### ISSUE TITLE
Update documentation to speak to game UI

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1015]
### Context
Many folks that use excalibur are confused about the proper way to do UI for games. 

### Proposal
We should add a section to the documentation discussing the ways that UI can be constructed in excalibur.

It should be clear that using HTML is the prefered UI mechanism, but also speak to reasons to use UIActor or other canvas rendered UI elements.

**Comment by Xstoudi** [comment]
Any update ?

**Comment by eonarheim** [comment]
There has been some updates here https://excaliburjs.com/docs/ui

Let us know if more needs to be addressed
