### ISSUE TITLE
TileMap should have getZIndex() too

### ISSUE THREAD

**Issue by baturinsky** [excaliburjs/Excalibur#1018]
There is currently no straight way to draw TileMap other than in background. Would be better if they'd have getZIndex() property, like Actor, and be drawn accordingly

**Comment by eonarheim** [comment]
Thanks @baturinsky this makes sense, it would be useful to position TileMaps at different z's for interesting effects.

For documentation here is the workaround @baturinsky is using

```typescript
lass TileMapActor extends ex.Actor {
    tileMap:ex.TileMap    
    public draw(ctx: CanvasRenderingContext2D, delta: number) {
      this.tileMap.draw(ctx, delta)
    }
}
```

**Comment by baturinsky** [comment]
Thanks. Btw, that workaround is a bit buggy, because Actor by default has OffscreenCulling trait, and tilemap therefore disappear when top left corner is off-screen. So, I have changed it to

```
class TileMapActor extends ex.Actor {
      
    public draw(ctx: CanvasRenderingContext2D, delta: number) {
      this.tileMap.draw(ctx, delta)
    }

    constructor(public tileMap:ex.TileMap){
      super()
      this.traits = []
    }
}
```

This seems to work right (so far)
