### ISSUE TITLE
API Documentation not rendering

### ISSUE THREAD

**Issue by NicolasVenne** [excaliburjs/Excalibur#1019]
Is anyone else experiencing the API links leading to empty routes?

Example of a broken link: https://excaliburjs.com/docs/api/v0.17.0/modules/_camera_.html

get this response:

NOT FOUND
You just hit a route that doesn't exist... the sadness.

**Comment by eonarheim** [comment]
@NicolasVenne Definitly not workign!

@kamranayub Have you seen this?

**Comment by NicolasVenne** [comment]
@eonarheim Good to know it's not just me!

Hopefully they get it back up soon, kinda hard to code without an API.

**Comment by eonarheim** [comment]
@NicolasVenne in the near term as a work aroun dthe doc source seems to still be available in our gh repo
https://github.com/excaliburjs/excaliburjs.github.io/tree/master/docs/api/edge/classes

**Comment by NicolasVenne** [comment]
Oh Perfect! Thank you so much, I was looking for it over on GH.

**Comment by kamranayub** [comment]
Fixed
