### ISSUE TITLE
Strip source maps from compiled distribution

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1026]
![image](https://user-images.githubusercontent.com/612071/43680485-805acf18-9801-11e8-9a3f-b4dcf9bdbdb6.png)

### Steps to Reproduce
In downstream projects using webpack with source maps enabled, the console is filled with sourcemap warnings because we don't ship the excalibur source as well.

### Expected Result
Downstream projects should not see these warnings

### Actual Result
Loads of warnings

### Environment

- browsers and versions: N/A
- operating system: N/A
- Excalibur versions: v0.18.0

### Current Workaround
Add an exclusion in the source-map-loader for excalibur
```javascript
module: {
      rules: [
        {
          test: /\.js$/,
          use: ["source-map-loader"],
          exclude: [
            path.resolve(__dirname,'node_modules/excalibur')
          ],
          enforce: "pre",
        },
```

**Comment by kamranayub** [comment]
Yeah this is common with TS libraries. Agree we need to strip them out on dist build.
