### ISSUE TITLE
Mouse clicks on <input>, <select> etc. elements outside of game window are not switching focus

### ISSUE THREAD

**Issue by baturinsky** [excaliburjs/Excalibur#1032]
### Steps to Reproduce
Add HTML elements such as input, select, probably many others on a page where excalibur game window is. Click on them

### Expected Result
They should get focus, so I can type in text, select an option from select, etc

### Actual Result
Nothing happens, they do not get focus. 

### Environment
Tested in Chrome and Firefox
Engine version excalibur@0.17.0-alpha.2522

### Current Workaround
I can switch focus to them and operate those elements normally by pressing TAB button certain number of times.

### Note
Clicks on links and buttons, on the other hand, works more or less normally. Though, UI libraries and such that depends on subscribing to click events can not work right too (for example, vuematerial.io button's ripple effect did not work)

**Comment by kamranayub** [comment]
Probably will need to configure PointerScope. By default only canvas
receives events. It's an option off the Engine you can specify on startup.

**Comment by baturinsky** [comment]
By default, clicks outside are possible, but behave like described above. Other options for PointerScope just disable clicks outside of canvas completely.

**Comment by kamranayub** [comment]
Ah I understand, thanks. We can take a look!

**Comment by eonarheim** [comment]
@baturinsky Just to confirm, did you configure pointer scope to be canvas?

```typescript
var game = new ex.Engine({
   canvasElementId: 'game',
   width: 600,
   height: 400,
   pointerScope: ex.Input.PointerScope.Canvas
});
```

I can't seem to reproduce the issue with excalibur (v0.18) set to Canvas pointer scope. I may have misunderstood.

Can you send a codepen or modify this one https://codepen.io/eonarheim/pen/jvBmXw?editors=1111?

**Comment by baturinsky** [comment]
Weird. Now it works right with ex.Input.PointerScope.Canvas for me too now. Both on your example and in my project. Maybe problem was caused by some other thing. Sorry, I should have tested things more thoroughly before reporting.

Thanks, you may close it now.

**Comment by kamranayub** [comment]
No problem, feel free to re-open if you encounter again!
