### ISSUE TITLE
Add SVG image support to Texture for Drawables

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1038]
### Context
Currently, only bmp, jpg, and png image types are support in excalibur texture system. Raster graphics have a few downsides, notably their potentially size and problems scaling up.

SVG would allow for infinite scaling, and super small image sources to download

### Proposal

Implement SVG as a supported Texture type,

```typescript

let svgTex = new ex.Texture('./path/to/my/cool.svg');

```

Some materials to reference:
* https://stackoverflow.com/questions/3768565/drawing-an-svg-file-on-a-html5-canvas
* https://developer.mozilla.org/en-US/docs/Web/API/Path2D

**Comment by kevin192291** [comment]
I was just working in the Texture class. Mind if I pick this one up?

**Comment by eonarheim** [comment]
@kevin192291 Go for it!

**Comment by eonarheim** [comment]
SVG's are now supported accidentally in `ex.ImageSource` in the webgl renderer!

![image](https://user-images.githubusercontent.com/612071/141598927-aae2f2e7-729d-4e29-ae2f-61fb106977d4.png)

**Comment by kevin192291** [comment]
Is this still an issue?  Want me to have a look at it?
