### ISSUE TITLE
Trigger Docs outdated

### ISSUE THREAD

**Issue by T00mm** [excaliburjs/Excalibur#1041]
The current docs at https://excaliburjs.com/docs/api/edge/classes/_trigger_.trigger.html is a bit outdated and this example won't work.

The actor doesn't have any collision so it will never trigger.

`actor.collisionType = ex.CollisionType.Active;`

The moveto is not on actor but on actions

`actor.actions.moveTo(100,200,100);`

I'm also quite new in this project but it seems these API docs aren't on Github or am I just that blind? If so, could you point me in the correct direction and I'll change the docs myself.

Kind regards,

**Comment by kamranayub** [comment]
Thanks for reporting! The docs for these are in the src/engine/docs folder.
The API reference docs are next to the methods in the source code.

If you'd like to submit a PR, that'd be awesome!
