### ISSUE TITLE
Get Started buttons on home page are bad links

### ISSUE THREAD

**Issue by bbugh** [excaliburjs/Excalibur#1064]
I almost gave up on excalibur because the call to action buttons are broken. In the process of making this bug I noticed that the top "Docs" links works though. Probably useful to have all of the links pointing to the correct location!

### Steps to Reproduce

1. Click on any of the "get started" buttons on the home page.
2. Observe that it goes to docs.excaliburjs.com instead of https://excaliburjs.com/docs

### Expected Result

The call to action buttons on the home page link to the correct location

### Actual Result

The server link fails to pull the sword from the stone and sends users to the wrong location(?)

**Comment by eonarheim** [comment]
@bbugh Good find, we'll get this fixed as soon as we can!

**Comment by eonarheim** [comment]
Looks like we missed this in the docs update

![image](https://user-images.githubusercontent.com/612071/48029995-4d2a9800-e115-11e8-9b20-b3bdd1ebef3b.png)

**Comment by eonarheim** [comment]
And this
![image](https://user-images.githubusercontent.com/612071/48030903-173ae300-e118-11e8-9591-1d1d2beddcbc.png)

**Comment by eonarheim** [comment]
@bbugh Fixed! Thanks for opening the issue
