### ISSUE TITLE
Implement Draggable Helper on Actors

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1092]
### Context
In order to properly implement drag and drop on an actor, it takes a lot of ceremonies to make it work. There should be a simpler way to enable actor drag and drop for actors.

Currently this:

```typescript
var block2 = new ex.Actor({
  pos: ex.Vector.Zero.clone(),
  anchor: ex.Vector.Zero.clone(),
  width: 50,
  height: 50,
  color: ex.Color.Red.clone(),
  collisionType: ex.CollisionType.PreventCollision
});

// Set drag flag
var boxPointerDragging = false;
block2.on('pointerdragstart', (pe: ex.Input.PointerEvent) => {
  boxPointerDragging = true;
});

// Set drag flag
block2.on('pointerdragend', (pe: ex.Input.PointerEvent) => {
  boxPointerDragging = false;
});

// Drag box around
block2.on('pointerdragmove', (pe: ex.Input.PointerEvent) => {
  if (boxPointerDragging) {
    block2.pos = pe.pointer.lastWorldPos;
  }
});

// Drag box around
block2.on('pointerdragleave', (pe: ex.Input.PointerEvent) => {
  if (boxPointerDragging) {
    block2.pos = pe.pointer.lastWorldPos;
  }
});
```

### Proposal

Add a `ex.Actor.draggable = true` utility gettter/setter/method to help remove this boilerplate

**Comment by MaanasArora** [comment]
Can I work on this issue?

**Comment by eonarheim** [comment]
@MaanasArora All yours! I've put the community in-progress label on the issue. Please open a draft PR as soon as you can.

**Comment by MaanasArora** [comment]
@eonarheim I have created a draft PR—sorry for the time taken! I was making sure I did everything correctly (I'm new to open source)
