### ISSUE TITLE
Update Excalibur to follow styleguide

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1102]
### Context
Some of the codestyle in Excalibur is not consistent. The team has drafted a new styleguide to help guide development

### Proposal
In several PRs update Excalibur with deprecation warnings where possible

* [x] PR to add STYLEGUIDE.md + update PR template for Excalibur
* [x] PR to update interface naming 
* [x] PR to update method naming 1 commit per file
* [x] PR to update to modern ES features `let` and `const` 
* [x] PR to update TSLint/ESLint rules to match styleguide

**Comment by alanag13** [comment]
we should consider adding ESLint rules for these items where possible.

**Comment by eonarheim** [comment]
@alanag13 good call, I've updated the issue to reflect that

**Comment by DavidLi119** [comment]
Hi, are there still any files to update to modern ES features `let` and `const`? I was thinking of doing ActionSpec.ts. Is that fine?

**Comment by eonarheim** [comment]
@DavidLi119 That would be awesome, open a PR!

**Comment by DavidLi119** [comment]
@eonarheim Quick question before I get started, what module do I install, when I open VSCode, every single method has red underline and it says it cannot find module `'../../build/dist/excalibur'`

**Comment by djcsdy** [comment]
Hi. Heads up: I am working on replacing all remaining instances of `var` with `let`/`const`.

**Comment by eonarheim** [comment]
@djcsdy Thanks! Please split with one commit per updated file as best you can

**Comment by djcsdy** [comment]
Oops. Sorry. I didn’t mean to spam this issue with every commit. I was trying to follow the style I observed in previous commit messages, and I forgot that GitHub would helpfully cross-reference the commits.

**Comment by eonarheim** [comment]
Complete!
