### ISSUE TITLE
[chore] Write test to confirm event handlers execute in order of subscription

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1107]
### Context
This was an existing TODO see #1105 

Currently we dont have a test that shows handlers execute in the same order as subscription.

### Proposal
Write a test in `EventSpec.ts` that registers `n` number of handlers in a certain order and tests that those handlers execute in the same order.

**Comment by agrgic16** [comment]
Hi guys, I'm interested in helping with this if nobody is working on it already.

**Comment by eonarheim** [comment]
@agrgic16 Excellent, I'll review the PR tonight
