### ISSUE TITLE
Unclear Documentation Surrounding Physics

### ISSUE THREAD

**Issue by justjoeyuk** [excaliburjs/Excalibur#1129]
The documentation isn't clear on letting the user know that Fixed-Fixed collisions aren't possible. I tried to *cheat* the system by using two fixed bodies and just moving them around. However, when looking through the source, I found:

```
// if both are fixed short circuit
    if (actorA.collisionType === CollisionType.Fixed && actorB.collisionType === CollisionType.Fixed) {
      return false;
    }
```
I think this should be made explicit, or at least a small explanation of each type and their relationship. Happy to do this myself, just putting this here as a note to anybody interested.

**Comment by eonarheim** [comment]
Good call out, this should be made explicit 👍
