### ISSUE TITLE
undefined is not a constructor (evaluating 'new window.AudioContext') on Safari

### ISSUE THREAD

**Issue by magnusandy** [excaliburjs/Excalibur#1132]
the error is `TypeError: undefined is not a constructor (evaluating 'new window.AudioContext')`

### Steps to Reproduce

I reproduced using a fresh clone of the example-ts-webpack, and tested with both 0.21.0 and 0.22.0 versions of excalibur. Start the running the project and press the play button and error will appear and the game will not start.

More specifically the error comes from calling `ex.AudioContextFactory.create();` the `create` function does not properly set the audio context if the case is webkit.

 

### Expected Result

Expect for the audio context to be defined or gracefully fail

### Actual Result

Error is thrown and execution halts. 

### Environment

- browsers and versions: Safari 12.1 (14607.1.40.1.4) 
- operating system: OSX 
- Excalibur versions: 0.21.0, 0.22.0 

### Current Workaround

Its possible to redefine the static `create` method to return the webkitAudioContext

`ex.AudioContextFactory.create = () => new (<any>window).webkitAudioContext();`

which would allow at least for the game to load.

### Possible Solution
possible fix might be something like:

```
public static create(): AudioContext {
    if (!this._INSTANCE) {
      if ((<any>window).AudioContext) {
        this._INSTANCE = new (<any>window).AudioContext();
      } else if (<any>window).webkitAudioContext) {
         this._INSTANCE = new (<any>window).webkitAudioContext();
      }
    }
    return this._INSTANCE;
  }
```

**Comment by eonarheim** [comment]
@magnusandy Good find, this is very odd. `Polyfill.ts` should be performing a similar function to your proposed solution, it is functionally the first import in engine and should have run before the static method call. I wonder if the polyfill is not working as we expect or webpack is producing a bundle in an unexpected order

https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Polyfill.ts#L28-L35

**Comment by eonarheim** [comment]
I can reproduce this in latest safari in browserstack, very good find

![image](https://user-images.githubusercontent.com/612071/56458961-e8759980-6352-11e9-9d68-a01740d8df9d.png)

**Comment by eonarheim** [comment]
The plot thickens, using un-minified excalibur seems to work no issues 😢 

![image](https://user-images.githubusercontent.com/612071/56459160-4905d600-6355-11e9-96c2-9bc318f621bd.png)

**Comment by eonarheim** [comment]
Minification seems to have re-ordered the definition of the polyfill. We can address this in 2 ways, export a polyfill applier function that can be called (currently it's a side effecting import in `Engine.ts`), update webpack configuration to produce the correct ordering.

![image](https://user-images.githubusercontent.com/612071/56459211-f2e56280-6355-11e9-8af6-3010045f54da.png)

**Comment by magnusandy** [comment]
Interesting, I didn't even think of the build process. I tried messing around here with the webpack config to try get the polyfill to be applied earlier without much success (but I am not too familiar with webpack). I think your proposed code and solution makes more sense in the long run, as it doesn't rely on tweaking the build process to work properly.

Thanks for the speedy response! I have really been enjoying building with Excalibur 😄
