### ISSUE TITLE
Update Excalibur compilation to enable full TS strictness

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1143]
### Context
As the typescript compiler has evolved it has brought new stricter safe-guards like "no implicit any", this enhances our ability to reason about types.

### Proposal
Turn up the compiler strictness flags as far as is reasonable and fix any associated errors in Excalibur.

**Comment by djcsdy** [comment]
FWIW I have been working on this in https://github.com/djcsdy/Excalibur/commits/better-types

I will be working on this again in a few weeks, but if someone else wants to pick it up in the meantime, they’re welcome to use my work as a starting point.

**Comment by eonarheim** [comment]
Excellent 👍 go for it

**Comment by eonarheim** [comment]
Dup of #1213, picking a winning (for some reason I made two issues?)
