### ISSUE TITLE
[Proposal] Alternative Functional API

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#1160]
### Context

We have different mechanisms in Excalibur to add functionality to actors/objects ranging from constructor params, traits, public properties, etc. To make it a bit more confusing, some things can be overridden or provide class hooks (`onPostUpdate`) while others need to be subscribed to with events (`onpostcollision`). Further, some things only work when done in specific places (`onInitialize`).

Our goal is to make Excalibur _simple_ and easy to use. Perhaps we can take inspiration from other libraries on how to simplify our API and ways to use Excalibur. I use React day-to-day and the new Hooks API provides some nice inspiration.

### Proposal

It would be great to unify all the APIs we have using a consistent pattern. Rather than force users to remember 3-4 ways to do something, we could get it down to just one way that still provides all the flexibility we need.

If we took a page from [React Hooks](https://reactjs.org/docs/hooks-intro.html), the APIs could be organized by functional area (ECS):

- `ex.Gfx`
  - `useDraw` (replaces `Actor.onPostDraw`)
  - `useDebugDraw`
  - `useAnimation`
  - `useSprite`
  - `useEffect`
  - `useZIndex`
  - `useScale`
  - `useVisibility`
- `ex.State`
  - `useState`
  - `useStore`
- `ex.Physics`
  - `useDimensions` (wxh)
  - `useCollision`
  - `useCollisionGroup`
  - `useVel`
  - `usePos`
  - `useRotation`
- `ex.Actions`
  - `useChain`
  - `useSingle`
  - `useParallel`
  - `useTrigger`
- `ex.Input`
  - `useKeyboard`
  - `usePointer`
  - `useGamepad`
  - `useVibration`
- `ex.useEngine`
- `ex.useResource`
- `ex.useScene`
- `ex.useCamera`

We could possibly **do away** with the idea of an "Actor" and move towards more entity-like structures that just have traits.

This is an example NPC actor that rewrites the sample-platformer NPC but using a "functional" actor with an ECS-like hook system:

```typescript
import * as ex from "../Excalibur/build/dist/excalibur.js";
import { botRedSpriteSheet, npcSprite } from "./resources";

const NPC = ({ x, y }: { x: number; y: number }) => {
  const [pos, setPos] = ex.Physics.usePos(x, y);
  const [zIndex, setZIndex] = ex.Gfx.useZIndex(-1);
  const [onGround, setOnGround] = ex.State.useState(false);
  const [hurt, setHurt] = ex.State.useState(false);
  const [hurtTime, setHurtTime] = ex.State.useState(0);
  
  ex.Physics.useCollision({
    type: ex.CollisionType.Active,
    shape: ex.Shape.Box(32, 50),
    offset: new ex.Vector(0, 3),
    group: ex.CollisionGroupManager.groupByName("player")
  });

  ex.Gfx.useAnimation(ctx => {
    const hurtleft = ctx.getAnimationByIndices(
      botRedSpriteSheet,
      [0, 1, 0, 1, 0, 1],
      150
    );
    hurtleft.scale = new ex.Vector(2, 2);

    return hurtleft;
  });

  ex.Gfx.useAnimation(ctx => {
    const hurtright = ctx.getAnimationByIndices(
      botRedSpriteSheet,
      [0, 1, 0, 1, 0, 1],
      150
    );
    hurtright.scale = new ex.Vector(2, 2);
    hurtright.flipHorizontal = true;

    return hurtright;
  });

  const [idleAnim, setIdleAnim] = ex.Gfx.useAnimation(ctx => {
    const idle = ctx.getAnimationByIndices(botRedSpriteSheet, [2, 3], 800);
    idle.scale = new ex.Vector(2, 2);

    return idle;
  });

  const [leftAnim, setLeftAnim] = ex.Gfx.useAnimation(ctx => {
    const left = ctx.getAnimationByIndices(
      botRedSpriteSheet,
      [3, 4, 5, 6, 7],
      100
    );
    left.scale = new ex.Vector(2, 2);

    return left;
  });

  const [rightAnim, setRightAnim] = ex.Gfx.useAnimation(ctx => {
    const right = ctx.getAnimationByIndices(
      botRedSpriteSheet,
      [3, 4, 5, 6, 7],
      100
    );
    right.scale = new ex.Vector(2, 2);
    right.flipHorizontal = true;

    return right;
  });

  ex.Actions.useChain(actions =>
    actions
      .moveBy(100, 0, 20)
      .moveBy(-100, 0, 20)
      .repeatForever()
  );

  const [vel, setVel] = ex.Physics.useVel(0);

  ex.useEngine(engine => {
    if (vel.x < 0) {
      setLeftAnim();
    }
    if (vel.x > 0) {
      setRightAnim();
    }
    if (vel.x === 0) {
      setIdleAnim();
    }
  });

  ex.Gfx.useDraw(ctx => {
    npcSprite.draw(ctx, -10, -100);
  })
};

export default NPC;
```

## Benefits

Some things I personally really like about this:

- Everything has a consistent API. If you want to **do anything** with an entity, the API is `use*`.
- Everything is flat. There is no special order or way to use things, it's all at the top-level.
- Everything is encapsulated. You don't need a global engine being passed around because hooks can encapsulate that and provide a context. State can have a getter and setter returned. Other things can return specific setters to avoid map/dictionary usage (like `this.addDrawing(key, drawing)`).
- Excalibur can control and understand how each hook is executed vs. putting the mental burden on the dev to remember/understand. "Does this go in `onInitialize`, do I use `.on`, do I override a method?", etc. etc. it's all tightly controlled.
- By forcing taking a "dependency" on the hooks, the engine can do all sorts of optimizations that are otherwise not able to be done in the current API.

## Questions

- How possible is this? React does it but it's pretty magical.
- Does this have memory implications? We've used classes historically due to benefits of the prototype.
- The return API of the hooks is up for debate; would we be able to cover most use cases?
- Is it too flat? React functional components are nice but designed to be composable. Would the same composability exist in Excalibur or would these start to get too huge?
- How do you reference other entities? How do you ask for info?
  - Possibly using helpers that know how to check an entity, e.g. `ex.Physics.getBounds(NPC)`

**Comment by eonarheim** [comment]
Closing for now, we can maybe discuss this at the next monthly or in the gh discussion?
