### ISSUE TITLE
Consistent getters and setters on game objects

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#117]
### Context
Sometimes game objects have a property to get/set values and other times they have a getValue setValue method. This inconsistency has the potential to cause confusion when working with Excalibur.

### Proposal
Excalibur should use getters and setters.

```
// property
actor.scale = 3
// vs
sprite.setScale(3);
```

**Comment by kamranayub** [comment]
I prefer jquery/other libraries that don't do `get`/`set` but rather use an overloaded method.

```js
actor.scale(0.5); // set
actor.scale(); // get
```

Cleaner, clearer, easy to use.

**Comment by kamranayub** [comment]
Further idea, we should at least consider all standard getters/setters also throwing up an event. This is typical in a ViewModel-based applications, but since we have an event dispatcher already, it would be trivial to add this niceity.

Consider the issue with updating actor's z-index and scene needing to rebalance its draw tree. By subscribing to any actor's z-index changing, it could do it without Actor being coupled directly to the scene.

```
public function zindex(value: number = null): number {
   if (value !== null) {
     this._zindex = value;
     this.notifyPropertyChanged("zindex");
   }
   return this._zindex;
}
```

**Comment by eonarheim** [comment]
@kamranayub I think having truly observable properties would be excellent, especially for games, but out of the scope of this pull request. Perhaps this is a new issue?

@kamranayub @alanag13 @jedeen Do we feel good about merging this request now?

**Comment by kamranayub** [comment]
I think you meant to comment on the PR, I pulled out the suggestion to put into this issue (and only mentioned it in the PR as future work)

**Comment by eonarheim** [comment]
Oops, your right haha :-1: for me

**Comment by kamranayub** [comment]
Watch, history can be amended.

**Comment by eonarheim** [comment]
Observable properties would be awesome in a game environment!

**Comment by kamranayub** [comment]
I suppose if we tried to follow ES6 it would be nice, but not sure if `Object.observe` makes sense for Excalibur... makes more sense to use our own event dispatcher as it runs in the update loop.

**Comment by eonarheim** [comment]
One thing that may make the code cleaner and easier to use is to implement JS property getter/setters which are pretty much supported everywhere see here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set

A could candidate for this would be `Actor.setZIndex(10)`, you could simplify to just `Actor.z = 10` doing something like this

```typescript
class Actor {
private _z:number = 0;
   get z():number {
      return this._z;
   }
   set z(newIndex: number) {
      this.scene.cleanupDrawTree(this);
      this._z = newIndex;
      this.scene.updateDrawTree(this);
   }
}
```

Which generates the es5 getter/setter syntax
```javascript
var Actor = (function () {
    function Actor() {
        this._z = 0;
    }
    Object.defineProperty(Actor.prototype, "z", {
        get: function () {
            return this._z;
        },
        set: function (newIndex) {
            this.scene.cleanupDrawTree(this);
            this._z = newIndex;
            this.scene.updateDrawTree(this);
        },
        enumerable: true,
        configurable: true
    });
    return Actor;
})();
```

I think this would be pretty slick @jedeen @kamranayub

**Comment by kamranayub** [comment]
As long as we maintain compatibility with the maximum browsers, I'm totally
cool with this--and will make it more consistent.

**Comment by eonarheim** [comment]
Also other physical quantities may be good candidates for getters and setters

```typescript

    /**
     * Gets the calculated width of an actor, factoring in scale
     */
    public getWidth() {
       return this._width * this.scale.x;
    }
    /**
     * Sets the width of an actor, factoring in the current scale
     */
    public setWidth(width) {
       this._width = width / this.scale.x;
    }
    /**
     * Gets the calculated height of an actor, factoring in scale
     */
    public getHeight() {
       return this._height * this.scale.y;
    }
    /**
     * Sets the height of an actor, factoring in the current scale
     */
    public setHeight(height) {
       this._height = height / this.scale.y;
    }

```

**Comment by eonarheim** [comment]
No longer needed, part of our code style
