### ISSUE TITLE
VSCode config (.vscode) should be ignored or fixed

### ISSUE THREAD

**Issue by gargrave** [excaliburjs/Excalibur#1173]
Just a little third-party perspective from a non-core dev.

This is more a "developer experience bug" than a production bug, but when working on https://github.com/excaliburjs/Excalibur/issues/1172, I noticed I was having some issues getting VSCode to indent correctly, and ultimately it was because the `.vscode` config directory has been committed to the repo.

There are a couple things I noticed here that are problematic:

These two lines effectively _force_ VSCode to use 4 spaces for indentation, even though the bulk of the codebase is clearly 2 spaces:

```
"editor.tabSize": 4,
"editor.detectIndentation": false
```

I also noticed there are config settings for various extensions, which seems a bit iffy for me, as I (and most likely any non-core devs) do not have these installed. It's not really a _problem_, but I like to keep my own `settings.json` for each project, which is not really possible when it's committed to a public repo.

So I'm just curious, is there a strong reason `.vscode` (and particularly `settings.json`) is committed? It's generally a best practice not to commit local configuration files, and it makes for a bit of an unattractive experience when I have settings forced on me that I don't like.

If it _really_ needs to stay in the repo, I would suggest fixing those two settings above (just remove `detectIndentation` altogether, IMO), as the indentation setting does not match reality. I would also lean towards removing any extension-specific settings (e.g. `restructuredtext`).

I would be happy to submit a PR in either direction if either of these is acceptable (my suggestion being towards ignoring it altogether), but I wanted to check if there were historical/contextual reasons for this.

**Comment by kamranayub** [comment]
I believe this was added before we added Prettier. We should be able to
remove the settings, though we may need to document the extension settings
for them to work properly in the CONTRIBUTING doc.

**Comment by eonarheim** [comment]
@gargrave Agreed, lets remove the mentioned settings and remove extension specific settings

**Comment by gargrave** [comment]
Sounds good! If nobody beats me to it, I will try to submit a PR in the next day or so. Should obviously be super small and simple. :)

**Comment by gargrave** [comment]
I obviously totally slipped on this, and my apologies for that. I got tied up with other things and then completely forgot about this request. :(

That said, it looks like you have updated this accordingly in the meantime, so I will close this issue. Thanks, and sorry for any inconvenience!
