### ISSUE TITLE
[Nitpick] Broken link on website

### ISSUE THREAD

**Issue by Darker7** [excaliburjs/Excalibur#1253]
The link to typescriptlang.org on the website is https://typescriptlang.org but should be https://www.typescriptlang.org/

**Comment by eonarheim** [comment]
@Darker7 Thanks, we'll take a look ASAP

**Comment by eonarheim** [comment]
Link locations https://github.com/excaliburjs/excaliburjs.github.io/search?q=https%3A%2F%2Ftypescriptlang.org&unscoped_q=https%3A%2F%2Ftypescriptlang.org
