### ISSUE TITLE
Remove obsolete .extend() semantics in Excalibur

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1276]
### Context
Browsers natively support ES6 classes, there is no need for a custom inheritance scheme in Excalibur. For any future down level support we should point people to tools like babel/TypeScript.

### Proposal

Remove these lines of code 
and any associated tests or documentation around it.
https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Class.ts#L60-L122

**Comment by Guzzler** [comment]
Hey I would like to claim this. WIll make a PR soon!

**Comment by Guzzler** [comment]
This has been completed in the above PR and can be reviewed. Hope this helps! @eonarheim
