### ISSUE TITLE
Add utility to get/set ex.Vector size

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1277]
### Context
It would be useful to set the magnitude of a vector, this allows easy scaling or capping at a maximum value. This is especially useful in physics simulations.

### Proposal

I propose something like the following (there is probably a more efficient method of changing the size of the vector)

```typescript
  /**
   * The magnitude (size) of the Vector
   * @obsolete magnitude will be removed in favor `.size` in version v0.24.0
   */
  public magnitude(): number {
    return this.distance();
  }
  
 /**
  * The size (aka magnitude) of the Vector
  */
  public get size(): number {
    return this.distance();
  }

  public set size(newLength: number) {
    this.normalize().scale(newLength);
  }
```

Usage:

```typescript

const vel = new ex.Vector(3, 4);

console.log(vel.size); // 5
vel.size = 13;

// Automatically calculates to correct scale
console.log(vel.x); // 5
console.log(vel.y); // 12
```

**Comment by saahilk** [comment]
Hi, I'd like to work on this issue.

**Comment by eonarheim** [comment]
@saahilk All yours! I've added the community in-progress label for you

**Comment by saahilk** [comment]
@eonarheim Alright let me get started then!

**Comment by saahilk** [comment]
@eonarheim Is there a doc where I can find how to setup the environment? I only found [this](https://github.com/excaliburjs/Excalibur/blob/master/.github/CONTRIBUTING.md). Also could you point me to the files I should look through to get started?

**Comment by eonarheim** [comment]
@saahilk Let me know if this doesn't cover everything https://github.com/excaliburjs/Excalibur#environment-setup, please let me know if there are any gaps in the readme 👍

**Comment by eonarheim** [comment]
We'll want to fix the readme if any steps are ambiguous, missing, wrong, or poorly written

**Comment by saahilk** [comment]
@eonarheim Hi which files do I look at to start with?

**Comment by saahilk** [comment]
@eonarheim Do I keep the existing magnitude function marking it as obsolete or just remove it adding the size() function?

**Comment by eonarheim** [comment]
Good question, lets keep the existing magnitude function with an `@obsolete` in the JSDoc comment. We'll remove it in the future v0.25.0 release.

**Comment by saahilk** [comment]
Hi @eonarheim the comments in the usage you have mentioned in the above issue is incorrect. When you set vel.size=13 the unit vector is (0.6, 0.8) and the scaled vector will be (7.8, 10.4) and not (5, 12).

**Comment by saahilk** [comment]
@eonarheim Could you check the modified pull request [here](https://github.com/excaliburjs/Excalibur/pull/1298).
