### ISSUE TITLE
Massive overuse of private modifiers

### ISSUE THREAD

**Issue by Darker7** [excaliburjs/Excalibur#1324]
## Context

I was trying to do more complex things with sprites but the API didn't provide me with what I wanted, so I decided to take a look at the source code to try and see if I could find some workaround by copying and changing some of excalibur's code, where I found that most of what I want would already be possible if I simply extended Sprite were it not for the fact that all of it is locked away behind private modifiers.

## Proposal

Replace all unnecessary private modifiers with protected modifiers.

Of course necessary private modifiers do exist, such as in the case of keeping track of IDs or it requiring more complicated access behaviour (i.e. getters and setters) &mdash; however whenever there is no reason to withhold a property or method from inheriting classes it should be protected instead or at least have a protected getter and setter.

### Reasoning

The obvious alternative to this is expanding the API to offer support for these uses as well but there will always be *some* functionality you haven't thought of in which case allowing users to implement a solution themselves &mdash; instead of having to asking you to provide it and then forcing them to wait until you actually do &mdash; is preferable. 
(Pull requests are not a solution to this since they still have to await screening before being accepted, not to mention that they require increased rigor and robustness.)

**Comment by jedeen** [comment]
Thanks for opening an issue! Could you please describe your use case for modifying Sprites? It would make it easier for us to help if we a bit more context. If there’s functionality that’s currently missing or unavailable from the API that makes sense for us to provide, we’d love to hear about it!

We strive to make Excalibur reasonable to use and extend, and API accessibility helps manage those goals, as well as our ability to improve and support the engine.

As an interim stopgap for extending Sprites, the property access restrictions that TypeScript enforces can be ignored by casting the property to type `any`, although this will disable TypeScript’s more helpful features.

**Comment by eonarheim** [comment]
Will open when we have more context about the issue.
