### ISSUE TITLE
Shorthand `vec()` for initializing vectors

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#1340]
### Context

Consider the following case that will be done a lot within an Excalibur codebase:

```ts
new Actor({ pos: new Vector(100, 200) })
```

Having to constantly type `new Vector` is a bit of a drag since it'll be typed a LOT.

### Proposal

We were discussing some alternatives in person, such as a shorthand function:

```ts
vec(0, 0);
```

~~Or maybe a tuple type:~~

```ts
// type VectorCompact = [number, number];
// let v: VectorCompact = [0, 0];
```

**Comment by eonarheim** [comment]
Lets create an exported function in `Algebra.ts` to do the `vec(...)` shorthand for now, the tuple will take a larger lift in the engine.

Something like this, with some tests
```typescript
export function vec(x: number, y: number) {
  return new Vector(x, y);
}
```
