### ISSUE TITLE
class Pointer does not have class Pointers events

### ISSUE THREAD

**Issue by lordnox** [excaliburjs/Excalibur#1345]
### Steps to Reproduce
```
game.input.pointers.primary.on('down', event => {
  // expected "event" to be Input.PointerEvent
  const evt = event as Input.PointerEvent // this cast does work
  evt.pos // exists in TypeScript
  event.pos // does not but is expected
})
game.input.pointers.on('down', event => {
  // the default pointers do correctly cast the type to Input.PointerEvent
  event.pos // does exist
})
```
### Expected Result
I did expect that a specific Pointer does have the PointerEvents associated

### Actual Result
PointerEvents are not correctly Typed for class "Pointer"

### Current Workaround
See code above

**Comment by eonarheim** [comment]
@lordnox Thanks for the find! This was an oversight during a recent refactoring. We'll get this resolved asap.
