### ISSUE TITLE
Add chunk system for tile maps with procedural content generation support

### ISSUE THREAD

**Issue by jurca** [excaliburjs/Excalibur#1348]
### Context
Some projects require a much larger map and/or would prefer to use procedural content generation for seemingly infinite worlds.

### Proposal
Implement an extension of the `TileMap` class that manages relatively small rectangular chunks of tiles, allowing for the required chunks to be generated on-demand once they are needed.

Chunks size, the maximum expected size of the world and the chunk generator must be configurable.

Since the goal is providing support of up to 9007199254740991×9007199254740991 tiles, the chunk system must include a configurable garbage collector of chunks that are "too far from the current viewport" (or match other configurable predicate if preferred). Dropping chunks from memory should be fine for most projects, since it is unlikely the tile map itself would be used to store results of any of the player's actions.

API proposal:

```typescript
type ChunkGenerator = (chunkX: number, chunkY: number, chunkSize: number, tileMap: ChunkSystemTileMap, engine: Engine) => TileMap

type ChunkSystemGarbageCollectorPredicate = (chunk: TileMap, engine: Engine) => boolean

interface ChunkSystemTileMapArgs extends Omit<TileMapArgs, 'x' | 'y' | 'rows' | 'cols'> {
    chunkSize: number
    maxRows: number
    maxCols: number
    chunkGenerator: ChunkGenerator
    chunkGarbageCollectorPredicate: ChunkSystemGarbageCollectorPredicate
}

class ChunkSystemTileMap extends TileMap {
  constructor(config: ChunkSystemTileMapArgs)

  // no new methods, just overrides of some of TileMap's methods
}
```

The related PR should also include a basic implementation of the `ChunkSystemGarbageCollectorPredicate` and at least one demo implementation of the `ChunkGenerator` that utilizes the [Perlin noise](https://excaliburjs.com/docs/api/edge/modules/_math_perlinnoise_.html) generator.

**Comment by kamranayub** [comment]
This would be an awesome feature 🤘

**Comment by jurca** [comment]
Just to give you a status update, I have started to work on this, but I will need to do some changes to the API I proposed in this issue:

1. The `ChunkSystemTileMap` cannot extend the `TileMap` class due to events fired by `TileMap`. I will, however, do my best to have the public API match the API of `TileMap`
2. An `emptyCell: Cell` option will be required in the `ChunkSystemTileMapArgs` so that I can have the chunks updated only in the `update` method and so that the `getCell*` methods do not need to have their signatures modified.

I'll start a WIP PR once I have the `ChunkSystemTileMap` class implemented.

**Comment by jurca** [comment]
@kamranayub I've started a work-in-progress PR to get your feedback on the code so far here: https://github.com/excaliburjs/Excalibur/pull/1355

Any feedback would be greatly appreciated :).

I'll keep working on what's missing in the meantime whenever I have the time.
