### ISSUE TITLE
Excalibur ECS Implementation Goals and Guide

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1361]
## Goals

* Break behavior out of Actor and other types into Components/Systems for:
   * Maintainability of the code base
   * Testability of the code base (new components/systems need high test coverage)
   * De-duplication
   * Tree shaking ability
* Excalibur should where possible maintain
   * The easy to use property
   * It should "just work" property
   * It should not surprise users
* Goal are **not**:
   * to be a pure ECS
   * to require users to know about ECS in order to use Excalibur
   * to purely increase performance 

## Guide

The current plan is to avoid breaking changes or regressions as much as possible. The plan is to add ECS in 2 steps:

First step the ECS foundations will be installed 
  * Entity type - Actors will be entities with pre-built components
  * Base Components
    * [x] Transform
    * [x] Motion
    * [x] Offscreen
    * [x] Drawing
  * Base systems
    * [x] Motion
    * [x] Drawing
  * Query mechanisms - what entities match what criteria

Second step ECS everywhere
   * All Excalibur behavior should be driven (at least under the hood) by ECS 
   * Particles
   * Collision
   * Triggers

**Comment by DaVince** [comment]
Nice, I've been waiting for this feature!

**Comment by eonarheim** [comment]
@DaVince let me know how it goes, it is missing some some convenience features at the moment. All systems need to be loaded in by hand for each Scene

**Comment by eonarheim** [comment]
@DaVince WIP migrating existing draw to to ECS #1643

**Comment by DaVince** [comment]
Thanks. I will check this out when I can, but time/energy has been scarce. It's been slow going as well as I've been running into having to figure out what goes where. Is it possible to add a very basic snippet containing the minimally required code to use it?

**Comment by eonarheim** [comment]
Good point @DaVince I'll get some documentation on ECS usage as a part of this PR

**Comment by AndrewCraswell** [comment]
Hey! Just wanted to drop in and say this is amazing. I've been lurking watching this project for awhile. Built my first game last night in a few hours (first time reading the docs, they're awesome!) and it was such a breath of fresh air from other frameworks like Phaser.

The ECS change is also a key differentiator. Before I saw this, my plan had been to attempt to combine Excalibur with ECSY. I'm curious about what drove the decision to create an ECS from scratch? Although the future of ECSY might be a bit in doubt at the moment, the key win it had was a Devtools extension. At the least I wonder if the same events that the ECSY Devtools expects could be emitted so that the tool can interop with Excalibur? And having another team drive that infrastructure might help keep Excalibur lean.

ECSY
https://github.com/ecsyjs/ecsy

ECSY Devtools
https://github.com/ecsyjs/ecsy-devtools

**Comment by eonarheim** [comment]
@AndrewCraswell Thanks for checking us out! Please do send us any feedback you have in the discussions! And we'd love to see your game as well!

There are a few reasons we decided chart our own course on an ECS in TypeScript:
* We want it to be 100% suited for Excalibur, keeping that ease of use and keeping tight seamless integration first of mind (And not require users to necessarily be aware of the ECS architecture)
* We want Excalibur's internal organization to be more maintainable on the road to 1.0, ECS is a nice way to organize
* We want to be TypeScript first and leverage the type system when using an ECS to build games
* We generally try to avoid explicit dependencies on other projects to control our own destiny, so to speak

We will look into the dev tools idea, no promises on anything anytime soon 😄 but building a plugin/extension/hook that can interop with an existing devtools is worth exploring.

**Comment by DrSensor** [comment]
This might give some inspiration (all js)
- [blazing fast ECS using *TypedArrays*](https://github.com/NateTheGreatt/bitECS)
- [ECS over WebRTC](https://github.com/3mcd/javelin/tree/master/examples/networking)
- [ecs-benchmark](https://github.com/noctjs/ecs-benchmark)

**Comment by DrSensor** [comment]
​

**Comment by eonarheim** [comment]
Thanks for all the awesome comments on this issue! I'm closing this issue for now but we may open more when we have changes to make.

We will definitely reference all the links posted!
