### ISSUE TITLE
Excalibur crashes when using tilemaps and actors together

### ISSUE THREAD

**Issue by DaVince** [excaliburjs/Excalibur#1418]
### Steps to Reproduce
```ts
import { Engine, Loader, Actor } from 'excalibur';
import { TiledResource } from '@excaliburjs/excalibur-tiled';

const game = new Engine();
const loader = new Loader();
const levelResource = new TiledResource('assets/map/single-layer.json');
loader.addResource(levelResource);

game.start(loader).then(() => {
  const tileMap = levelResource.getTileMap();
  game.addTileMap(tileMap);

  const actor = new Actor();
  game.add(actor); // Game crashes on this line
});
```

### Expected Result
The map should display, along with any defined actors.

### Actual Result
The entire browser tab freezes and needs to be force closed.

### Environment
- browsers and versions: Chromium 79.0.3945.130, Firefox 72.0.2
- operating system: Ubuntu 19.10
- Excalibur versions: 0.23.0

### Notes
- UIActors are fine; the problem specifically seems to happen when combining the Tiled TileMap and an Actor.
- `import * as ex from 'excalibur'` instead of the above import style makes no difference.

### Current Workaround
None.

**Comment by DaVince** [comment]
I've slightly modified the CodeSandbox sample to demonstrate the crash: https://codesandbox.io/s/excalibur-tiled-example-ev0mt

**Comment by DaVince** [comment]
I have done further testing by writing a map loader for an entirely unrelated map format (specifically, some entirely inconsequential DOS game which stores its maps as text files).

End result: the culprit does not seem to be the Tiled map loader, but possibly something in Excalibur's code itself that is causing the browser to lock up.

I'd like to try and contribute to the project and will be hunting down this issue in the Excalibur code. First, I'd like to retest this issue on the latest version; is there any sort of development branch or do I just check out `master`?

**Comment by eonarheim** [comment]
Thanks for digging into this!

Master is the best place to work against for fixes, if you want to test a
specific version of excalibur when released we have git tags that
correspond to the release number.

Please open a PR as soon as you can to discuss your fix/findings

Thanks again!

**Comment by DaVince** [comment]
Found the method that caused the lockup: stub out method `TileMapImpl.collides()` and the browser doesn't freeze anymore.

Will attempt a fix and send a PR tomorrow.

**Comment by DaVince** [comment]
https://github.com/excaliburjs/excalibur-tiled/issues/87 is a duplicate of this and can also be closed :)
