### ISSUE TITLE
Bug: Util.extend deep doesn't do what you expect

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#1442]
I was writing a spec for `Util.extend` and noticed passing `deep` param wasn't actually doing a deep merge, it was just doing a nested shallow merge...

I think we could also evaluate whether we need this utility anymore now with ES2015 classes and spread support. I think this was mainly to enable vanilla JS `ex.Actor.extend(...)` syntax which can be replaced with proper ES2015 classes.

### Steps to Reproduce

See `src/spec/UtilSpec.ts`

### Expected Result

If it _should_ deep merge, then do that but otherwise remove the `deep` parameter.

### Environment

- browsers and versions: Chrome 80
- operating system: Windows
- Excalibur versions: 0.23.0

### Current Workaround

Use a merge utility from `lodash` or equivalent.

**Comment by eonarheim** [comment]
@kamranayub I'm thinking we should perhaps deprecate this feature? It's not really used widely in the codebase, and modern JS and other libraries support this better.

**Comment by kamranayub** [comment]
Yep! Agree.

**Comment by eonarheim** [comment]
Extend is deprecated
