### ISSUE TITLE
SpriteFonts should support different target colors

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#148]
This could be done by adding a custom sprite effect on top of the underlying sprites and applying the new target color over the pixel data of the original image.

**Comment by kamranayub** [comment]
This isn't supported anymore. The draw function is not called on SpriteFont by a label.

Additionally, when using `opacity1, existing effects will not be preserved due to this logic:

```
if (this.previousOpacity !== this.opacity) {
  charSprite.clearEffects();
  charSprite.addEffect(new ex.Effects.Opacity(this.opacity));
}
```
