### ISSUE TITLE
MMORPG Loading textures

### ISSUE THREAD

**Issue by Qarasina** [excaliburjs/Excalibur#1486]
Hi, I'm trying to create a javascript MMORPG project via Excalibur right now, the main concern being that I'm not sure if it's possible to load the textures as we progress through the game? MMORPGs often use a lot of textures, so I don't feel like asking people to load everything and keep in mind from the start

**Comment by eonarheim** [comment]
Hi @Qarasina, textures can be loaded incrementally without using the main loader by calling the [`Texture.load()`](https://excaliburjs.com/docs/api/v0.23.0/classes/_resources_texture_.texture.html#load) which returns a promise like that resolves when the texture is loaded and the bitmap is ready for use. It is important to be sure a texture [is loaded](https://excaliburjs.com/docs/api/v0.23.0/classes/_resources_texture_.texture.html#isloaded) before trying to draw it or an error will result.

**Comment by Qarasina** [comment]
Thanks :)
