### ISSUE TITLE
Remove audio tag implementation 

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1487]
### Context
We are dropping support for older browsers, with the wide-spread support of the WebAudio API the need for our own HTML5 tag based implementation of classes is gone. 

### Proposal
* [ ] Remove `AudioTagInstance`
* [ ] Update `AudioInstance` implementation to use WebAudio only (perhaps even simplify)
* [ ] Update any affected tests to remove isseus

**Comment by kamranayub** [comment]
We should also have a wider IE11 tracking / planning deprecation issue, as this will effectively end support for IE11.

**Comment by electro75** [comment]
I am looking to get started on open source contribution. Shall I take this issue up?

**Comment by eonarheim** [comment]
@electro75 all yours!

**Comment by woutfeys** [comment]
> I am looking to get started on open source contribution. Shall I take this issue up?

Me too! I was also thinking that this priject might be cool to work on!
