### ISSUE TITLE
Draw left face and right face

### ISSUE THREAD

**Issue by Qarasina** [excaliburjs/Excalibur#1490]
```js
    this.addDrawing("right", Resources.FatherRight)
        this.addDrawing("left", Resources.FatherLeft)
```

Error : 
```
      TS2345: Argument of type 'Texture' is not assignable to parameter of type 'Drawable'.
```
But why ?

**Comment by eonarheim** [comment]
Hi @Qarasina, in the current drawing system to add a drawing to an Actor it must be a `Drawable` type. I agree that `Texture` does seem like it should work, it has a slightly different responsibility to reference a loadable bitmap. `Sprite` is a drawable view into a bitmap (Texture). We are making some changes [soon in v0.24](https://github.com/excaliburjs/Excalibur/issues/1161)  to make this a better experience and less confusing.

There is a quick way to convert a `Texture` to a `Sprite` using `Texture.asSprite()` which will create a Sprite that is the same size as the backing Texture.

https://excaliburjs.com/docs/api/v0.23.0/classes/_drawing_sprite_.sprite.html

**Comment by Qarasina** [comment]
Thanks :)
