### ISSUE TITLE
Allow for camera constraints

### ISSUE THREAD

**Issue by DaVince** [excaliburjs/Excalibur#1498]
### Context
Right now, a camera can move anywhere and everywhere. In the context of showing a map, this will mean that when bound to an Actor, the camera moves beyond the limits of the map and shows sudden emptiness.

### Proposal
I propose to add an extra constraints property to the CameraStrategy class, that, when set, will stop the camera once it goes beyond the defined constraints.

Example:
```ts
this.cameraStrategy.constraints = new Vector(mapWidth, mapHeight);
```
CameraStrategy.action() is then expected to follow the constraints and return the appropriate value.

**Comment by eonarheim** [comment]
I think this is a great idea, it may be possible to create a new implementation of the `CameraStrategy` interface to bind the camera viewport to a bounding box area.

**Comment by DaVince** [comment]
Good thinking, that's much cleaner. I'm implementing such a strategy right now and will start a merge request for it.

**Comment by DaVince** [comment]
Example usage:

```ts
let boundingBox = new BoundingBox(leftBorder, topBorder, rightBorder, bottomBorder);
game.currentScene.camera.strategy.limitCameraBounds(boundingBox);
```
