### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by thomergil** [excaliburjs/Excalibur#1504]
On the main docs page [https://excaliburjs.com/docs/api/edge/?no-cache=1] there is a link to "Working with Scenes", currently pointing at [https://excaliburjs.com/docs/api/edge/modules/_index_.html#scene], which should probably be pointing at [https://excaliburjs.com/docs/api/edge/classes/_scene_.scene.html]

**Comment by eonarheim** [comment]
@thomergil Thanks for spotting, seems like typedoc changed a few months back and links started breaking

**Comment by eonarheim** [comment]
Looks like the doc site links are working as expected now, let me know if you see any other oddness 👍
