### ISSUE TITLE
Embedding a page with Excalibur in an iframe from another domain results in an exception

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#1510]
### Steps to Reproduce

On Slides.com, try to embed a page with Excalibur running using the Iframe feature.

For example, https://excaliburjs.com/ludum-46/

### Expected Result

The game should start.

### Actual Result

You get an exception due to Keyboard (I think) attempting to access the parent frame (which is cross-origin) and fails.

![image](https://user-images.githubusercontent.com/563819/80330771-aefc2780-880b-11ea-8e89-f3cee778574e.png)

### Environment

- browsers and versions: Chrome 81
- operating system: Windows 10
- Excalibur versions: 0.24.1 (0.23.x?)

It looks like Office Daydream embeds fine: http://excaliburjs.com/ludum-41/

But The Show Must Go On does not: https://excaliburjs.com/ludum-46/

I was testing using Storybook page: https://excaliburjs.com/examples/iframe.html?id=actions--fade

It looks like this may have been introduced in the time between Ludum 41 and Ludum 46?

### Current Workaround

Don't embed it in an iframe or use previous working Excalibur version.

**Comment by kamranayub** [comment]
Related to https://github.com/excaliburjs/Excalibur/issues/1294

How should we handle cross-origin embeds? 🤔

**Comment by eonarheim** [comment]
@Carghaez We just published version v0.24.2 to address the cross origin

Serving from unpkg works in codepen again
https://unpkg.com/excalibur@0.24.2/dist/excalibur.min.js

https://codepen.io/eonarheim/pen/MWaoGyd
