### ISSUE TITLE
Test fail on fresh clone

### ISSUE THREAD

**Issue by Xstoudi** [excaliburjs/Excalibur#1513]
### Steps to Reproduce
```
git clone https://github.com/excaliburjs/Excalibur.git
npm install
npm run dev
```
### Expected Result
Run without failing

### Actual Result
16 FAILED

### Environment

- browsers and versions: test runner
- operating system: Windows 10
- Excalibur versions: master branch

**Comment by Xstoudi** [comment]
Ok seems, like it is flacky tests : images diff often fail (between 96% and 99.50%) because it attempts 99.5% match.

**Comment by eonarheim** [comment]
@Xstoudi which tests in particular are failing for you? Definitely not ideal if tests are failing on one machine and not another.

**Comment by Xstoudi** [comment]
Ok, on Ubuntu everything seems to work correctly.

**Comment by eonarheim** [comment]
@Xstoudi mine seem to pass on win10 running in chrome headless, what build do you have?

**Comment by eonarheim** [comment]
Run `winver.exe` to output build number

**Comment by Xstoudi** [comment]
Windows 10 - Version 1909. I figured out that `npm install` wasn't downloading Puppeteer's Chromium binary. More exactly, it downloads it but it doesn't unzip it.
