### ISSUE TITLE
Opacity on drawables does not propagate to children

### ISSUE THREAD

**Issue by DaVince** [excaliburjs/Excalibur#1529]
### Steps to Reproduce
- Create an Actor or ScreenElement. Add some children to it.
- Change the opacity of the parent object.

### Expected Result
I expected the opacity of all children objects to be changed accordingly to its parent.

### Actual Result
The children display at full opacity regardless of the parent.

### Environment
- browsers and versions: N/A
- operating system: N/A
- Excalibur versions: 0.24.1

### Current Workaround
Set the opacities of all the children manually.

As far as I can tell, only opacity is affected by this. Changing the parent scale, for example, works fine.

**Comment by kamranayub** [comment]
This may turn out to be a non-issue once we remove child actors soon. There's a lot wrong with them 😬 @eonarheim thoughts?

**Comment by eonarheim** [comment]
We plan to remove child actors soon in favor of the new graphics api for heirarchical drawing. I'm not sure it makes sense to fix this.

**Comment by eonarheim** [comment]
A case could be made to fix it for now until the new api is ready, thoughts?

**Comment by DaVince** [comment]
I'd say only if the time is worth the effort. I'm able to work around it right now by looping through all the children and setting their opacity to the parent's.

If the feature is going away anyway it makes more sense for me to stop using them and eventually switch my HUD class, which makes heavy use of the feature, to use the planned GraphicsGroup and Layer features.

**Comment by eonarheim** [comment]
I believe this was closed in #1730
