### ISSUE TITLE
bug: Automated release tooling does not add GH release assets

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#1533]
The automated release script isn't adding the dist files automatically to tagged releases in GitHub:

![image](https://user-images.githubusercontent.com/563819/80933955-728c7680-8d8b-11ea-8e8d-3eb02944db3c.png)

(I added the JS manually to 0.24.2)

Should prioritize this.

**Comment by DaVince** [comment]
Does this include the release notes? Both are missing for 0.24.2 on both this repo and the dist repo.

**Comment by eonarheim** [comment]
I think it should include both the dist files and release notes

**Comment by eonarheim** [comment]
Partially fixed with 086b970f

We'll need some more robust automation that @jedeen is working on to get the full release notes
