### ISSUE TITLE
Actor without a drawing doesn't set anchor properly

### ISSUE THREAD

**Issue by DaVince** [excaliburjs/Excalibur#1535]
I use some actors without graphics as trigger areas for the game to act on, but they don't get positioned properly.

### Steps to Reproduce
Try the following code:

```ts
const actor = new Actor(0, 0, 32, 32, Color.Red);
actor.anchor.setTo(0, 0);
game.add(actor);
```

### Expected Result
The full actor should be visible, with the very top-left of the actor displaying at position 0,0.

### Actual Result
Only a quarter of the actor is visible. The anchor is ignored and so 0,0 is where the middle of the actor is displayed.

Setting the position again after setting the anchor doesn't change this behavior. Neither does not setting an actor color.

### Environment
- browsers and versions: Google Chrome 81.0.4044.138, Safari 13.1 (14609.1.20.111.8)
- operating system: MacOS, Ubuntu 19.10
- Excalibur versions: 0.23.0, 0.24.1
- This seems to have broken at some point after 0.22.0, which handles it correctly.

### Current Workaround
Add half the actor's size to the position when placing the actor and subtract half its size when reading its position.

**Comment by DaVince** [comment]
Expected result:
![image](https://user-images.githubusercontent.com/105533/81198288-976a2f00-8fc1-11ea-9169-edaee13587c7.png)


Actual result:
![image](https://user-images.githubusercontent.com/105533/81198021-48bc9500-8fc1-11ea-8d22-6cf01dd2b495.png)

**Comment by kamranayub** [comment]
Yeah that's a regression for sure, yikes!

**Comment by catrielmuller** [comment]
@DaVince // @kamranayub  // @eonarheim , need to be tested but now look like it's doing that should be doing. :D

**Comment by DaVince** [comment]
Couldn't get the opportunity to test, but it looks like that's been done already. Thanks for the fix!
