### ISSUE TITLE
Convert Excalibur Particle Tester into a Storybook story

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#1536]
### Context
We currently have a particle system demo in [a separate repository](https://github.com/excaliburjs/particle-tester). Now that we support Storybook, we can import it into the main repo as a Storybook story.

### Proposal
- convert the existing particle system demo into a Storybook story
  - add all of the sliders in the old demo with the Storybook knobs plugin
- mark old particle tester repository as archived and private

**Comment by catrielmuller** [comment]
I will take this.

**Comment by eonarheim** [comment]
@catrielmuller All yours! Let us know if you have any questions or run into any issues!

There are some examples of other stories here
https://github.com/excaliburjs/Excalibur/tree/main/src/stories

To run the stories locally, navigate to the root of the project
* `npm install`
* `npm run visual`

**Comment by catrielmuller** [comment]
@eonarheim I don't know if I followed the all Rules, lmk if miss something. It's my first PR on this project.
