### ISSUE TITLE
Update the Code of Conduct to Contributor Covenant 2.0

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#1538]
### Context
Our Code of Conduct based on version 1.4 of the [Contributor Covenant](https://www.contributor-covenant.org/). The newest version (2.0) includes:
- updated examples of positive community behavior
- updated examples of unacceptable behavior
- clarifications about the scope of the Code of Conduct
- updates to the Enforcement policy

### Proposal
1. review [version 2.0 of the Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct/)
2. discuss the changes from version 1.4 to version 2.0
3. propose any additional changes to our own Code of Conduct
4. update our Code of Conduct

**Comment by eonarheim** [comment]
I approve 👍 let's adopt
