### ISSUE TITLE
Actor documentation points to the wrong page

### ISSUE THREAD

**Issue by thomergil** [excaliburjs/Excalibur#1541]
On page https://excaliburjs.com/docs/api/edge/?no-cache=1 , "Working with Actors" should be pointing at https://excaliburjs.com/docs/api/edge/classes/_actor_.actor.html but it's not.

**Comment by thomergil** [comment]
The same bug is true for "Working with Scenes".

**Comment by eonarheim** [comment]
@kamranayub This seems to have happened relatively recently, do you remember what the cause was?

**Comment by kamranayub** [comment]
I think it's been like this? But regardless, these links need to point to the new user docs, not the API reference anymore as they are out of date.

Refer to https://excaliburjs.com/docs for the latest docs!

**Comment by eonarheim** [comment]
I think the "Working with Actors" link still doesn't work with the latest

**Comment by eonarheim** [comment]
Docs have been re-arranged to have top level topics here https://excaliburjs.com/docs
