### ISSUE TITLE
Passing a Data URI to Texture constructor hangs Loader (and isLoaded() never returns true)

### ISSUE THREAD

**Issue by thomergil** [excaliburjs/Excalibur#1543]
If I'm reading the `Texture` constructor correctly, it should be able to handle Data URI as `path`. However, this hangs the loader forever.

```import * as ex from 'excalibur';

export const Images: { [key: string]: ex.Texture } = {
    failure: new ex.Texture(
        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANwAAADcCAYAAAAbWs+BAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4gIUARQAHY8+4wAAApBJREFUeNrt3cFqAjEUhlEjvv8rXz
    ),
};

const allResources = { ...Images };
export const loader = new ex.Loader();
loader.suppressPlayButton = true;

for (const res in allResources) {
    loader.addResource(allResources[res]);
}

game.start(loader).then(function () { /* */ }
```

Invoking `.load()` on a `Texture` object that was constructed with a Data URI never returns `true` for `.isLoaded()`. 

One thing that catches my attention in `Texture`'s constructor is that it appears that:

```
            this._isLoaded = true;
```

...is called for `path` that is *not* a Data URI, but it is never called for a `path` that *is* a Data URI. See https://github.com/excaliburjs/Excalibur/blob/57e03f4d/src/engine/Resources/Texture.ts#L73

**Comment by eonarheim** [comment]
Good find, that shouldn't happen

**Comment by thomergil** [comment]
I believe the fix might be adding `this._isLoaded = true;` in the part of the constructor that deals with a Data URI path. (Though I don't have enough understanding of the code yet whether that will resolve the hanging Loader; I have to assume that something polls all resources until `isLoaded() == true`, though?)

**Comment by thomergil** [comment]
My suggested fix does not, in fact, resolve the hanging loader problem.

**Comment by eonarheim** [comment]
I wonder if it's a missing promise resolve() that should fire when a data
URI is passed

**Comment by thomergil** [comment]
I think it's there: https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Resources/Texture.ts#L64

**Comment by thomergil** [comment]
Awesome.
