### ISSUE TITLE
Flakey Sound test sometimes fails in CI

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1547]
![image](https://user-images.githubusercontent.com/612071/81888903-ec7ce680-9567-11ea-8b94-67e299530e05.png)

### Steps to Reproduce
Every once in a while this test will fail. I suspect the setTimeout is the source of the flakiness

https://github.com/excaliburjs/Excalibur/blob/ea301f7d009cb46a8910122a5c70aeb6698ed4a0/src/spec/SoundSpec.ts#L263-L281

### Expected Result
The test should always pass

### Actual Result
Sometimes fails

### Environment

- browsers and versions: Chrome Headless
- operating system: linux & windows
- Excalibur versions: master

### Current Workaround
Rebuild the commit in CI

**Comment by eonarheim** [comment]
The flakey test returns :( 

https://travis-ci.com/github/excaliburjs/Excalibur/builds/178988671#L1209

**Comment by PJinx** [comment]
Could you use a try/catch method or something similar to grab the exception?

**Comment by eonarheim** [comment]
This seems to have been fixed mysteriously, will reopen if we spot flakiness
