### ISSUE TITLE
Implement Scene activation context and data passing

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#1548]
### Context

Thinking about usage of scenes as navigation structures, you go between scenes almost like a page router. Typically with navigation APIs, you can pass data (like a URL or route data). In Excalibur, when you call `Engine.goToScene(sceneKey)` it might be nice to pass data to the `Scene.onActivate` hook.

### Proposal

We'd need to figure out a way to indicate to TypeScript how to type this but something like this:

```ts
class Level extends Scene {
  onActivate(context) {
    console.log(context.data); // "overworld"
  }
}
game.add('level', new Level());
game.goToScene('level', 'overworld');
```

The data passed can be arbitrary, no reason to restrict it necessarily. By default, `undefined` is used.

```ts
interface SceneActivationContext<TData = undefined> {
  data: TData;
  previousScene: Scene;
  engine: Engine;
}
```

Maybe some type helpers on `Scene`?

```ts
class Level extends Scene<string> {
  onActivate(context /* type: SceneActivationContext<string> */) {
    console.log(context.data); // "overworld"
  }
}
```

Or can we override with optional generic?

```ts
class Scene {
  // ...
  public onActivate<TData = undefined>(context: SceneActivationContext<TData>) {
    // override me
  }
}

class Level extends Scene {
  onActivate<string>(context) {
    console.log(context.data);
                        ^ string
  }
```

**Comment by mattjennings** [comment]
Are you willing to take PRs on this? This is something I have need for and would be happy to contribute.

To preserve backwards compatibilty with the current API of `onActivate(oldScene, newScene)`, I think it would be fine to have `data` as a 3rd parameter. But I do like having a single `context` parameter more if we're okay having that as a breaking change.

As for typing, what if we had it Scene take a generic?

```ts
class Scene<TData = undefined > {
   onActivate(ctx: SceneActivationContext<TData>): void
}

interface SceneActivationContext<TData = undefined> {
  data: TData;
  previousScene: Scene;
  engine: Engine;
}
```

**Comment by eonarheim** [comment]
@mattjennings Definitely all yours! 

I'd be okay with the breaking change in this case for scene activation, the `context` sets us up for future additions.

I think your generic proposal is reasonable 👍 the default type parameter will help keep existing `new ex.Scene()` code backwards compatible without requiring users to supply a generic. Maybe we call it `TActivationData` for greater specificity? 

@kamranayub @jedeen Any objections to the proposal?

**Comment by mattjennings** [comment]
Awesome! I'll get to it.

Would we want to change the API for `onDeactivate` as well to match? I'm not sure if the `oldScene` and `newScene` params were around when this issue was made, but in the suggested `SceneActivationContext` type it only has `previousScene`. 

I imagine we want references to previous & next scenes for both `onActivate` and `onDeactivate`. How would we feel about something like this?

```ts
export interface SceneActivationContext<TData = undefined> {
  data: TData;
  oldScene: Scene; // or previousScene?
  newScene: Scene; // or nextScene?
  engine: Engine;
}

export interface CanActivate<TData = undefined> {
  /**
   * Overridable implementation
   */
  onActivate(context: SceneActivationContext<TData>): void;

  /**
   * Event signatures
   */
  on(eventName: Events.activate, handler: (event: Events.ActivateEvent) => void): void;
  once(eventName: Events.activate, handler: (event: Events.ActivateEvent) => void): void;
  off(eventName: Events.activate, handler?: (event: Events.ActivateEvent) => void): void;
}

export interface CanDeactivate {
  /**
   * Overridable implementation
   */
  onDeactivate(context: SceneActivationContext<never>): void;

  /**
   * Event signature
   */
  on(eventName: Events.deactivate, handler: (event: Events.DeactivateEvent) => void): void;
  once(eventName: Events.deactivate, handler: (event: Events.DeactivateEvent) => void): void;
  off(eventName: Events.deactivate, handler?: (event: Events.DeactivateEvent) => void): void;
}
```

**Comment by eonarheim** [comment]
@mattjennings I like all of these suggestions :+1:

I like `previousScene` and `nextScene`, they use clearer language. It communicates directionality better than new/old.

**Comment by mattjennings** [comment]
It seems using a generic as part of the Scene class isn't too helpful, and actually causes type issues in certain scenarios.

1. I thought that the type for `onActivate` could be inferred by the generic - but unfortunately that's not how Typescript works when extending classes:

```ts
class MyScene extends ex.Scene<{ foo: string >} {

   // type of ctx still needs to be explicitly defined here
   onActivate(ctx: ex.SceneActivationContext<{ foo: string }>) {
   }
}
```

2. `Scene<TData = undefined>` breaks any type that expects a regular `Scene` but gets one that has a defined generic.

```ts
class MyScene extends ex.Scene<{ foo: string >} {}

function doSomething(scene: ex.Scene) {}

doSomething(new MyScene()) // causes ts error, as it expects type Scene<undefined>, not Scene<{ foo: string }>

// doSomething would have to be typed like this to fix it
function doSomething(scene: ex.Scene<any>) {}
function doSomething<T>(scene: ex.Scene<T>) {}
```

so I propose either `Scene<TData = any>`, or scrapping the generic from `Scene` and just have it be provided in the `onActivate` method, as originally suggested.

**Comment by eonarheim** [comment]
Hmm indeed, in that case I think providing it in the `onActivate` might be the best path forward 👍

**Comment by mattjennings** [comment]
@eonarheim oops, it seems the types are a bit off.

<img width="756" alt="CleanShot 2022-07-01 at 10 55 56@2x" src="https://user-images.githubusercontent.com/8703090/176929150-aed42bd1-b603-4f2e-bcb1-2227d44ec0aa.png">

This is because the class methods take generics, i.e `onActivate<TData = undefined>`. Which means the inheriting class also has to match the same definition of generics:

```ts
class MyScene extends ex.Scene {
    public onActivate<string>(ctx: ex.SceneActivationContext<string>) {
    }
}
```
... which is, of course, not ideal. 

So a solution would be to go back to having a generic of `TActivationData` on the Scene, but have it default to `unknown` . That way it can be inferred by the given generic for `ctx: ex.SceneActivationContext` in `onActivate`, and also shouldn't break any types that just require `ex.Scene` like I ran into before.

before: 

```ts
export class Scene
  extends Class
  implements CanInitialize, CanActivate, CanDeactivate, CanUpdate, CanDraw {

  public onActivate<TData = undefined>(_context: SceneActivationContext<TData>): void {}
}
```

after:

```ts
export class Scene<TActivationData = unknown>
  extends Class
  implements CanInitialize, CanActivate<TActivationData>, CanDeactivate, CanUpdate, CanDraw {

  public onActivate(_context: SceneActivationContext<TActivationData>): void {}
}
```

I'll make a PR shortly with the changes and you can review if it makes sense. Sorry for the back and forth on this!

**Comment by eonarheim** [comment]
@mattjennings sounds good! Thanks for pointing this out 👍
