### ISSUE TITLE
Velocity is always zero when using easeTo

### ISSUE THREAD

**Issue by apaatsio** [excaliburjs/Excalibur#1638]
When using `easeTo`, the velocity of the body is not updated but it stays 0. 

This behavior differs from `moveTo`. I would expect them to behave in a similar way. Moreover, the actor is clearly moving so it should have a velocity, right?

### Steps to Reproduce

See https://codepen.io/apaatsio/pen/bGpvvwr

Basically just call `this.actions.easeTo()` on any actor and observe `this.body.vel`.

### Expected Result

`this.body.vel` reflects the speed of the body.

### Actual Result

`this.body.vel` is always (0, 0).

### Environment

- browsers and versions: Chrome 85
- operating system: Linux
- Excalibur versions: 0.24.5

**Comment by eonarheim** [comment]
@apaatsio Good find, that is indeed inconsistent. Velocity is probably more ideal in general than altering position directly in the easing function...
