### ISSUE TITLE
Add full ASCII printable set of keys and switch to KeyboardEvent.code

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1654]
### Context

Currently Excalibur does not have every printable ASCII character in it's constants and is using the deprecated `KeyboardEvent.keyCode`. We are no longer supporting IE11 so no need to support `keyCode`

### Proposal

* Add a constant for every ~~printable ASCII~~ physical key in Excalibur.
  * Current constants using deprecated keyCode property
        https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Input/Keyboard.ts#L8-L59

* Update logic to use `KeyboardEvent.code` https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Input/Keyboard.ts#L132

See ascii table https://theasciicode.com.ar/ascii-control-characters/horizontal-tab-ascii-code-9.html

**Comment by rledford** [comment]
@eonarheim some of the printable ASCII characters are only in `KeyboardEvent.code` on the `keypressed` event, but not the `keydown` and `keyup` event (e.g. `@` will emit code _50_ for `keydown`, _64_ for `keypressed`, and _50_ again for `keyup`). The engine is only listening for _keydown_ and _keyup_ and just wanted to make sure this is ok. I've forked the repo and added constants for all printable ASCII characters and updated to use `KeyboardEvent.code`. I'll make a PR to discuss some other things like the existing letter constants and what we can do for the lowercase ones - trying to follow the enum naming convention to start with an uppercase letter but not sure what to do with the lowercase letters.

**Comment by eonarheim** [comment]
Hi @rledford thanks! Definitely, working within the current engine keyup/keydown handlers is okay. 

Let's not be concerned with casing at the moment, the `KeyboardEvent.code` does not encode that information. Just enough enum to capture `KeyboardEvent.code` from a physical key on a keyboard. Use the common keys shared between firefox and chrome, we can ignore the ones that are not the same. https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values

My original ask for all printable is a misnomer apologies, we really want physical key space. 

https://codesandbox.io/s/key-code-y6994?file=/src/index.ts

We would be interested to hear your thoughts on how we might tackle key combinations and surfacing values from `KeyboardEvent.key` in the future.
