### ISSUE TITLE
Change `isDebug` to `showDebug(toggle: boolean)`

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1655]
### Context

Currently it is slightly odd to turn on debug drawing mode `isDebug = true`. We should switch this to a better named method. 

### Proposal

Implement `showDebug(toggle: boolean)` which can toggle debug drawing mode `true` or `false`

Add tests to show it works as expected

**Comment by MrBartusek** [comment]
@eonarheim Can I work on that?

**Comment by eonarheim** [comment]
@MrBartusek all yours
