### ISSUE TITLE
Remove UIActor stub

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1656]
### Context

UIActor has been renamed, remove any remaining UIActor code

### Proposal

* Remove UIActor https://github.com/excaliburjs/Excalibur/blob/a462a5da218a493b0feccc2522f14da0bb21c558/src/engine/ScreenElement.ts#L58

* Ensure tests still pass

**Comment by catrielmuller** [comment]
@eonarheim -> https://github.com/excaliburjs/Excalibur/pull/1680 lmk if it's ok.
