### ISSUE TITLE
Remove use of WebAudio noteOn()

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1657]
### Context

Use `start()`, noteOn has been deprecated for some time

### Proposal

Remove noteOn code https://github.com/excaliburjs/Excalibur/blob/a462a5da218a493b0feccc2522f14da0bb21c558/src/engine/Util/WebAudio.ts#L49-L54

Ensure tests still pass

**Comment by kala2** [comment]
Hello, would you mind if i take it? Could you please assign it to me?

**Comment by eonarheim** [comment]
@kala2 All yours!
