### ISSUE TITLE
Nearest-neighbour viewport scaling doesn't work in Firefox

### ISSUE THREAD

**Issue by djcsdy** [excaliburjs/Excalibur#1676]
### Steps to Reproduce

```typescript
const width = 320;
const height = 240;

const engine = new Engine({
    viewport: {width * 4, height * 4},
    resolution: {width, height},
    displayMode: DisplayMode.Fixed,
    antialiasing: false,
    suppressHiDPIScaling: true
});
```

Construct an engine as above, and then draw some sprites. Bitmap graphics are drawn at 320×240, and then scaled up to fill a 1280×960 viewport.

### Expected Result

On most browsers, graphics are upscaled from 320×240 to 1280×960 using a nearest-neighbour filter. This is the expected behaviour because `antialiasing: false`.

![image](https://user-images.githubusercontent.com/310800/95004545-5adc4700-05e4-11eb-9cdb-8dc95a826ee3.png)

### Actual Result

On Firefox, graphics are upscaled from 320×240 to 1280×960 using a bilinear filter.

![image](https://user-images.githubusercontent.com/310800/95004540-4435f000-05e4-11eb-94bc-d5cb4b6d6034.png)

This happens because Firefox does not support `image-rendering: pixelated`.

However, Firefox does support `image-rendering: crisp-edges`. Per-spec `crisp-edges` is not exactly equivalent to `pixelated` because a browser is allowed to use an upscaling algorithm designed to preserve crisp edges such as 2xSaI or hqx, but it is still a better fallback than `auto` when `pixelated` isn't supported. In practice Firefox implements `crisp-edges` using a nearest-neighbour upscaler and every other browser supports `pixelated` correctly. Given its implementation, it's not clear why Firefox doesn't treat `pixelated` as equivalent to `crisp-edges`.

### Suggested solution

Test if the browser supports `image-rendering: "pixelated"`. If it doesn't, set `image-rendering: "crisp-edges"` instead.

### Environment

- browsers and versions: Firefox 80
- operating system: Windows 10
- Excalibur versions: 0.24.5

### Current Workaround

```typescript
    if (engine.canvas.style.imageRendering === "") {
        engine.canvas.style.imageRendering = "crisp-edges";
    }
```

**Comment by eonarheim** [comment]
@djcsdy Thanks for the issue, your proposed solution seems like the fix.
