### ISSUE TITLE
Z-Index is broken since v0.24.5

### ISSUE THREAD

**Issue by djcsdy** [excaliburjs/Excalibur#1678]
### Steps to Reproduce

1. Create some actors.
2. Set a different z-index on each actor.
3. Position the actors to overlap.

### Expected Result

Actors with a higher z-index should be displayed in front of actors with a lower z-index.

### Actual Result

Actors are displayed in no particular order.

### Environment

- browsers and versions: Firefox 80
- operating system: Windows 10
- Excalibur versions: 0.24.5

The problem is commit 855ce516.

In this commit calls to `SortedList.getComparable` have been changed from `getComparable.call(element)` to `getComparable(element)`. In other words, `element` was previously passed as `this`, but now it is passed as an argument. However the actual implementation passed as `getComparable` still expects `element` to be passed as `this`.

**Comment by eonarheim** [comment]
@djcsdy Good find, definitely an issue
