### ISSUE TITLE
Actors get added multiple times as ActorsUnderPointer

### ISSUE THREAD

**Issue by Jvkassel** [excaliburjs/Excalibur#1787]
I am creating a UI where button actors (children) can be added to a window actor (parent).
I've added an eventlistener to the buttons to check if they have been pushed. By accident I stumbled upon the function [`getActorsUnderPointer`](https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Input/Pointer.ts#L183) and was curious what it returned. So I viewed the results. Instead of just showing the button and the window actors, it showed me a fast increasing `array`.
After digging around it looked like the [`isActorAliveUnderPointer`](https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Input/Pointer.ts#L226) returns `false` for the buttons since those don't have a scene (cause it's directly added to the window).

### Steps to Reproduce

I've recreated a simple version of the problem here:
https://codesandbox.io/s/crimson-water-rblth

### Expected Result

It should just return an `array` containing the two actors.

### Actual Result

It returns an `array` that increases in size with every update.

### Environment

- browsers and versions: Chrome (88.0.4324.182) 
- operating system: Windows 
- Excalibur versions: 0.24.5 
- (anything else that may be relevant) 

### Current Workaround

None

**Comment by eonarheim** [comment]
@Jvkassel The pointer API was recently refactored, the `getActorsUnderPointer` no longer exists as a method
