### ISSUE TITLE
Rename TopCamera

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#184]
A TopCamera doesn't necessarily have to be used in a top-down game environment. It should be more accurately named to describe its behavior of being locked (or at least focusing) on a particular actor.

**Comment by kamranayub** [comment]
If this is done, it should be merged in. You can merge in this commit specifically, if you don't want to merge in the branch.

**Comment by eonarheim** [comment]
@jedeen Looks like this is done in your old branch from almost a year ago... probably don't want to merge this now. Perhaps a new commit with the changes copied?

**Comment by eonarheim** [comment]
Completed with #435
