### ISSUE TITLE
Changing color of a circle (Graphics object) with padding moves it

### ISSUE THREAD

**Issue by LokiMidgard** [excaliburjs/Excalibur#1897]
### Steps to Reproduce

1. Add a circle to an actor
2. apply padding
3. periodically update the color

<Details>
<Summary >
<b>A Minimal Sample</b>
</Summary >

```ts
import { Engine, Loader, DisplayMode, Scene, Actor, Color, vec } from 'excalibur';
import { Resources } from './resources';
import { delay } from 'excalibur/build/dist/Util';
import { Circle } from 'excalibur/build/dist/Graphics';

/**
 * Managed game class
 */
class Game extends Engine {

  constructor() {
    super({
      displayMode: DisplayMode.Fill,
      enableCanvasTransparency: true,

    });
  }

  public start() {
    const scene = new Scene();
    const actor = new Actor({ pos: vec(150, 150) });
    const circle = new Circle({
      radius: 30,
      strokeColor: Color.DarkGray,
      lineWidth: 4,
      padding: 2,
      smoothing: true,

    });
    actor.graphics.add(circle);
    scene.add(actor);
    this.add('levelOne', scene);


    // Automatically load all default resources
    const loader = new Loader(Object.values(Resources));
    this.simulate(circle);
    return super.start(loader);
  }

  private async simulate(circle: Circle) {
    while (true) {
      await delay(1000);
      circle.color = Color.Red;
      await delay(1000);
      circle.color = Color.Violet;
    }
  }
}

const game = new Game();
game.start().then(() => {
  game.goToScene('levelOne');
});

```

</Details>

### Expected Result

Just the color is changing

### Actual Result

![excalibur-problem2](https://user-images.githubusercontent.com/389101/119254802-be89a380-bbb8-11eb-827f-9fb2a3474355.gif)

the position changes

### Environment

- browsers and versions: 
  Brave: `Version 1.24.86 Chromium: 90.0.4430.212 (Offizieller Build) (64-Bit)`
  Firefox: `88.0.1 (64-Bit)`
- operating system: Windows 10 Home `20H2` `19042.985`
- Excalibur versions: `0.25.0-alpha.84`
- I tested versions back to `0.25.0-alpha.80`

### Current Workaround

Not using padding, however that looks ugly since the circle is no longer round:
![image](https://user-images.githubusercontent.com/389101/119254981-7fa81d80-bbb9-11eb-8e13-7747735e590c.png)

You can also reset the width and height explicitly after updating the color. this "only" lets the circle wobble...

![excalibur-problem3](https://user-images.githubusercontent.com/389101/119255490-6bb1eb00-bbbc-11eb-9165-3753b5b60150.gif)

**Comment by eonarheim** [comment]
Thanks for the issue, this is a good find. I bet something is off internally in abstract Graphic when recalculating width, height, and centering when padding is used.

**Comment by LokiMidgard** [comment]
@eonarheim I think the commit changed the behavior of padding. I think before padding increased the Size of the actor. no it no longer does, however it changes the x and y coordinates.

![image](https://user-images.githubusercontent.com/389101/119649687-33601600-be23-11eb-97ec-8a7775875111.png)


I set following values on circle:
```ts
      lineWidth: 10,
      padding: 20,
```

<Details>
<Summary><b>Complete sample</b></Summery>

```ts
import { Engine, Loader, DisplayMode, Scene, Actor, Color, vec } from 'excalibur';
import { Resources } from './resources';
import { delay } from 'excalibur/build/dist/Util';
import { Circle } from 'excalibur/build/dist/Graphics';

/**
 * Managed game class
 */
class Game extends Engine {

  constructor() {
    super({
      displayMode: DisplayMode.Fill,
      enableCanvasTransparency: true,

    });
  }

  public start() {
    const scene = new Scene();
    const actor = new Actor({ pos: vec(150, 150) });
    const circle = new Circle({
      radius: 30,
      strokeColor: Color.DarkGray,
      lineWidth: 10,
      padding: 20,
      smoothing: true,
    });
    circle.showDebug=true
    actor.graphics.add(circle);
    scene.add(actor);
    this.add('levelOne', scene);


    // Automatically load all default resources
    const loader = new Loader(Object.values(Resources));
    this.simulate(circle);
    return super.start(loader);
  }

  private async simulate(circle: Circle) {
    while (true) {
      await delay(1000);
      circle.color = Color.Red;
      await delay(1000);
      circle.color = Color.Violet;
    }
  }
}

const game = new Game();
game.start().then(() => {
  game.goToScene('levelOne');
});


```

</Details>

**Comment by eonarheim** [comment]
@LokiMidgard indeed, I'll reopen
