### ISSUE TITLE
Offline storage support for loaded resources

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#199]
### Context 
This will decrease loading times on games that have already loaded resources once in the past.

### Proposal
Implement offline storage support.

**Comment by jedeen** [comment]
see also #5

**Comment by eonarheim** [comment]
WebWorkers!!!!!

**Comment by eonarheim** [comment]
We are reducing the scope of features we are focusing on to core engine and feature improvements. We are still open to PRs and/or plugins for non-core features.

Spoke with @jedeen offline
