### ISSUE TITLE
Support an Excalibur "package" file where we could compress multiple resources

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#200]
This would be advantageous in the loading scenario, allowing Excalibur to make only one xhr request and unpack the compressed binary data on the client. 

It should speed up the loading of files and provide some layer of obfuscation for peoples game assets.

**Comment by kamranayub** [comment]
Doing as part of excaliburjs/excalibur-tiled repo

**Comment by eonarheim** [comment]
WIP in excalibur-pack repo
