### ISSUE TITLE
Add `.center` getter to Screen

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#2045]
### Context

A common operation that could be made quicker is a helper getter to get the center of the screen. Currently folks need to write
```typescript
const center = vec(game.halfDrawWidth, game.halfDrawHeight);
```

### Proposal

1. Add a new getter `center` to Screen that will return a `Vector` `vec(this.halfDrawWidth, this.halfDrawHeight)`;
2. New unit tests are required

**Comment by SirPedr** [comment]
Would be happy to work on this ;)

**Comment by eonarheim** [comment]
@SirPedr all yours!
