### ISSUE TITLE
'Features' docs page is missing

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#2109]
### Expected Result

The https://excaliburjs.com/docs/features link in the main Readme should resolve

### Actual Result

The https://excaliburjs.com/docs/features link 404s

### Proposed Solution

Replace or remove the link to this page in the documentation.

### Current Workaround
None

**Comment by SulthanNK** [comment]
I would like to take this issue If no one started working already.

**Comment by eonarheim** [comment]
@SulthanNK all yours! Please replace the features link with https://excaliburjs.com/docs 👍

**Comment by SulthanNK** [comment]
Hi @eonarheim, I replaced the broken link with the new one and Raised the PR.
