### ISSUE TITLE
Center of child not updated on parent move. Breaks camera strategies.

### ISSUE THREAD

**Issue by luttje** [excaliburjs/Excalibur#2192]
Because [camera strategies use actor.center](https://github.com/excaliburjs/Excalibur/blob/0082c6f7d2cf411d9e3bf9888051cde0538867bb/src/engine/Camera.ts#L105), and because the value of that doesn't change for parented actors, camera strategies break.

### Steps to Reproduce
Using the parcel v2 typescript template:
1. add a child to an actor using actor.addChild(childActor)
2. Set the camera strategy to follow the child actor (elastic, radius, lock or lock axis)
3. Test by moving the parent

The camera doesn't follow the actor.

Here's some code I used to test this: https://pastebin.com/mwaCJ2mp

### Expected Result
The camera strategy should follow the parent of a child to which it is locked.

### Actual Result
The camera strategy remains at the initial position

### Possible cause
When looking at the strategy code I noticed all these broken strategies use 'actor.center' to decide the position. If you `console.log(this.center);` in the child update, you will notice it does not change. I suspect that is why the camera strategy fails to follow the actor.

Lines where actor.center is used in the strategies:
* LockCameraToActorStrategy: https://github.com/excaliburjs/Excalibur/blob/0082c6f7d2cf411d9e3bf9888051cde0538867bb/src/engine/Camera.ts#L105
* LockCameraToActorAxisStrategy: https://github.com/excaliburjs/Excalibur/blob/0082c6f7d2cf411d9e3bf9888051cde0538867bb/src/engine/Camera.ts#L116
* ElasticToActorStrategy: https://github.com/excaliburjs/Excalibur/blob/0082c6f7d2cf411d9e3bf9888051cde0538867bb/src/engine/Camera.ts#L141
* RadiusAroundActorStrategy: https://github.com/excaliburjs/Excalibur/blob/0082c6f7d2cf411d9e3bf9888051cde0538867bb/src/engine/Camera.ts#L172

### Current workaround
Simply set the strategy to follow the parent.

My reasoning for following the child with the camera is that I may want the camera to be directed in front of, or away from the player character. In my case the child is a 'CameraDirector'-actor and the parent is a 'PlayerCharacter'-actor.

Hope this helps!

**Comment by eonarheim** [comment]
@luttje Thanks for the well written issue! 

I was able to spot the problem in the source theoretically have a fix queued up :+1:
