### ISSUE TITLE
Bug: engine.screenshot does not work in webgl context.

### ISSUE THREAD

**Issue by vbalien** [excaliburjs/Excalibur#2203]
### Steps to Reproduce

To take a screenshot, I did the following:
```js
this.engine.screenshot()
```

### Expected Result

A screenshot should be returned.

### Actual Result

Returns an blank image.

### Environment

- browsers and versions: Chrome (97.0.4692.71), Firefox (96.0.2)
- operating system: Linux 5.16
- Excalibur versions: 0.25.2
- (anything else that may be relevant) 

### Current Workaround

Use `useCanvasGraphicsContext`.

**Comment by eonarheim** [comment]
@vbalien Thanks for the issue, definitely a bug 👍
