### ISSUE TITLE
Add Enter key in enum Keys

### ISSUE THREAD

**Issue by yongsooim** [excaliburjs/Excalibur#2263]
### Context
I want to test wasPressed(key: Keys) for the enter key, but there is no enum value "Enter" in enum Keys.
Without this, I have to use event method but I want the consistency with other keys.

### Proposal
Add Enter key in enum Keys

**Comment by yongsooim** [comment]
Added PR(#2264) for this issue

**Comment by eonarheim** [comment]
Hi @yongsooim,

It's definitely desirable to know when the "enter" key is/was pressed. 

I'll add this to our priorities for the next release.

Did you find a workaround by chance?

**Comment by yongsooim** [comment]
> Hi @yongsooim,
> 
> It's definitely desirable to know when the "enter" key is/was pressed.
> 
> I'll add this to our priorities for the next release.
> 
> Did you find a workaround by chance?


Thank you! I used event method like this for the workaround :
```typescript
let enterWasPressed = false

anActorInTheCurrentScene.onInitialize = (game) => {
  game.input.keyboard.on("press", (evt) => {
    if (evt.value == "Enter") {
      enterWasPressed = true
    }
  }
}

anActorInTheCurrentScene.update(){
  if(enterWasPressed){
      //enter pressed tesetd
  }
}

anActorInTheCurrentScene.onPostUpdate(){
  enterWasPressed = false
}

```
