### ISSUE TITLE
Try every template,no one can use

### ISSUE THREAD

**Issue by YunlongYang** [excaliburjs/Excalibur#2319]
~~~~~~~~~~

**Comment by eonarheim** [comment]
Hi @YunlongYang thanks for the issue! Can you provide some more detail about what you problems you faced?

**Comment by YunlongYang** [comment]
@eonarheim I am so sad, you may clean all node_modules and cache, then start any template lke rollup,webpack, then you will see

**Comment by eonarheim** [comment]
Hi @YunlongYang I'm not able to reproduce a any issues, can you post any errors or issues you see specifically?

I've performed a fresh clone of the webpack template.

`git clone https://github.com/excaliburjs/template-ts-webpack.git`

With Node version 16.13.0 & Npm version 8.10.0

`npm install`

`npm run start`

<img width="521" alt="image" src="https://user-images.githubusercontent.com/612071/169651501-08865424-2a07-4fb5-bce9-734cda403ccc.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/612071/169651508-61e8a05d-0c6b-4757-b46c-995ff06f0d05.png">


I'm also not able to reproduce any issues on the rollup template

**Comment by YunlongYang** [comment]
My Version is
C:\Users\yunlong>node --version
v16.15.0

C:\Users\yunlong>npm --version
8.10.0

**Comment by YunlongYang** [comment]
@eonarheim It stay here,no move
C:\Users\yunlong\Desktop\WorkSpace\template-ts-webpack>npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
[..................] | idealTree:inflate:node_modules/@types/eslint-scope: sill inflate node_modules/@types/eslint-scop

**Comment by YunlongYang** [comment]
@eonarheim idealTree:template-ts-webpack: sill idealTree buildDeps

**Comment by eonarheim** [comment]
I've pushed an updated `package-lock.json` do you still have the issue now?

I updated to the same versions you have of node & npm and I still cannot reproduce unfortunately.

Otherwise, I've had similar issues with npm where installs can get stuck because of locked files. This sounds bad but sometimes restarting the computer will resolve npm issues caused by file locking.

Some common causes for me
* Anti-virus
* Files open by another process
* Windows explorer open in the `node_modules` directory

**Comment by YunlongYang** [comment]
@edualb still on another lib, you know my feelings

C:\Users\yunlong\Desktop\WorkSpace\test\template-ts-webpack>npm install
[#################.] \ reify:webpack: timing reifyNode:node_modules/resolve Completed in 464ms

**Comment by YunlongYang** [comment]
C:\Users\yunlong\Desktop\WorkSpace\test\template-ts-webpack>npm install
[##################] | reify:webpack: timing reifyNode:node_modules/webpack-dev-server/node_modules/ajv Completed in 10

**Comment by YunlongYang** [comment]
you can create new branch within node_modules, then i can use

**Comment by eonarheim** [comment]
Let me know how restarting your computer goes.
