### ISSUE TITLE
Add the ability to clip particles

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#233]
### Context
Let's say I need to generate particles within a certain frame of the game (stage). I have a rectangular bounds; It would be nice to stop particles from drawing past those bounds.

### Proposal
Add the ability to define a clipping mask for particles, to prevent them from being drawn outside the mask.

**Comment by eonarheim** [comment]
We should be able to define a clipping mask for particles (and actors in general)

**Comment by eonarheim** [comment]
Closing for now
