### ISSUE TITLE
Provide playback position from sound instance

### ISSUE THREAD

**Issue by EzraMoore65** [excaliburjs/Excalibur#2335]
Was working on a rhythm game and hit a roadblock when I realized you cannot currently get the position of a sound instance. Managed to find another npm package that I can use, but would love to see this added to the engine.

**Comment by eonarheim** [comment]
@EzraMoore65 this would be a great idea! I fully endorse such a feature!

**Comment by eonarheim** [comment]
I'll have some time to look at it this weekend, I'll give it a shot

**Comment by eonarheim** [comment]
@EzraMoore65 the latest alpha should include this feature, it'd be awesome to get your feedback

[0.27.0-alpha.474](https://www.npmjs.com/package/excalibur/v/0.27.0-alpha.474)

**Comment by EzraMoore65** [comment]
@eonarheim Did exactly what I wanted. Thank you for the quick turn around!
