### ISSUE TITLE
Add easing functions for particle movement

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#234]
### Context
It would be useful to simulate other types of movement, maybe more erratic, maybe more random speeds, etc. Think dust motes.

### Proposal

```
emitter.easing = 'linear';
emitter.easing = 'ease-out';
emitter.easing = 'cubic-bezier(x)';
emitter.easing = (x) => {};
```

This might be two enhancements; one for easing, one for affecting positions over time.

Resources:
- http://cubic-bezier.com/
- http://easings.net/

**Comment by eonarheim** [comment]
We are reducing the scope of features we are focusing on to core engine and feature improvements. We are still open to PRs and/or plugins for non-core features.

Spoke with @jedeen offline
