### ISSUE TITLE
Docs: default CollisionType on Actor is incorrect

### ISSUE THREAD

**Issue by ivanjermakov** [excaliburjs/Excalibur#2341]
### Steps to Reproduce

1. Initialize a new Actor `const actor = new Actor()`
2. Check collision type `actor.body.collisionType`

### Expected Result

Collision type is `CollisionType.PreventCollision` as per [Docs](https://excaliburjs.com/docs/collisiontypes)

### Actual Result

Collision type is `CollisionType.Passive`

### Environment

    "excalibur": "^0.26.0"

### Current Workaround

Initialize Actor with explicit collision type

    const actor = new Actor({
      collisionType: CollisionType.PreventCollision,
    })

**Comment by eonarheim** [comment]
Hi @ivanjermakov, thanks for the issue!

I'll look into this, and figure out what the default actually should be.

One advantage of `ex.CollisionType.PreventCollision` as the default is you aren't paying for any collision logic by default. There may have been a reason it was switched to `ex.CollisionType.Passive` so we'll want to understand why.

**Comment by eonarheim** [comment]
Thanks for pointing out the issue with `ex.Physics.enabled = false`!

I think it's unexpected that `pointerdown` events no longer work in that situation 😱

**Comment by eonarheim** [comment]
I've updated the docs to match reality https://github.com/excaliburjs/excaliburjs.github.io/commit/5c579514482bc40d27f3ed8ef1f011bec264ad90

I'll have time this weekend to dig into what the default `CollisionType` should be going forward, and to fix that bug you pointed out.

**Comment by eonarheim** [comment]
I'm closing this for now, we've update the docs to match reality and theoretically fixed the pointerdown issue when physics is disabled 👍 

@ivanjermakov Thanks again for the issue!
