### ISSUE TITLE
Problems with EventDispatcher

### ISSUE THREAD

**Issue by ilnicki** [excaliburjs/Excalibur#2347]
Hi team, started building a simple game and just encountered some problems with EventHandler. For now I've found at least 3 problems:

## EventHandler.off has a bug with removing nonexistent handlers
https://github.com/excaliburjs/Excalibur/blob/e446f5e237e1aa4d7b338642d75b8c427fa9b822/src/engine/EventDispatcher.ts#L84
indexOf returns -1 if none found, splice accespts -1
### Steps to Reproduce

const dispatcher = new EventDispatcher();
dispatcher.on('foo', () => console.log('foo1'));
dispatcher.on('foo', () => console.log('foo2'));
dispatcher.on('foo', () => console.log('foo3'));
dispatcher.off('foo', () => 'pain');
dispatcher.emit('foo', null);

### Expected Result
foo1
foo2
foo3
### Actual Result
foo1
foo2

## EventHandler.once is not working as intended
https://github.com/excaliburjs/Excalibur/blob/e446f5e237e1aa4d7b338642d75b8c427fa9b822/src/engine/EventDispatcher.ts#L101
The bug is actually based on off's one. metaHandler is added to array, handler is tried to remove.
### Steps to Reproduce

const dispatcher = new EventDispatcher();
dispatcher.once('foo', () => console.log('foo1'));
dispatcher.on('foo', () => console.log('foo2'));
dispatcher.on('foo', () => console.log('foo3'));
try {
    dispatcher.emit('foo', null);
} catch {}
try {
    dispatcher.emit('foo', null);
} catch {}

### Expected Result
foo1
foo2
foo3
foo2
foo3
### Actual Result
foo1
foo2
foo1

## EventHandler.emit fails if number of handlers is changed during iteration
https://github.com/excaliburjs/Excalibur/blob/e446f5e237e1aa4d7b338642d75b8c427fa9b822/src/engine/EventDispatcher.ts#L36
### Steps to Reproduce

const dispatcher = new EventDispatcher();
dispatcher.once('foo', () => console.log('foo1'));
dispatcher.on('foo', () => console.log('foo2'));
dispatcher.on('foo', () => console.log('foo3'));
dispatcher.emit('foo', null);

### Expected Result
foo1
foo2
foo3
### Actual Result
Uncaught TypeError: this._handlers[eventName][i] is not a function at EventDispatcher.emit (excalibur.js:5370:1)

**Comment by eonarheim** [comment]
Hi @ilnicki thanks for the issue! I appreciate the thorough reproductions.

These are definitely bugs we'll want to address soon. I'll have some time this weekend to look into them 👍

**Comment by eonarheim** [comment]
@ilnicki Thanks again! The latest alpha build should have the fixes included. `excalibur@0.27.0-alpha.480`

Let me know if you run into any more issues!
