### ISSUE TITLE
Chromium's Image#decode has limited calls

### ISSUE THREAD

**Issue by HxShard** [excaliburjs/Excalibur#2359]
It's a Chromium specific issue. In Firefox & Safari works as expected.

[codesandbox](https://codesandbox.io/s/happy-gagarin-j1vjr) from [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1055828#c7) issue on chromium.org
Another issue is [here](https://bugs.chromium.org/p/chromium/issues/detail?id=606319).

Possible solutions:
1. Add option to load images through DOM
2. Set up a limit for Image#decode promises (only 256 images could be decoded simultaneously)

I just check second solution by myself, and it worked like a charm.

Error:
`excalibur.js:2996 [Error] :  [Tiled] Error loading tileset images
tiled-map-resource.ts:392 Error loading ImageSource from path '/assets/clothes/dress.png' with error [The source image cannot be decoded.]`

Implemented in ImageSource: https://github.com/excaliburjs/Excalibur/blob/b285ede60652ff8273f78a37a1de2bc6a77db485/src/engine/Graphics/ImageSource.ts#L92

**Comment by eonarheim** [comment]
@HxShard thanks for the issue, wow this is a great find!

I don't think we've tried to load that many images at once, glad you found this. I like option 2 the most, it would be the most transparent for users loading images.

**Comment by eonarheim** [comment]
I bet we could implement something similar to a semaphore in front of the `image.decode()` in `ImageSource` and limit to 256 images. This SO post looks like promising start https://stackoverflow.com/a/68446264, we might need to tweak that implementation a bit to be a standalone semaphore and not require a function be passed.

```typescript
// ImageSource.ts
export class ImageSource {
  private _decodeSemaphore = new Semaphore(256);

  ...

  async load(): Promise<HTMLImageElement>{

    ...

    await this._decodeSemaphore.enter();
    await image.decode();

    ...

  }

  ...

}

```
