### ISSUE TITLE
Implement Arbitrary Polygon Collision Detection

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#24]
The engine only implements naive collision detection on rectangles without rotation. It should provide a more robust system allowing arbitrary polygons to collide.

**Comment by kamranayub** [comment]
@eonarheim is this done as part of rigid body physics and PolygonArea?

**Comment by eonarheim** [comment]
Yup

**Comment by kamranayub** [comment]
Can make a separate issue for concave. Convex polygons are supported since 0.8
