### ISSUE TITLE
Actor clone method throws error

### ISSUE THREAD

**Issue by robly18** [excaliburjs/Excalibur#2407]
### Steps to Reproduce

Clone an actor. See minimal working example, cannibalized from the documentation paddle example:
```
import "regenerator-runtime/runtime";

import * as ex from 'excalibur';
import {vec, Actor, Color, CollisionType, Engine} from 'excalibur';

const game = new Engine({
  width: 800,
  height: 600,
});

game.start();

const paddle = new Actor({
x: 150, y: game.drawHeight - 40,
width: 200, height: 20,
color: Color.Chartreuse
});

const paddle2 = paddle.clone();
```

### Expected Result

A deep copy of `paddle` would be stored in `paddle2`.

### Actual Result

When the code is compiled and executed, the following error is printed to the console, and execution halts:
```
Uncaught TypeError: transform is undefined
    update PolygonCollider.ts:408
    update ColliderComponent.ts:95
    onAdd ColliderComponent.ts:141
    addComponent Entity.ts:345
    clone Entity.ts:293
    parcelRequire<["main.js"]< main.js:15
    newRequire main.1f19ae8e.js:47
    parcelRequire main.1f19ae8e.js:81
    <anonymous> main.1f19ae8e.js:120
PolygonCollider.ts:408:22
    update PolygonCollider.ts:408
    update ColliderComponent.ts:95
    onAdd ColliderComponent.ts:141
    addComponent Entity.ts:345
    clone Entity.ts:293
    parcelRequire<["main.js"]< main.js:15
    newRequire main.1f19ae8e.js:47
    parcelRequire main.1f19ae8e.js:81
    <anonymous> main.1f19ae8e.js:120
```

### Environment

- browsers and versions: Firefox 102.0.1 (64-bit)
- operating system: Windows 10
- Excalibur versions: v0.27.0

### Current Workaround

None. See also #2408  for another failed attempt at copying an actor.

**Comment by eonarheim** [comment]
@robly18 Thanks for the issue!

Definitely a bug, I should have some time this week to look into this but clone should work like you expect.
