### ISSUE TITLE
Engine VisibleEvent is not firing on visibility change

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2409]
### Steps to Reproduce

This is reproducible with the [sample platformer](https://codesandbox.io/s/github/excaliburjs/sample-platformer)

- Start game
- Switch tabs or unfocus window
- Go back to game and it remains paused
- console log only shows "pause", no "start", which means the visible event never fired

### Expected Result

Engine should emit the "visible" event when window is focused

### Actual Result

It does not emit the "visible" event

### Environment

- browsers and versions: Chrome 103.0.5060.114 , FireFox 102.0.1, Safari 15.5
- operating system: macOS 12.4
- Excalibur versions: 0.27

### Current Workaround

I see that we have some browser-specific behaviour here https://github.com/excaliburjs/Excalibur/blob/88a30ceb7fd2986e2d13f4d2fa7c8be87a1def09/src/engine/Engine.ts#L1112-L1133 but I am currently doing this instead:

```js
document.addEventListener('visibilitychange', () => {
  if (document.visibilityState === 'hidden') {
    engine.stop()
  } else if (document.visibilityState === 'visible') {
    engine.start()
  }
})
```

which seems to have [good browser support](https://caniuse.com/mdn-api_document_visibilitystate)

**Comment by eonarheim** [comment]
@mattjennings Thanks for the bug! Good find!

It definitely seems the browsers have improved their support for visibility. I would also support simplifying the code to remove the old prefixed polyfills.
