### ISSUE TITLE
Add a convenient hook for Postprocessors to update

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#2416]
### Context

Currently there is no lifecycle hook for postprocessors to update over time.

See discussion #2415

### Proposal

Add some sort of hook that allows users to update uniforms after the shader has been bound.

Perhaps a `onPreRender()` or `update`? Not sure what makes the most sense?

**Comment by mattjennings** [comment]
I have personally been doing something like this:

```js
class MyActor extends ex.Actor {
    effect = new SomePostProcessor()

    onInitialize(engine) {
          engine.graphicsContext.addPostProcessor(this.effect)
          const shader = this.effect.getShader()

          // set initial uniforms, otherwise shader errors
          shader.use()
          shader.setUniformFloat('u_time', 0)
    }

    onPreUpdate() {
          const shader = this.effect.getShader()
          shader.use()
          shader.setUniformFloat('u_time', someValue)
    }
}
```

which I honestly haven't minded to this point, but this about as complex as my usage has gotten.

A lifecycle hook that allows me to set the uniforms once instead of both in initialize and an update loop would be nice. Possibly something that abstracts`shader.use()` when setting uniforms would be handy too (but I imagine there's good reason to have that called separately).

**Comment by eonarheim** [comment]
@mattjennings I like what you've done here! That's a pretty convenient work around at the moment.

I think it makes sense to have a shader specific lifecycle hook for the situation you describe. Perhaps something specific like `onUpdate(...)` which would be called every frame and be guaranteed to have `shader.use()` constext setup? And maybe a `onInitialize(...)` which would be called once?

It's probably worth including a few well known uniforms by default (definitely `u_time` for sure). I use ShaderToy a good deal to develop shader code, maybe borrowing some from their list would be useful? At minimum it would help when sourcing shader code into excalibur?

<img width="361" alt="image" src="https://user-images.githubusercontent.com/612071/179405189-5c4bf66c-41cb-4876-9e73-dd32a53ffc2b.png">

Things that look useful on first glance might be `iTime`, `iTimeDelta`, `iMouse`, iResoultion`?

I'd want to also document a way to include additional textures into the composition as well.

**Comment by mattjennings** [comment]
That all sounds good to me! 

A set of well-known uniforms from ShaderToy would be awesome. It seems to be the go-to for examples, and it would really help newcomers like myself with migrating to Excalibur.
