### ISSUE TITLE
Actors page Working with Images & Sprites having incorrect info

### ISSUE THREAD

**Issue by kennyneedsmilky** [excaliburjs/Excalibur#2417]
On the Actors page, in the Working with Images & Sprites section, it shows incorrect information about actor.

As you can see in the picture, isn't it supposed to be `actor.graphics.use(sprite)` instead of `actor.use(sprite)` ?

<img width="939" alt="スクリーンショット 2022-07-17 午前5 07 59" src="https://user-images.githubusercontent.com/74458502/179370600-3721b36a-ce10-4a1c-b8da-b97905ec09c8.png">

**Comment by eonarheim** [comment]
Hi @kennyneedsmilky, thanks for the issue!

I believe you are correct, this is indeed a typo in the docs 👍

**Comment by eonarheim** [comment]
Updated! Docs should be redeployed momentarily 👍  https://github.com/excaliburjs/excaliburjs.github.io/commit/d08b1fb2b39aee436410240e40c74306de019596

Thanks again @kennyneedsmilky!
