### ISSUE TITLE
Emitting an event with a value of 0 produces a GameEvent instead

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2418]
When emitting a custom event on an object, if the value is 0 it gets overwritten by a GameEvent due to this line:

https://github.com/excaliburjs/Excalibur/blob/730d621805d32104c18dc7ca8d9e97c7f212bb2b/src/engine/EventDispatcher.ts#L36-L38

### Steps to Reproduce

Emit an event with a value of 0:

```js
actor.emit('something', 0)

actor.on('something', (value) => {
    console.log(value) // GameEvent
})

actor.emit('something', 1)

actor.on('something', (value) => {
    console.log(value) // 1
})
```

### Expected Result

Value to be persisted

### Actual Result

Value gets overwriten with GameEvent

### Environment

- Excalibur versions: 0.27

### Current Workaround

Create a custom GameEvent instance and emit that instead. Perhaps that is the intention, that every event should be an instance of GameEvent? If so, should `emit` throw an error if it receives something other than `undefined` or a `GameEvent`?

**Comment by eonarheim** [comment]
@mattjennings Thanks for the bug! 

My spidey sense says this is likely bad falsey checking and providing a default `GameEvent`

**Comment by mattjennings** [comment]
@eonarheim yup that's what's happening here. I started working on a PR to fix this by only forcing to `GameEvent` if `null` or `undefined` - however I noticed the type definition for `emit` on `EventDispatcher` is:

```ts
public emit(eventName: string, event: GameEvent<T>) {}
```

while on `Class` it's:

```ts
public emit(eventName: string, eventObject: any) {}
```

so while I can update `EventDispatcher` to preserve non-GameEvents, it goes against the expected type. Should `Class` be updated to take `GameEvent`? If so, what should `emit` do when it receives something else?

**Comment by eonarheim** [comment]
Awesome, thanks for picking this up!

My intention is to remove the `GameEvent<T>` requirement eventually, it's been artificially constricting (requiring people to build custom events for simple things) and hasn't been very useful in general...

I'd support widening the type in the PR to be looser on `EventDispatcher.emit()`, maybe this? 

```typescript
// This might need some additional thought if it winds up causing typing issues elsewhere...
public emit(eventName: string, event: GameEvent<T> | any) {}
```

Otherwise I'm okay with a tactical change to just address the bad falsey check, and we can continue thinking/discussing the types on `EventDispatcher`

**Comment by mattjennings** [comment]
Good to know, I agree that it is a bit cumbersom to have to make custom events for simple values.

Doing `GameEvent<T> | any` effectively just casts it as `any`, unfortunately:

<img width="542" alt="CleanShot 2022-07-17 at 13 36 49@2x" src="https://user-images.githubusercontent.com/8703090/179420053-6aae4a52-231a-4d2b-ae50-b5ed3b3066b8.png">

I will just address the falsey check for now then!
