### ISSUE TITLE
Screen.contentArea and canvas seems to get out of sync when resizing window

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2435]
I might be misunderstanding how to use `Screen.contentArea`, but it seems that when using a display mode of `FitScreenAndFill` either the bounds are incorrect or the canvas does not draw positions properly after the window is resized.

Here's a video of the codesandbox repro below. When I refresh the page, the positions are correct.

https://user-images.githubusercontent.com/8703090/181378639-d6506f19-08eb-443b-8c2b-ed5bb98ed749.mp4

### Steps to Reproduce

repro: https://codesandbox.io/s/excalibur-fitscreenandfill-bug-epeb2u?file=/src/index.js

Red box is anchored to top/left of `contentArea`, while green box represents the entire bounds of `contentArea`. If you resize the window, they drift from where they should be. If you refresh the page they are in the proper spot, and notice the logged coordinates of the red box are the same before/after the refresh.

If I'm doing anything incorrect please let me know!

### Expected Result

Setting an object's position to bounds of `Screen.contentArea` should stay consistent after window resize

### Actual Result

Positions drift after resize, but are in expected position after refresh using same window dimensions

### Environment

- browsers and versions: Chrome 103, also seeing same behaviour on FireFox and Safari
- operating system: macOS 12.4
- Excalibur versions: 0.27
- I am using a device with devicePixelRatio of 2 (macbook pro)

**Comment by eonarheim** [comment]
@mattjennings Thanks for the bug!

Definitely feels like a bug, I share your expectations 👍

**Comment by eonarheim** [comment]
I have a workaround for this example, it positions the camera in the center of the screen. This may not work in all situations... but not totally sure.

```typescript
engine.onPostUpdate = () => {
  engine.currentScene.camera.pos = engine.screen.center;
}
``` 

I think the core issue with `contentArea` the `*AndFill` style display modes is that the resolution changes dynamically (more world space pixels), but the camera position does not adjust with it. I think the fix will involve adjusting camera position or the default graphics context transform?

**Comment by eonarheim** [comment]
Oh I just realized that `contentArea` is in screen space which is a potentially confusing aspect. Actors in world space still drift unexpectedly, but this will draw the `contentArea` in world space at least.

```typescript
bounds.on("preupdate", () => {
  // calculate safe area in world space
  const topLeft = engine.screen.screenToWorldCoordinates(ex.vec(engine.screen.contentArea.left, engine.screen.contentArea.top));
  const bottomRight = engine.screen.screenToWorldCoordinates(ex.vec(engine.screen.contentArea.right, engine.screen.contentArea.bottom));
  bounds.pos = topLeft;
  bounds.graphics.current[0].graphic.width = bottomRight.x - topLeft.x;
  bounds.graphics.current[0].graphic.height = bottomRight.y - topLeft.y;
  bounds.graphics.recalculateBounds();
});
```

**Comment by eonarheim** [comment]
Sorry for all the spam! Would you expect that the top left of the content area would always correspond to (0, 0) in world space? I feel like that _should be_ the right thing to expect (currently not the case in excalibur)

<img width="759" alt="image" src="https://user-images.githubusercontent.com/612071/181412072-5e9e234b-ff2e-462f-bf55-47058e9e8bc2.png">

**Comment by mattjennings** [comment]
I think that is what I would expect, but this is the first time I've ever worked with a dynamic resolution so I'm not sure if that's the correct expectation 😅. If that's also what you would expect though, then I think that would be the proper change. I may have also been thrown off by the `contentArea` being in the screen space like you said, but I think your code snippet there might do the trick. I'll give it a shot!

In the end, I was looking for a way to consistently anchor to any side of the "safe" area following resize, and that if I refresh the page at those dimensions, it'll be the same placement. I think what confused me the most was the difference in positions when resizing and then refreshing.

**Comment by eonarheim** [comment]
@mattjennings I think I've got this fixed up in the PR, some small code changes but it should produce the desired effect once merged.

The `contentArea` is in screen space, so to draw those bounds I switched the `bounds` actor to `  coordPlane: ex.CoordPlane.Screen`. Now the origin should always be the top left of the green bounds 🚀 
![content-area](https://user-images.githubusercontent.com/612071/183230691-02eeecaa-1f16-421d-87d2-be8e53d972e3.gif)

```typescript
var engine = new ex.Engine({
  width: 400,
  height: 400,
  displayMode: ex.DisplayMode.FitScreenAndFill
});


var box = new ex.Actor({
  pos: ex.vec(50, 50),
  width: 64,
  height: 64,
  color: ex.Color.Red,
  anchor: ex.vec(0, 0)
});

var bounds = new ex.Actor({
  color: ex.Color.Green,
  height: 1,
  width: 1,
  coordPlane: ex.CoordPlane.Screen,
  anchor: ex.vec(0, 0)
});

engine.add(bounds);
engine.add(box);


bounds.on("preupdate", () => {
  bounds.graphics.current[0].graphic.width = engine.screen.contentArea.width;
  bounds.graphics.current[0].graphic.height = engine.screen.contentArea.height;
});

engine.start();
```

**Comment by mattjennings** [comment]
@eonarheim this is awesome! Thanks a ton, this looks like a fantastic solution. Great job!
