### ISSUE TITLE
Sound looping does not seem to be working

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2450]
### Steps to Reproduce

repro: https://codesandbox.io/s/github/mattjennings/excalibur-sound-loop-bug

1. set `snd.loop = true`
2. play via `snd.play()`
3. sound does not loop

This occurs on Safari/Chrome/FF. However, some funny behaviour between the 3:

On Chrome, if I unfocus/refocus the tab the sound will play again.

On FireFox, switching to a different tab will sometimes loop the sound, but at louder (and seemingly random) volumes. Focusing back on the excalibur tab will sometimes play the sound again. It gets pretty funky if you start flipping back and forth between the 2 tabs.

On Safari, nothing happens when switching tabs.

Here's a video with audio showing the behaviour on FF (ignore the extra sounds at 0:03, that's the macOS sound effect from turning up the volume)

https://user-images.githubusercontent.com/8703090/182677673-fc5d4ee5-4689-42ff-b868-8d27beab68eb.mp4

### Expected Result

Sound should loop

### Actual Result

Sound does not loop, odd behaviour when switching tabs on Chrome/FireFox.

### Environment

- browsers and versions: Chrome 103, Safari 15.5, FireFox 103
- operating system: macOS 12.4
- Excalibur versions: 0.27

### Current Workaround

Avoid setting `snd.loop = true` and manually play again by either checking for `snd.isPlaying()` during update, or hooking into `playbackend` event.

**Comment by eonarheim** [comment]
@mattjennings Thanks for the bug and the thorough reproduction!

I think the loop regression and odd behavior may have been caused by the `Sound` refactoring to an internal state machine. I think I have a fix :+1:
