### ISSUE TITLE
Create a packaging utility to easily generate platform packages ready for use

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#246]
Name pending. Anvil? Forge? Foundry?

Create a packaging utility that takes a compiled game and assets and generates a package (or packages) that makes it easy to publish your game.
- [ ] Package into node-webkit for Linux, Mac, PC
- [ ] Package into Universal App for Windows 8.1 and Windows Phone 8.1
- [ ] Package into WinJS App for Xbox One (when that support is announced)
- [ ] Package into Chrome app

The templates should probably be in a repository or set of repositories for easy management and updates.

Pseudo-invocation of utility:

```
> forge .\dist -p "universal-app" -p "node-webkit"
```

Options to be determined.

**Comment by eonarheim** [comment]
This is out of scope for excalibur core
