### ISSUE TITLE
Support "wasPressed" and "wasReleased" for Gamepad input

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2460]
### Context

It would be helpful if `engine.inputs.gamepad` supported `wasPressed` and `wasHeld` the same way `engine.inputs.keyboard` does.  This would make it easier to interchangeably support keyboard or gamepad input.

### Proposal

Add `wasPressed(button)` and `wasReleased(button)` to gamepad input API. Perhaps rename `isButtonPressed()` to `isButtonHeld()` to closer match keyboard API (`isKeyHeld()`)

**Comment by ewal** [comment]
+1 on this

**Comment by eonarheim** [comment]
@mattjennings I think this is a great idea! I fully support this

**Comment by eonarheim** [comment]
I'd be in favor of increased consistency between the keyboard & gamepad API. 

We can mark the `isButtonPressed()` as `@deprecated` and will be removed in v0.28.0
