### ISSUE TITLE
Build error due to `@obsolete` decorator

### ISSUE THREAD

**Issue by ewal** [excaliburjs/Excalibur#2462]
Just a fyi, not a real issue :)

I have a local version of Excalibur which I reference by path in a project. When building my project with parcel I get the following error:

```
@parcel/transformer-js: Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key

  /node_modules/excalibur/Collision/Physics.ts:106:3
    105 |
  > 106 |   @obsolete({
  >     |   ^
    107 |     message: 'Alias for incorrect spelling used in older versions, will be removed in v0.25.0',
    108 |     alternateMethod: 'dynamicTreeVelocityMultiplier'

```

I noticed that this particular decorator is only used here and nowhere else in the project instead of jsdoc deprecation comments so I figured that perhaps it's a leftover. 
(I do have decorators enabled in my project so still confused why the error is thrown but probably a local config :man_shrugging: )

**Comment by eonarheim** [comment]
Oh indeed, we use/used this particular decorator to throw warnings into the browser console when a `@deprecated` method is used as an additional signal to the developer. But perhaps the jsdoc `@deprecated` is good enough a signal? @jedeen @kamranayub I'm curious if you think we should just remove the `@obsolete()` experimental ts decorator. 

It looks like it might be a parcel specific issue with SWC https://github.com/parcel-bundler/parcel/issues/7425, looks like a workaround was mentioned by switching away from the SWC transformer https://github.com/parcel-bundler/parcel/issues/7425#issuecomment-991258011

**Comment by ewal** [comment]
Thank you. Yeah, definitely related to parcel.
