### ISSUE TITLE
Support wrapping ex.Text graphics

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#2463]
### Context

Currently it is not possible to wrap text graphics inside a bounding box without some manual intervention or custom code.

See discussion for more context https://github.com/excaliburjs/Excalibur/discussions/2458#discussioncomment-3393549

### Proposal

Implement simple text wrapping given a optional maximum width or an optional containing bounding box.

Perhaps `ex.Text.maxWidth` or `ex.Text.textContainer`?

```typescript
const text = new ex.Text({
  ...
  maxWidth: 200 // pixels
});
``` 

```typescript
const text = new ex.Text({
  ...
  textContainer: ex.BoundingBox.fromDimension(200, 200); // 200x200 box
});
```

**Comment by DaVince** [comment]
+1 for having a `textContainer` property containing a `BoundingBox`. Special care would then be given to also respect the text container height so it doesn't render text beyond the given bounding box.
