### ISSUE TITLE
`actions.scaleTo` never completes when scaling exclusively on the x-axis

### ISSUE THREAD

**Issue by reissbaker** [excaliburjs/Excalibur#2470]
Hello! :wave:

I'm pretty sure I found a bug in the `ScaleTo` action; the `isComplete` method checks `tx.scale.y` against the x-axis, rather than the `tx.scale.x` against the x-axis, and so the action will never complete if, for example, you're only scaling the x-axis. [The bug is on this line](https://github.com/excaliburjs/Excalibur/blob/fd2fa241da53558ebbebb300463d06ed465713a2/src/engine/Actions/Action/ScaleTo.ts#L64); I also cloned the repo, wrote a test, watched it fail, and then fixed the `isComplete` method; I'm opening this issue first since the PR checklist asks you to open an issue first. :smile:

### Steps to Reproduce

```javascript
actor
  .scaleTo(vec(2, 1), vec(1, 1))
  .scaleTo(vec(3, 1), vec(1, 1)); // This will never run
```

### Expected Result

The first scale would complete, and then the second scale would run and complete.

### Actual Result

The first scale executes, but never believes it's completed, and so the second scale never runs.

### Environment

- browsers and versions: Chrome, but this is a problem in any browser; the line of code that checks the x-axis for completion actually checks the y-axis.
- operating system: Windows
- Excalibur versions: main branch

### Current Workaround

Manually do the scaling yourself in an pre-/post-/`update` function instead of using the action.

**Comment by eonarheim** [comment]
Hi @reissbaker! Thanks for the issue! Good find!
