### ISSUE TITLE
(logo) Image has not completed loading before drawImage

### ISSUE THREAD

**Issue by sl45sms** [excaliburjs/Excalibur#2538]
### Steps to Reproduce
In some cases on low speed engine (jsdom/canvas) and probably on some low end pc's, the image, when populated from the getter, does not complete loaded when calling the drawImage.

Actually, I've made it to run the excalibur at nodejs [excalibur-on-nodejs](https://github.com/sl45sms/excalibur-on-nodejs) except this issue.

### Expected Result

the load of logoImg be completed before draw.
### Actual Result

a fatal error from underline canvas
```
[Fatal] :  Error: Image given has not completed loading
```
### Environment

- browsers and versions: jsdom/canvas 
- operating system: linux
- Excalibur versions: v0.27.0 
- (anything else that may be relevant) 

### Current Workaround
So, I propose to wait for onload event before the drawImage.
```
this._image.onload = () => ctx.drawImage(this._image, 0, 0, ....
```

**Comment by eonarheim** [comment]
I think this has been fixed!
