### ISSUE TITLE
the text location is error in isometric tiled map

### ISSUE THREAD

**Issue by sparkok** [excaliburjs/Excalibur#2574]
I find that the location of a tiled text or a object is  error in isometric tiled map. 
![1675721720392](https://user-images.githubusercontent.com/7651365/217099765-ca2f47c4-f46a-479e-8db0-7363e26b651c.png)
![1675721817266](https://user-images.githubusercontent.com/7651365/217100048-a6b1b081-ccde-4723-bf50-5500f4c15a14.png)

**Comment by eonarheim** [comment]
@sparkok This is definitely unexpected, I've marked this as a bug. I'll take a look before the next release.

**Comment by eonarheim** [comment]
Fixed in https://github.com/excaliburjs/excalibur-tiled/pull/448
