### ISSUE TITLE
Weird behavior on actor clone

### ISSUE THREAD

**Issue by robly18** [excaliburjs/Excalibur#2575]
(Wasn't there a template for bug reports somewhere? I couldn't find it this time around.)

Excited as I was for the clone bug fix, I continued working on a side project of mine, but ran into some weirdness. After a lot of second guessing myself, I've reached the conclusion that the current method for actor cloning has a bug in it somewhere.

This example is being run on Excalibur v0.28.0-alpha.628+017953a.

## Minimal Working Example

```
import "regenerator-runtime/runtime";

import * as ex from 'excalibur';
import {vec, Actor, Color, CollisionType, Engine} from 'excalibur';

const game = new Engine({
  width: 800,
  height: 600,
});

game.start();

const paddle = new Actor({
x: 150, y:  40,
width: 200, height: 20,
color: Color.Chartreuse,
collisionType: CollisionType.Active,
});
game.add(paddle);

const paddle2 = paddle.clone();

paddle2.pos.x = 400;
paddle2.color = Color.Red;
paddle2.on('collisionstart', (ev)=>{console.log(ev);});
game.add(paddle2);

ex.Physics.useRealisticPhysics();
ex.Physics.gravity = vec(0,60);

const wall = new Actor({
x: 100, y:  400,
width: 200, height: 20,
color: Color.Black,
collisionType: CollisionType.Fixed
});
game.add(wall);
```

## Expected Behavior

One should see two falling physics objects, `paddle` and `paddle2`, and a `wall` below `paddle`. `paddle2` should be a copy of `paddle`, but with a different x coordinate and a different color. There is a `collisionstart` event assigned to `paddle2`, which should never occur because it never collides with `wall`.

## Actual Behavior

While `paddle2` does indeed have a distinct x coordinate from `paddle`, the change in color to `paddle2` also applies to `paddle`, which becomes red instead of chartreuse. Moreover, the `collisionstart` event is triggered when `paddle` collides with the wall.

## Probable Cause

The deep copy which should be happening when `paddle.clone()` is called is probably not deep copying some of the object's components.

**Comment by eonarheim** [comment]
> (Wasn't there a template for bug reports somewhere? I couldn't find it this time around.)

There certainly was, I'll figure out what happened there!

This does seem like a bug in the cloning, I think you are right not everything must be copied correctly. It sounds like there is something off in the graphics component color change, and the collider component events at minimum.

**Comment by robly18** [comment]
> @robly18 Does this show up for you when you click "new issue"? <img alt="image" width="599" src="https://user-images.githubusercontent.com/612071/218492838-60ff4a7d-ce18-4e27-b5a3-83edd83dcaca.png">

Yeah, now it does. Don't know why it didn't yesterday, maybe I opened an issue in some weird way that automatically opened a blank issue. Thanks!

**Comment by eonarheim** [comment]
Thanks @robly18 for reporting this!

**Comment by eonarheim** [comment]
I've tested against your repro and I think we've got both issues sorted 👍

**Comment by robly18** [comment]
No problem! Thank you for the excellent package.

As you can probably guess by my reports, I'm working on a project that uses `Actor.clone()` to some degree, so I'll be sure to report any weirdness I find!
