### ISSUE TITLE
Vue reactivity causes "Error rotating Dynamic Tree"

### ISSUE THREAD

**Issue by BinarySpike** [excaliburjs/Excalibur#2595]
### Steps to Reproduce

Wrap the `game` (`Engine`) in a vue reactivity like `ref` and call a `.goToScene`.  Add some actors to the scene (in the repro just click on the world) and the error "Error rotating dynamic tree" will happen quickly.

Wrapping the game engine in a generic `Proxy` does not cause the issue.  Unfortunately I cannot track down why the DynamicTree is having issues.

### Expected Result

No error.

I understand that I probably shouldn't wrap the game engine as a reactive element, but it's the "default" if you just pass it to the UI and have the UI call back into it.

Even if this isn't resolvable, I'd like to know why this happens.

A workaround (in vue3) is to use `markRaw(game)` on your data model in the UI component so it doesn't get wrapped.

### Environment

See https://github.com/BinarySpike/bug-reproduce-excaliburjs-and-vuejs as a reproduction of the bug.

Based on `template-ts-vite`

```typescript
class Game extends Engine {
    initialize() {
      let buggy = ref(this); // <-- this reproduces the bug

      console.log(buggy.value); // <-- Prints Proxy not Prints gamescene extends Scene

      buggy.value.addScene('game', new gamescene()); // <-- this is where things fall apart.
      buggy.value.goToScene('game');

      buggy.value.start();
    }
  }
  
  export const game = new Game({
    pointerScope: Input.PointerScope.Document,
  });
  game.initialize();
```

**Comment by eonarheim** [comment]
Closing, we recommend using the `markRaw` strategy to avoid vue attempting to watch the entire excalibur state
