### ISSUE TITLE
Move particle-tester to separate repository

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#260]
Particle tester is stand-alone.
- BONUS: Excalibur site repo can reference it as a submodule so it'll be under the excalibur site

We can then keep it separate from the core engine.

Thoughts?

Arguments:

* If people make excalibur a submodule, it reduces the cruft. 
* It's nice to keep things separate and stand-alone so people can contrib individually to what they want.
* It appeases my sense of organization
* It works towards a goal of making this repo solely about the "core" of Excalibur. I want `excaliburjs/core` eventually ;)

**Comment by eonarheim** [comment]
YAY!
