### ISSUE TITLE
Add an optional iOS "Tap to Play" interstitial button to Loader to accommodate interaction requirements for playing sounds

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#262]
Add an interstitial step to Loader that is optional (and extensible) to have user interact with a UI element to allow iOS to play sounds immediately after loading.

---

This is for the HTML5 Audio Fallback.

Created a test case here: http://kamranicus.com/wp81-ie11-audio-bug/

Issues:
- iOS will not play audio unless there's user interaction
- Mobile devices have a long initial load time causing a significant delay in playback

Related posts:
- http://codetheory.in/html5-audio-behaviour-and-support-in-ios-and-android/
- http://codetheory.in/fixing-html5-audio-problems-in-ios-and-android-mobile-browsers-to-overcome-the-limitations/
- http://codetheory.in/solve-your-game-audio-problems-on-ios-and-android-with-web-audio-api/
- https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

I think the plan will be to implement the app cache storage with the audio tag fallback for browers that support it. Then in WinJS environment, use Windows Runtime API for sound.

**Comment by jedeen** [comment]
@kamranayub Has any work been done to resolve this issue?

**Comment by kamranayub** [comment]
I don't remember doing anything for this, no.

**Comment by eonarheim** [comment]
We should confirm this is still bug

**Comment by eonarheim** [comment]
We could use the Xamarin test cloud to help test this
https://www.xamarin.com/test-cloud

**Comment by kamranayub** [comment]
Tested with Sweepstacks:

- Galaxy S6, Chrome -- No delay, works.
- iPhone 6S - Starts audio after engaging drag

**Comment by eonarheim** [comment]
@kamranayub I like the "tap to play" workaround in the Loader to get around this iOS limitation

Also this article was pretty good https://www.ibm.com/developerworks/library/wa-ioshtml5/ it suggest a similar workaround

**Comment by kamranayub** [comment]
Lets make this issue about implementing an optional loader function to do
this (with overridable draw/update). Just need to figure out how to detect
iOS... browser detection sucks, better if we can detect feature or test if
user interaction is required.
