### ISSUE TITLE
Screen element graphics anchor is broken in 0.28.0-alpha.547

### ISSUE THREAD

**Issue by ikiselev1989** [excaliburjs/Excalibur#2636]
### Steps to Reproduce
Create new screen element. Add graphics to it.

### Expected Result
Graphics is centered on element.

### Actual Result
Graphics is not centered on element.

**Comment by eonarheim** [comment]
Hi @ikiselev1989 

This isn't well documented, but `ScreenElement`'s have an anchor of (0, 0) by default which draw the graphics from the top left. Is this what you are seeing?

The anchor on `ScreenElement` can be changed to center graphics by setting it to (.5, .5)

```typescript
const screenElement = new ex.ScreenElement({..});
screenElement.anchor = ex.Vector.Half;
```

I've pushed an update to the documentation to highlight this gap https://github.com/excaliburjs/excaliburjs.github.io/commit/dc1f614a6c91a29d6c54134bfd0a91a506ec822d

**Comment by ikiselev1989** [comment]
Hi @onarheim 
Sorry, I was on fire and couldn't leave good feedback yesterday.
The story:
I used half vector anchor for graphics of `Screen Element` and it was good but in version 0.28.0-alpha.547 it's not affected for graphics.

**Comment by eonarheim** [comment]
@ikiselev1989 Interesting, I'll dig into those versions!

**Comment by ikiselev1989** [comment]
@eonarheim Hi! Of course. I want to use anchor in center of ScreenElement and add its graphics in the same place with anchor in center.
```
import {Engine, ImageSource, Loader, ScreenElement, Vector} from "excalibur";

const engine = new Engine({
    width: 600,
    height: 400
});

engine.debug.entity.showId = false;
engine.debug.collider.showGeometry = true;

engine.showDebug(true)

const image = new ImageSource('./vite.svg');

const loader = new Loader([image]);

const screenElement = new ScreenElement({
    pos: new Vector(engine.screen.halfDrawWidth, engine.screen.halfDrawHeight),
    width: 100,
    height: 100,
    anchor: Vector.Half
});

screenElement.graphics.use(image.toSprite(), {anchor: Vector.Half});

engine.currentScene.add(screenElement);

engine.start(loader);

```
I want:
![image](https://github.com/excaliburjs/Excalibur/assets/22061871/9fe0d4ab-3b21-4d30-bf6d-a5bd97d5db27)

I get:
![image](https://github.com/excaliburjs/Excalibur/assets/22061871/9867cae5-3d0e-47b1-95ba-1c1befeaaa43)

**Comment by eonarheim** [comment]
@ikiselev1989 Theoretically fixed, let me know if the latest alpha doesn't address the issue!

**Comment by ikiselev1989** [comment]
@eonarheim Hi! Sorry for late.
I still get this. 
![image](https://github.com/excaliburjs/Excalibur/assets/22061871/6689e392-1742-441c-8e84-14dad7f1e66c)
BUT maybe I understand it wrong. I think if I use Vector.Half for both of ScreenElement and its graphics it should be the same center of ScreenElement and its graphics.
