### ISSUE TITLE
Scale X=-1 breaks collision physics

### ISSUE THREAD

**Issue by ufukbakan** [excaliburjs/Excalibur#2688]
After setting scale.x to -1 my character goes through other colliders, can we fix this

**Comment by eonarheim** [comment]
@ufukbakan Thanks for the issue! This is definitely unexpected, my guess is there are some flipped normals in the collider geometry when this happens causing the errant behavior.

Are you using `scale.x = -1` to flip the graphics? If so, one workaround might be to use `Graphic.flipHorizontal` https://excaliburjs.com/docs/api/edge/classes/Graphic.html#flipHorizontal

**Comment by ufukbakan** [comment]
> @ufukbakan Thanks for the issue! This is definitely unexpected, my guess is there are some flipped normals in the collider geometry when this happens causing the errant behavior.
> 
> Are you using `scale.x = -1` to flip the graphics? If so, one workaround might be to use `Graphic.flipHorizontal` https://excaliburjs.com/docs/api/edge/classes/Graphic.html#flipHorizontal

I was scaling actor itself not the graphics (because i didnt want to loop all graphics and flip each of them) but it broke the physics so i had to loop each graphic animation to flip them

**Comment by eonarheim** [comment]
@ufukbakan Would a new feature on the graphics component to flip all the graphics associated with the actor during drawing be useful?

Something like

```typescript
const actor = new ex.Actor({...});

// Flips during drawing but doesn't 
actor.graphics.flipHorizontal = true;
actor.graphics.flipVertical = true;
```

**Comment by ufukbakan** [comment]
> @ufukbakan Would a new feature on the graphics component to flip all the graphics associated with the actor during drawing be useful?
> 
> Something like
> 
> ```ts
> const actor = new ex.Actor({...});
> 
> // Flips during drawing but doesn't 
> actor.graphics.flipHorizontal = true;
> actor.graphics.flipVertical = true;
> ```

Yes, i think it will be, so we dont have to define runLeft, runRight, jumpLeft, jumpRight, idleLeft, idleRight, attackLeft, attackRight... Just we will able to define run, jump, idle attack graphics and flip graphics if facing left
