### ISSUE TITLE
Scaling a tilemap breaks clipping.

### ISSUE THREAD

**Issue by thefakeplace** [excaliburjs/Excalibur#2699]
### Steps to Reproduce

Create a tilemap and apply scaling to it.

```typescript
const createTilemap = () => {
  const tilemap = new TileMap({
    rows: 16,
    columns: 16,
    tileWidth: SHEET_TILE_WIDTH,
    tileHeight: SHEET_TILE_HEIGHT,
  });

  for (const cell of tilemap.tiles) {
    const sprite = spriteSheet.getSprite(0
    cell.addGraphic(sprite);
  }

  tilemap.scale = vec(
    WORLD_TILE_WIDTH / SHEET_TILE_WIDTH,
    WORLD_TILE_HEIGHT / SHEET_TILE_HEIGHT,
  );
  return tilemap;
};
```

### Expected Result

Clipping works.

### Actual Result

Tiles are incorrectly clipped when they leave the camera view.

https://github.com/excaliburjs/Excalibur/assets/96276377/a1f718ae-0683-4c4c-b0af-117edfbc45fe

**Comment by eonarheim** [comment]
@thefakeplace Thanks for the issue! Definitely a bug!

I'll take a look at this soon 👍 

As a possible work around you could look at zooming the camera `Camera.zoom` to get the scaling you are looking to see.

**Comment by thefakeplace** [comment]
Thanks! That works for me
