### ISSUE TITLE
The collision of tiles disappear when placed right above a tile with a custom collider

### ISSUE THREAD

**Issue by Ziphil** [excaliburjs/Excalibur#2732]
### Steps to Reproduce
1. Create a tileset with custom colliders.
2. On a tile layer with custom property `solid` set true, place tiles *without* a custom collider vertically and then place a tile *with* a custom collider right below them.
3. Save the map as `.tmx` format.

### Expected Result
The tiles without a custom collider will be solid tiles (with square collisions), and the tile with a custom collider will have that collider.

### Actual Result
The collision of the tiles without custom colliders disappear. The tile with a collider is correctly pulled into. (See the right side of the following image)
<img width="306" alt="2" src="https://user-images.githubusercontent.com/17818689/188834576-7a73f610-f45f-4c04-a22d-16c4c9549b47.png">

Currently vertically consecutive solid tiles are merged into one collider (as is shown in the left side of the image above). I suspect this merging operation has some bug.

### Environment

- browsers and versions: Chrome 105.0.5195.52, Firefox 104.0.2
- operating system: Windows 10
- Tiled version: 1.9.1
- Excalibur versions: 0.28.0-alpha.562
- Tiled plugin versions: 0.27.0

### Current Workaround
Set custom colliders even for the tiles that is completely solid, and the merging will not occur and everything will be as expected.
<img width="303" alt="1" src="https://user-images.githubusercontent.com/17818689/188837806-b3ba4ebf-120d-442e-9a95-c90c354b8916.png">

**Comment by eonarheim** [comment]
@Ziphil I've transferred the issue over to the excalibur repo, turned out to be an quick fix 🎉
