### ISSUE TITLE
Keys wasPressed event in Engine class

### ISSUE THREAD

**Issue by ikiselev1989** [excaliburjs/Excalibur#2762]
Hi! I'm trying to add keys was pressed event in main input mapper, but it seems not working.
[the code on stackblitz](https://stackblitz.com/edit/typescript-bjsuc9?file=index.ts)

```
import {Engine, Keys} from "excalibur";

const engine = new Engine({
    width: 600,
    height: 400
});

engine.start().then(() => {
    engine.inputMapper.on(({keyboard}) => (keyboard.wasPressed(Keys.Space)), (pressed) => {
        console.log(pressed);
    })
});

```

**Comment by eonarheim** [comment]
Hi @ikiselev1989

This is a good question, we've had issues where keyboard events through iframes don't work unless they are in focus.

Clicking into or giving the canvas focus works

<img width="720" alt="image" src="https://github.com/excaliburjs/Excalibur/assets/612071/3db59cc7-c137-4f1f-a592-a2cd1a9dad7c">

Or opening in a new tab it does work 

<img width="495" alt="image" src="https://github.com/excaliburjs/Excalibur/assets/612071/fcdbad42-54f3-4ae6-be07-307d5d17f5a2">

**Comment by ikiselev1989** [comment]
@eonarheim Hi! Yep, `isHeld` is working, bit `wasPressed` is not working. This is what I want to work :)

**Comment by eonarheim** [comment]
@ikiselev1989 Oh yes you're right, I think the `wasPressed` might be a bug. I'll look into that!
