### ISSUE TITLE
Cameras should exist off of the scene not the engine

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#277]
This has been causing trouble when transitioning to new scenes, because the camera is now offset by a large amount

**Comment by eonarheim** [comment]
This is done

**Comment by jedeen** [comment]
It only looks like this is working on the root scene. The issue still persists if you create other scenes.

**Comment by eonarheim** [comment]
@jedeen Indeed it does

**Comment by eonarheim** [comment]
Cameras do not center properly when new scenes are created :(
