### ISSUE TITLE
Fix RotateTo and RotateBy to turn by the the shortest angle by default

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#282]
Currently RotateTo and RotateBy rotate in an arbitrary direction that is not correct or expected. Users should be able to specify a specific rotation strategy, otherwise the default ShortestPath is used.

```
enum RotationStrategy {
      ShortestPath = 0,
      Clockwise = 1,
      CounterClockwise = 2      
}
```

**Comment by kamranayub** [comment]
I'm sure this would be easier to write test-first and *then* work on implementation.
