### ISSUE TITLE
Sprite tint doesn't seem to have any effect.

### ISSUE THREAD

**Issue by fabiopolimeni** [excaliburjs/Excalibur#2848]
I am trying to get some shadows automatically out of a sprite. My idea was to use the `tint` property, which says it multiplies it by the current pixel color, to create a shadow on the fly. While `opacity` is taken into account, the `tint` doesn't seem to matter at all.

### Steps to Reproduce

```typescript
constructor() {
  ...

    // Create a shadow sprite that is a stretched version of the platform sprite
    this.shadow = this.graphics.add(
      "shadow",
      new Sprite({
        image: sprite.image,
        origin: vec(1, 1),
        sourceView: sprite.sourceView, // sourceView needs to be cloned if it exists
        tint: Color.fromRGB(0, 0, 0), // Semi-transparent black for shadow
        opacity: 0.5,
        scale: vec(1.2, 1), // Stretched horizontally and squashed vertically to look like a shadow
      })
    );
}
```
and later I do

```typescript
onInitialize() {
// Draw the shadow first, so it appears under the platform
    this.graphics.show(this.shadow);
    this.graphics.show(this.base);
}
```

### Expected Result

A black (shadow) sprite painted behind the base one with transparency.

### Actual Result

The shadow sprite is painted behind the base one, and it has the correct opacity, but the `tint` did not affect color of the sprite, so it as the same color of the original one.

- browsers and versions: Version 120.0.6099.109 (Official Build) (arm64)
- operating system: MacOs 14.2
- Excalibur versions: 0.28

**Comment by eonarheim** [comment]
Thanks for the issue @fabiopolimeni I'm looking at this now

**Comment by eonarheim** [comment]
@fabiopolimeni Totally a bug! It'll be a quick fix! PR incoming 👍

**Comment by eonarheim** [comment]
@fabiopolimeni The PR will be merged tonight, you can work around this issue by setting the tint after construction

```typescript
const sprite = new ex.Sprite(...)
sprite.tint = ex.Color.Black;
```

**Comment by eonarheim** [comment]
@fabiopolimeni Cut a new version last night! v0.28.4 has the fix in it

**Comment by fabiopolimeni** [comment]
Amazing, I will test this soon, thank you!

**Comment by fabiopolimeni** [comment]
> @fabiopolimeni Cut a new version last night! v0.28.4 has the fix in it

It works as expected for me too ;)
