### ISSUE TITLE
Actor PreDraw/PostDraw events not working, or are incorrectly typed

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2854]
It seems there are `predraw` and `postdraw` events in the [ActorEvents types](https://github.com/excaliburjs/Excalibur/blob/a77658c88f5d905439d9b14bbe9d531b026cacb7/src/engine/Actor.ts#L151C24-L151C24), but I don't believe they are actually emitted. 

I think these were added in the [strong event types refactor](https://github.com/excaliburjs/Excalibur/commit/032ff764c05231bc5bdaa9d86135940bcce0722c) - perhaps by accident, but FWIW it would be handy to have these events directly on the actor 😄

### Steps to Reproduce

Add an event listener on the actor for `predraw` or `postdraw`

https://codesandbox.io/p/devbox/admiring-elion-dqsvzf?file=/index.js:23,1-26,8

### Expected Result

Events should emit

### Actual Result

Events do not emit

### Environment

- browsers and versions: Chromium 120.0.6099.129
- operating system: macOS 14.2.1
- Excalibur versions: 0.28.4 
- (anything else that may be relevant) 

### Current Workaround

N/A

**Comment by eonarheim** [comment]
@mattjennings Good find! yup they should still emit! Should be an easy fix
