### ISSUE TITLE
Consider removing _ prefix for param names in overridable public methods

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2855]
### Context

When utilizing an IDE's autocomplete for overriding methods (Actor's `onPreUpdate` for example), it will autocomplete the method using param names from the definition of the super class:

![CleanShot 2023-12-26 at 12 20 43@2x](https://github.com/excaliburjs/Excalibur/assets/8703090/232a1eb7-532a-4e58-9b14-77a299b8107e)

Since the params are named with `_` prefix in the super method, I get them in my autocomplete too. I then go and remove them manually, kind of ruining the benefits of the autocomplete.

### Proposal

I presume this `_` is to dodge the no-unused-vars eslint rule. Perhaps there's a better way to do this so that it doesn't affect the public API.

Suggestions:

1. Disable the no-unused-vars rule for the line of the overridable methods

```ts
class Actor {
   onPreUpdate(engine, delta) { // eslint-disable-line no-unused-vars 
   }

    // or

   /**
    * Not sure if this affects the JS doc for the method
    **/
   // eslint-disable-next-line no-unused-vars 
   onPreUpdate(engine, delta) {}
}
```

2. Customize the [no-unused-vars](https://eslint.org/docs/latest/rules/no-unused-vars#argsignorepattern) rule to ignore based on some other pattern... perhaps hardcoding `engine`, `delta`, as those seem to be the most common... but this isn't very scalable

**Comment by eonarheim** [comment]
@mattjennings I agree, this is very goofy looking. And you are 100% right, eslint is the reason. I'd be down to do disable by line on overrides for sure.
