### ISSUE TITLE
Emit "actionstart" and "actioncomplete" events

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2856]
It would be useful the ActionsComponent emitted events when starting/completing actions

### Context

I have a moving platform that has its path defined by actions

```ts
    const platform = new MovingPlatform(
      {
        x: 300,
        y: 50,
        width: 100,
        height: 16,
      },
      (actions) =>
        actions.repeatForever((builder) =>
          builder.moveBy(0, -50, 40).moveBy(0, 50, 40)
        )
    )
```

I have some particular logic that I need to run whenever the platform changes direction that should happen immediately after the velocity is changed. Hooking into an event would be a very nice way to solve this.

### Proposal

Action component the following events containing the relevant action:

- `actionstart`
- `actioncomplete`

These can be either on the actor or the actions component, or both? This would also fire for each action in `repeatForever` etc.

```ts
type ActionStartEvent {
    action: ex.Action
}

type ActionCompleteEvent {
   action: ex.Action
}

this.on('actioncomplete', (ev) => {
   
})
```

**Comment by eonarheim** [comment]
100% down for this!
