### ISSUE TITLE
Add getGlobalOldPos() helper to Actors

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2922]
### Context

Serves same purpose as `this.oldPos`, but for the global position.

### Proposal

Add `this.getGlobalOldPos()` method to Actor.

Additional thought: any appetite for turning `getGlobalPos()` into a getter?

```ts
class Actor {
  get globalPos(): ex.Vector {
    // do global pos logic
   }

  get globalOldPos(): ex.Vector {
     // .. etc
  }
}
```

**Comment by eonarheim** [comment]
@mattjennings 100% totally agree.

I'm down to explore the getter 👍
