### ISSUE TITLE
Camera (TopCamera?) doesn't work properly at all when canvas "actual" size is lower than resolution

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#293]
Breakout sample can scale to a small screen with no issues. As soon as I try the same approach with Kraken, the map disappears but the glow remains under the kraken. It's totally messed up. The camera only works when the canvas "actual" size is > its resolution.

Reproduce:

1. Create a game canvas with a canvas res of 800x600
2. Use CSS to position: absolute the canvas and fill the screen
3. Resize the window to < 800x600 and observe the game works
4. Resize the window to > 800x600 and observe the game breaks

```html
<canvas width="800" height="600" style="position: absolute; top: 0; left: 0; right: 0; bottom: 0"></canvas>
```

**Comment by eonarheim** [comment]
@kamranayub I'm wondering if this will be fixed with #486 ...

A lot of the problems I feel like were from the zoom aspect of this. Do you remember any details about this?

**Comment by kamranayub** [comment]
Yah probably

**Comment by eonarheim** [comment]
I was able to repro this in Kraken, it is definitely offscreen culling for TileMaps that is not working

**Comment by eonarheim** [comment]
So I think this is the culprite piece of code right here

```typescript
TileMap.prototype.update = function (engine, delta) {
    var worldCoordsUpperLeft = engine.screenToWorldCoordinates(new ex.Point(0, 0));

    var worldCoordsLowerRight = engine.screenToWorldCoordinates(new ex.Point(engine.width, engine.height));
    // should be
    var worldCoordsLowerRight = engine.screenToWorldCoordinates(new ex.Point(engine.canvas.clientWidth, engine.canvas.clientHeight));
```

since we need the current client width/height of the canvas in order to adequately cull from the screen
