### ISSUE TITLE
Child entity should inherit transform.coordPlane of parent

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2933]
I think a child entity should inherit the coordPlane of its parent's transform. 

Consider having a ScreenElement with children - currently, its children do not follow along with it (at least, not properly). If I set the coordPlane of the children to ex.CoordPlane.Screen, they do.

### Steps to Reproduce

```ts
export default class Level1 extends ex.Scene {
  onInitialize() {
    const player = new ex.Actor({
      x: 100,
      y: 100,
      width: 100,
      height: 100,
      color: ex.Color.Yellow,
      vel: ex.vec(50, 0),
    })
    this.add(player)

    this.camera.strategy.lockToActor(player)

    const screenEl = new ex.ScreenElement({
      width: 100,
      height: 100,
      color: ex.Color.Red,
    })

    this.add(screenEl)

    screenEl.addChild(
      new ex.Label({
        text: 'hello',
        color: ex.Color.White,
        font: new ex.Font({
          size: 32,
        }),
      }),
    )
  }
}

```

https://github.com/excaliburjs/Excalibur/assets/8703090/a2f904e4-99fb-41a8-8f6b-e8ba74d37811

### Expected Result

It's a bit hard to tell in the clip, but "hello" should be staying in position as a child of the red box screen element.

### Actual Result

"hello" coordPlane is to the world instead of the Screen, so it moves off the camera.

### Environment

- Excalibur versions: 0.28.7

### Current Workaround

Manually setting the child's coordPlane to ex.CoordPlane.Screen

**Comment by eonarheim** [comment]
@mattjennings I agree, I think someone else ran into this and it produces unexpected results.

Going to label this a bug
