### ISSUE TITLE
excaliburjs.com/docs "Edit this page" link is generated incorrectly

### ISSUE THREAD

**Issue by ikudrickiy** [excaliburjs/Excalibur#3005]
### Steps to Reproduce

1. _Go to any page starting with https://excaliburjs.com/docs/ (this link fits the condition)_
2. _Find the `Edit this page` link at the bottom of the current article_
![image](https://github.com/excaliburjs/Excalibur/assets/139219793/d5bbc64f-9792-4e35-805b-f698073e68d1)
3. _Press this button to follow the link_

### Expected Result

4. **The link leads you to the right github doc page**

### Actual Result

4. **The link is broken, it has extra /docs/ division in its path**
For example:
https://github.com/excaliburjs/Excalibur/tree/main/site/docs/docs/00-your-first-game.mdx

### Environment

- browsers and versions: Google Chrome (version 123.0.6312.88)
- operating system: Windows 11 Pro for workstations (version 23H2)

**Comment by ikudrickiy** [comment]
Maybe this is related to the issue:
https://github.com/excaliburjs/Excalibur/blob/c0b6cdf7c9439f840f76d3c81bc4b991ea19c357/site/docusaurus.config.ts#L55

**Comment by eonarheim** [comment]
@kamranayub Did I mess up this configuration?

**Comment by eonarheim** [comment]
fixed with https://github.com/excaliburjs/Excalibur/commit/88594e26efc06ad9ece6a1f79537018a939a331f

Thanks for the report!
