### ISSUE TITLE
Optimise Side.fromDirection(direction: Vector): Side

### ISSUE THREAD

**Issue by ikudrickiy** [excaliburjs/Excalibur#3006]
### Context

Now [this function](https://github.com/excaliburjs/Excalibur/blob/c0b6cdf7c9439f840f76d3c81bc4b991ea19c357/src/engine/Collision/Side.ts#L38) to process dominant direction from a vector finds the most directionally similar vector between `Vector.Left`, `Vector.Right`, `Vector.Up` and `Vector.Down` computing the dot product twice(!) for each pair and finding the maximum result to get corresponding array index later. For some reason it also treats `-Number.MAX_VALUE` as the lowest number ever when in reality it is `-Infinity`.

### Proposal

I propose to determine the dominant direction by comparing the coordinates of the vector with each other to determine a quarter of plane this vector belongs to and along with this the dominant direction. The code below will have one shared ray assigned to the bottom instead of right. But it can be changed adding extra comparison. Among other things, such code is less prone to rounding errors.

<details>
  <summary>Plane partitioning diagram</summary>

![image](https://github.com/excaliburjs/Excalibur/assets/139219793/347caae7-7d15-46ee-8e62-19d2cddf3465)
</details>

Javascript code demonstrating the idea:
<details>
  <summary>My original solution</summary>

```js
if (y >= x) {
  //left or bottom
  if (y <= -x)
    //LEFT or top
    return Side.Left;

  //if (y === x) return Side.Right;

  //right or BOTTOM
  return Side.Bottom;
}

//right or top
if (y >= -x)
  //RIGHT or bottom
  return Side.Right;

//left or TOP
return Side.Up;
```
</details>

<details>
  <summary>More readable solution from `BoundingBox.getSideFromIntersection(intersection: Vector): Side`</summary>

```js
if (Math.abs(x) >= Math.abs(y)) {
  if (x <= 0) return Side.Left;

  return Side.Right;
}

if (y <= 0) return Side.Top;

return Side.Bottom;
```
</details>

**Comment by ikudrickiy** [comment]
https://github.com/excaliburjs/Excalibur/blob/c0b6cdf7c9439f840f76d3c81bc4b991ea19c357/src/engine/Collision/BoundingBox.ts#L58

has similar logic

**Comment by eonarheim** [comment]
@ikudrickiy Sorry for the delayed response! But this looks great!
