### ISSUE TITLE
Add Missing test files

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#305]
🔨 🔧 ❗️  
This is a collaborative effort to increase the valuable testing coverage for Excalibur. Any time you are working within the files and methods below, please add useful tests.
- [x] Algebra
- [ ] Scene onInitialize, onActivate, onDeactivate
- [ ] Cullbox.prototype.isSpriteOffScreen
- [ ] Cullbox.prototype.update whe offscreen
- [ ] Capture pointer update when is killed
- [ ] TileMapCollisionDetection update
- [ ] Vector normalize on zero length vectors
- [ ] Vector normals
- [ ] Ray non intersect
- [ ] base64encode (maybe remove?)
- [ ] drawLine
- [ ] randomIntInRange
- [ ] getPosition
- [ ] removeItemToArray
- [x] Sprites
- [x] SpriteSheet
- [ ] SpriteFont
- [ ] TileMap, Cell
- [x] SATBoundingBox (remove)
- [ ] Class
- [x] Timer.getTimeRunning
- [ ] NaiveCollisionResovler
- [ ] DynamicAABBTree
- [ ] EaseTo action
- [ ] RotateBy Type CounterClockwise
- [x] Fade action
- [ ] CallMethod
- [ ] Repeat
- [ ] ActionQueue remove
- [ ] ActionContext all actions
- [ ] SortedList _cleanUp
- [ ] Easing functions
- [x] predraw, postdraw, preupdate postupdate
- [ ] EventDispatcher unsubscribe
- [ ] Color effects (lighten, darken, etc)
- [ ] HSLColor fromRGBA
- [ ] UIActor contains
- [x] Trigger
- [x] Particles
- [x] Animation
- [x] FallbackAudio
- [x] Sound
- [ ] Resource load
- [ ] Loader
- [x] Texture load
- [ ] Detector
- [x] Template/Binding (remove maybe?)
- [x] Label
- [ ] Label#getTextWidth (#679)
- [x] Pointers
- [ ] Engine

**Comment by eonarheim** [comment]
We should look at https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md to ignore things that can't be tested

**Comment by eonarheim** [comment]
This is fairly out of date, and coverage is pretty good
