### ISSUE TITLE
Docs: Improve documentation for shaders

### ISSUE THREAD

**Issue by KokoDoko** [excaliburjs/Excalibur#3065]
### Context

The documentation page for post processors : https://excaliburjs.com/docs/postprocessors
doesn't seem complete. 

The examples for colorblindness work

There is an example for a grayscale shader, but this is missing information on how to implement the grayscale shader.
If you just copy the colorblindness example and replace the colorblindness shader with the grayscale shader, it doesn't work.

```js
const gray = new GrayScalePostProcessor();
game.graphicsContext.addPostProcessor(gray);
```
> 🚨 error: `getShader()` is not defined.

### Proposal

Include code that explains how to implement the grayscale shader

**Comment by eonarheim** [comment]
@KokoDoko Totally agree!
