### ISSUE TITLE
Error when child w/ transform + graphics component is added to entity without transform component

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#3073]
At this line here, transform can be undefined https://github.com/excaliburjs/Excalibur/blob/47cbb185c9b3b519720f841f6b3be46e11bacaac/src/engine/Graphics/GraphicsSystem.ts#L258

### Steps to Reproduce

```ts
    const parent = new ex.Entity()
    const child = new ex.Entity()
    child.addComponent(new ex.TransformComponent())
    child.addComponent(new ex.GraphicsComponent())
    parent.addChild(child)
    this.add(parent)
```
### Expected Result

No error

### Actual Result

```
[Fatal] :  TypeError: Cannot read properties of undefined (reading 'get')
    at GraphicsSystem._applyTransform (GraphicsSystem.ts:261:26)
```

### Environment

- Excalibur versions: 0.29.3

**Comment by eonarheim** [comment]
@mattjennings I think we could probably make this work... I can imagine a world where you have a container entity with no transform..
