### ISSUE TITLE
Docs: fix and/or update GraphicsGroup documentation

### ISSUE THREAD

**Issue by Autsider666** [excaliburjs/Excalibur#3085]
### Context
The [GraphicsGroup documentation](https://excaliburjs.com/docs/graphics-group/) is both incomplete and outdated.
- It misses examples for at least the direct Graphic inserion in the `members` parameter of its options
- `pos` seems to be replaced with `offset` in GraphicsGrouping

### Proposal

A quick fix would be replacing `pos` with `offset` [here](https://github.com/excaliburjs/Excalibur/blob/main/site/docs/04-graphics/04.2-graphics-group.mdx). Rewriting the whole page would be even better, but I'm not the best person to estimate/propose something in that direction, as I've 0 experience with that part of the codebase yet.

**Comment by eonarheim** [comment]
Hi @Autsider666 thanks for the issue!

Totally agree, this definitely needs to be better

**Comment by eonarheim** [comment]
Fixed! https://github.com/excaliburjs/Excalibur/issues/3085

Commits 
6087c4f052c4e4f927372ad128ff1cffe61c85dd
33a9df4502edd386d93bed7ac68b8adbc12423fc
