### ISSUE TITLE
precollision event inconsistencies between Actor hook and ColliderComponent event

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#3098]
The value of `other` in the precollision event is either a collider or the actor, depending on where you're listening to the  event from.

[Actor's `onPreCollisionResolve` is a collider](https://github.com/excaliburjs/Excalibur/blob/b57684c30686d2075e4d6cc6f65ba4577b32f4de/src/engine/Actor.ts#L1007)

[ColliderComponent event is the entity](https://github.com/excaliburjs/Excalibur/blob/b57684c30686d2075e4d6cc6f65ba4577b32f4de/src/engine/Collision/ColliderComponent.ts#L158), which is wiring from what the [System emits](https://github.com/excaliburjs/Excalibur/blob/b57684c30686d2075e4d6cc6f65ba4577b32f4de/src/engine/Collision/Solver/ArcadeSolver.ts#L90)

I would suggest keeping them always as colliders.

---

Tangentially (this could be its own issue but I figured i'd throw it in here), I wonder if lifecycle methods like `onXYZ()` on actors should always match the event payload. In other words 1 param as the event. Sometimes it's a pain when you want to move an event handler as a `.on()` handler to/from an Actor lifecycle method because one is multiple params whereas the other is an event object.

**Comment by eonarheim** [comment]
I agree, I think keeping them as the Collider would be less confusing

> Tangentially (this could be its own issue but I figured i'd throw it in here), I wonder if lifecycle methods like onXYZ() on actors should always match the event payload. In other words 1 param as the event. Sometimes it's a pain when you want to move an event handler as a .on() handler to/from an Actor lifecycle method because one is multiple params whereas the other is an event object.

It definitely feel like it should match... I'd support changes to make this so

**Comment by mattjennings** [comment]
cool, I've split that out into a separate issue then! https://github.com/excaliburjs/Excalibur/issues/3106
