### ISSUE TITLE
Change "priority" on System to be a static member

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#3102]
### Context

This would make it much easier to specify a system to run before/after another system.

```ts
class SomeSystem extends ex.System {
    static priority = ex.MotionSystem.priority - 1
}

**Comment by eonarheim** [comment]
I support this, you thinking like this? 
![image](https://github.com/excaliburjs/Excalibur/assets/612071/530e80b2-c452-4f7d-96df-ca7e5e4660c2)

This would definitely be a breaking change for anyone that's implemented a custom system

**Comment by mattjennings** [comment]
Yup, exactly. 

It appears you can actually have both an instance and static member of the same name (TIL), if we wanted to avoid the breaking change.
