### ISSUE TITLE
Graphic.tint nullability

### ISSUE THREAD

**Issue by raylu** [excaliburjs/Excalibur#3119]
`Graphic.tint` is a non-nullable `Color`, but it starts as `null` and the way to remove tint from a graphic is to set it back to `null`

**Comment by eonarheim** [comment]
We have loose types on parts of the project that allow these bugs to sneak through, adjusting this type should fix things. https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Graphics/Graphic.ts#L60

Additionally we should drop a new tsconfig targeting this directory to incrementally shore up types.
