### ISSUE TITLE
unused scene loader fails scene transitions and locks up engine

### ISSUE THREAD

**Issue by andybarron** [excaliburjs/Excalibur#3128]
### Steps to Reproduce

```ts
import * as ex from "excalibur";

class Scene1 extends ex.Scene {
  override backgroundColor = ex.Color.DarkGray;
  override onInitialize() {
    this.input.pointers.on("down", () => {
      console.warn("should change scenes");
      this.engine.goToScene("Scene2");
    });
  }
}

class Scene2 extends ex.Scene {
  override backgroundColor = ex.Color.Viridian;
  // issue still occurs if onPreLoad is not defined or
  // if we call super.onPreLoad(loader)
  override onPreLoad(loader: ex.DefaultLoader) {
    // un-commenting this call fixes the issue.
    // loader.addResource({
    //   data: {},
    //   isLoaded: () => true,
    //   load: () => Promise.resolve(),
    // });
  }
}

const game = new ex.Engine({
  scenes: {
    Scene1,
    Scene2: { scene: Scene2, loader: ex.Loader },
  },
});

game.start();
game.goToScene("Scene1");
```

### Expected Result

* Game logs `should change scene` and transitions to `Scene2` on click.

### Actual Result

* Game logs message but does not change scene. No more events are fired (e.g. pointer move), essentially locking up the engine.

### Environment

- browsers and versions: Firefox (128.0, 64-bit), Chrome (126.0.6478.127, arm64)
- operating system: macOS 14.5 (Sonoma) - MacBook Air (M1, 2020)
- Excalibur versions: 0.30.0-alpha.1106

### Current Workaround

Adding a fake resource to the loader fixes the issue.

**Comment by eonarheim** [comment]
@andybarron Woof definitely unexpected! Nice find! 

Theoretically should be a quick fix
