### ISSUE TITLE
docs: Update all engine source code Markdown comment symbol links to `{@apilink}`

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#3132]
We need to go around and fix up all the Markdown symbol links in the engine source code so they get rendered properly in the docs API site.

### Steps to Reproduce

On API pages, links between API symbols used to be done using the legacy symbol markup:

```
This is a link to the [[Actor]] class.

This is a link to the [[Actor|actor]] class with custom display text.
```

These should all be switched to `{@apilink symbol | text}` links ([docs](https://www.npmjs.com/package/docusaurus-plugin-typedoc-api#apilink)).

You can refer to `src\engine\Actions\ActionContext.ts` for an example that works.

> **NOTE:** Using the official `{@link}` tag [doesn't quite work as expected](https://github.com/milesj/docusaurus-plugin-typedoc-api/issues/66#issuecomment-2239524493) all the time, so for consistency I recommend `@apilink`.

### Expected Result

The links should work.

**Example:**

![image](https://github.com/user-attachments/assets/8ac8b77e-69ec-4af2-8fb2-02d18ca8d257)

### Actual Result

The links are rendered in plaintext.

**Example:**

![image](https://github.com/user-attachments/assets/9f779072-cd10-4614-8413-34ccc83e2c84)

**Comment by kamranayub** [comment]
If someone can get GitHub Copilot to do this, you'd be a hero 🤖

**Comment by Autsider666** [comment]
I've some free time today, so let me see if I can do this using search/replace combined with regex
