### ISSUE TITLE
Entity `silenceWarnings` option isn't available through Actor

### ISSUE THREAD

**Issue by Autsider666** [excaliburjs/Excalibur#3141]
### Context

The `silenceWarnings` option was added last week to prevent the "Entity X was not added to a scene"  messages during development. But it's not yet useable for Actors.

### Proposal

The most direct solution is adding it to ActorArgs and tunneling it to the Entity constructor, but that's not by definition the most sexy solution.
Another option would be to move the `silence` check to [inside the setTimeout](https://github.com/excaliburjs/Excalibur/blob/main/src/engine/EntityComponentSystem/Entity.ts#L143) and either add a setter to Entity or do something experimental like using a `silence` tag to block the warning.

**Comment by eonarheim** [comment]
@Autsider666 ope! we should make this visible on actors at minimum. Passing through the ctor arg would be the lowest effort fix
