### ISSUE TITLE
Proposal: rename or alias Vector.size to Vector.magnitude

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#3165]
### Context

This is something that I repeatedly get tripped up on.  It seems best to match Vector properties/methods to their mathematical operation. In Excalibur that's mostly true except magnitude is `size`, and I always forget. Most vector libraries also seem to name their magnitude property/method as `magnitude`

### Proposal

Deprecate `size` in favour of `magnitude`

**Comment by eonarheim** [comment]
@mattjennings totally agree
