### ISSUE TITLE
More accurate deltaTime

### ISSUE THREAD

**Issue by chrispytoes** [excaliburjs/Excalibur#3180]
I'm new to Excalibur, and I'm wondering why deltaTime is rounded to a whole number. It seems like my movement is actually smoother without using it at all because of how inaccurate it is. Logging it, it seems to keep jumping between 5 and 7, and always a whole number. It will never actually be correct since 60 fps has a deltaTime of 16.66.

**Comment by eonarheim** [comment]
@chrispytoes Thanks for the issue! I think we are using the highest precision timer available to us in js.
