### ISSUE TITLE
Spawning an actor right next to another actor sometimes causes unexpected placement

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#319]
In the Sleepy Hollow game, trying to start the player actor (`CollisionType.Active`) on the ground (an actor with `CollisionType.Fixed`) causes the player actor to spawn slightly above the ground. 

The current workaround is to create the player with `CollisionType.PreventCollision` and then in the `onInitialize()` of the player, set the collision type to Active.

**Comment by kamranayub** [comment]
Is it an issue with spawning *touching* or *overlapping* do you think?

**Comment by eonarheim** [comment]
@kamranayub Possibly both, I don't remember the specifics of the issue. This is pretty testable though.
