### ISSUE TITLE
Expose RendererPlugin interface as exported typescript types

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#3234]
### Discussed in https://github.com/excaliburjs/Excalibur/discussions/3233

<div type='discussions-op-text'>

<sup>Originally posted by **mccolljr** October  1, 2024</sup>
I wanted to play around with a custom renderer plugin, but I'm noticing that the RendererPlugin type isn't exported. TypeScript complains that the type is unexported, and some digging indicates that it is exported from `renderer.d.ts` but not from the `Context` `index.d.ts`. Is this intentional or just an oversight?</div>

**Comment by Autsider666** [comment]
What would be the requirements for an interface to be exposed (or not) in general?

**Comment by eonarheim** [comment]
We'll need the interface exported through the graphics `index.ts`, I think the root `index.ts` is already exporting all the graphics types.
