### ISSUE TITLE
Feature Request: add tile enter / leave events for tilemap tiles

### ISSUE THREAD

**Issue by rishavs** [excaliburjs/Excalibur#3283]
### Context
For tilemap based games, often we want to highlight cursor on tiles. For example, based on mouse cursor, we would need to highlight the tile the cursor is on. Today we do not have these events for individual tiles. 
For a discussion on this ask in the Discord, see https://discord.com/channels/1195771303215513671/1308773344379797554

### Proposal
We need to be able to capture the following events for each tile pointer enter, pointer leave, pointer click

**Comment by eonarheim** [comment]
Totally agree! I support this feature
