### ISSUE TITLE
clearParticles not working

### ISSUE THREAD

**Issue by brunocalou** [excaliburjs/Excalibur#3310]
### Steps to Reproduce

1. Add particles to a scene using an emitter
2. Call clearParticles method from the emitter

[CodePen link](https://codepen.io/brunocalou/pen/raBxKVg)

### Expected Result

The particles should be cleared

### Actual Result

The particles are unaffected

### Environment

- browsers and versions: Any browser
- operating system: MacOS 14.6.1 
- Excalibur versions: ^0.29.3

### Current Workaround

None

**Comment by eonarheim** [comment]
@brunocalou Thanks for the issue, definitely a bug! I'm working on particles tonight so I'll take a look

**Comment by eonarheim** [comment]
@brunocalou Pushed to main! Should be deployed to an alpha build momentarily
