### ISSUE TITLE
Rework Actions

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#353]
- [ ] Timelines (sets of actions)
- [ ] Separate API from actors
- [ ] Works on Groups
- [ ] State machine?
## Timelines/States

Need a way to create a set of actions that I can transition to/play depending on certain conditions. For example, in Kraken we want ships to have a Guard state, a Patrol state, a Hunt state, and maybe a Idle state and each has different sets of actions **plus** there may be different transitions between those states.

This could be achieved with FSM + Timelines, for example. I could define a set of timelines (Guard, Hunt) and then could "play" them. I would need a way to transition between timelines, I think, but that might just be another timeline itself (i.e. "Return to Guard").
## State machine

Is something like this useful, or just confusing:

``` typescript
actor.moveTo(...).moveTo(...).if(someConditionDoNextAction).rotateTo(...).else().moveTo();
```

or maybe a trigger system:

``` typescript
var trigger = new ConditionTrigger()
trigger.condition(function(){
   return true;
});
trigger.on(function(){
   actor.moveTo(...);
});
```

**Comment by eonarheim** [comment]
Closing for now, willing to accept new proposals
