### ISSUE TITLE
Misspelling in documentation on gh-pages

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/Excalibur#362]
"Test wether this bounding box collides with another returning, the intersection vector that can be used to resovle the collision. If there is no collision null is returned." under Collision/BoundingBox

"wether" should be "whether" and "resovle" should be "resolve".  Would also suggest some rephrasing to: "Test whether this bounding box collides with another one. Returns the intersection vector that can be used to resolve the collision. If there is no collision, null is returned."

**Comment by kamranayub** [comment]
You can now do this in `master` and it'll be live on the site.

**Comment by kamranayub** [comment]
Fixed in #421
