### ISSUE TITLE
Implement `bindProperty` or equivalent for actors (objects)

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#367]
Consider this:

An actor is concerned about controlling a few other actors (Button => Label, Some other effect, etc) and I would like to be able to set my related actors' properties to the same value as my own.

```
this.visible = false;
// should cascade to
this._label.visible = false;
this._labelOutline.visible = false;
this._pulsateEffect.visible = false;
```

**Comment by eonarheim** [comment]
Doesn't make sense anymore

**Comment by eonarheim** [comment]
This could be handled on the postupdate event
