### ISSUE TITLE
Event namespacing

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#370]
### Context
For dealing with `this` and such:

### Proposal 
```
this.off("pointerdown.mainmenu");
```

Removes all handlers under the namespace.

See jQuery docs:

> Event names should only contain alphanumerics, underscore, and colon chraracters.
> 
> An event name can be qualified by event namespaces that simplify removing or triggering the event. For example, "click.myPlugin.simple" defines both the myPlugin and simple namespaces for this particular click event. A click event handler attached via that string could be removed with .off("click.myPlugin") or .off("click.simple") without disturbing other click handlers attached to the elements. Namespaces are similar to CSS classes in that they are not hierarchical; only one name needs to match. Namespaces beginning with an underscore are reserved for jQuery's use.

**Comment by kamranayub** [comment]
This shouldn't be too hard, it's not hierarchical. So basically you will need a lookup dictionary for namespace => {event, handlers}, and then for a handler, to know what namespaces it's been assigned. The regex is simple. Then when doing `.off(".namespace.namespace2") for each namespace you remove any handlers (delete the key from the hash?).

**Comment by eonarheim** [comment]
We are reducing the scope of features we are focusing on to core engine and feature improvements. We are still open to PRs and/or plugins for non-core features.

Spoke with @jedeen offline
