### ISSUE TITLE
Capture mouseup/touchend events on document.body instead of engine.canvas 

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/Excalibur#374]
We ran into this for SweepStacks. If the user clicks and drags outside the canvas, mouseup/touchend events don't fire since they are being listened to on the canvas. Adding these listeners to document.body would prevent this and the events would still fire when they occur in the canvas due to bubbling.

**Comment by eonarheim** [comment]
The work left on this issue is to make this behavior configurable.
