### ISSUE TITLE
Implement engine.clear() (or better named) convenience method

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/Excalibur#376]
### Context
When developing SweepStacks, we ran into a lot of problems related to certain things not being disposed/reset properly because we were trying to restart the game/start a different game mode. 

### Proposal 
Implement a "global" disposal method that resets the Excalibur engine to its initial state.

It might be easier to implement once better disposal for actors, etc has been implemented, but the idea is to easily allow users to restart a game fresh without refreshing the page or doing something like window.location.reload since those both would require Excalibur to reload all resources.

Basic logic would be:

-Remove all actors and non-default scenes
- cancel all timers
  -unhook all keyboard, pointer, and gamepad events
- do anything else that would have to be done that I just don't know about yet

restarting the game then just becomes the developer calling the same methods he did before initially calling game.start.

**Comment by kamranayub** [comment]
Just ran into this today when trying to swap between different tile map examples in a visual test

**Comment by eonarheim** [comment]
I think it would be good if we kill all killable things in the scene and zero out all the collections `uiActors`, `actors`, `timers`, `triggers` etc

**Comment by eonarheim** [comment]
We should also allow scenes to be `.clear()`'ed as well
