### ISSUE TITLE
Support grouping of audio resources

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/Excalibur#380]
An associative array could store groups of related sounds. You could then apply existing audio methods to these groups to have those occur on all the soundbytes in the group.
 Possible use cases i've thought of:

Separating music from sound effects and allowing developer to easily mute/adjust volume of all audio in each group

Allowing a simple abstraction for playing several soundbytes at the same time

**Comment by eonarheim** [comment]
See #590
