### ISSUE TITLE
Catch global (fatal) errors to aid in debugging

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#381]
Exascerbated by mobile, update loop errors can cause crashing and are hard to debug. Can we figure out a way to intelligently catch errors in update loop and break/stop the game execution so it doesn't wedge browsers?

```
mainloop() {

  try {
    engine.update(delta);
  } catch (e) {
    // update loop error, catch and rethrow safely with debugging info
   cancelRequestAnimationFrame(mainloop);
  }
}
```

**Comment by eonarheim** [comment]
@kamranayub Should we also add an option to toast a friendly message to the user if the game crashes hard? Like "Oops, something went wrong. Please contact your friendly neighborhood game developer"?

**Comment by alanag13** [comment]
@eonarheim if such a message exists it should be configurable.

**Comment by eonarheim** [comment]
@alanag13 Agreed

**Comment by eonarheim** [comment]
@alanag13 @kamranayub I like having a event handler for this.

Should we expose something like this too?
```js
engine.on('fatalexception', ()=>{...})
```

**Comment by kamranayub** [comment]
Thought of that, figured one of the fatal errors could be with the event
dispatcher. This way it's very minimal, with no infrastructure to handle
fatal exceptions.

**Comment by eonarheim** [comment]
That is a good point... let's just do the `engine.onFatalException`
