### ISSUE TITLE
Sprite objects are too heavy from a memory perspective

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#384]
Currently every time you create a sprite or clone a sprite a new copy of the source bitmap is created in memory which is a huge problem for browsers with less efficient garbage collection. (Mobile browsers are especially limited when it comes to this). 

I propose that we create a `ex.LightSprite` which equivalent to most of the functionality of sprites, but without creating a duplicate bitmap. It would need to be very clear in the documentation that this type cannot use sprite effects.

Or we create a couple of backing implementations for the original `ex.Sprite` and user's opt in to sprite effects where the backing bitmap is required.

**Comment by kamranayub** [comment]
I feel like it would be weird to have a `LightSprite` and a `Sprite`, because why wouldn't a sprite be light by default? :confused: Opt-in seems best to me, like actors.

**Comment by eonarheim** [comment]
In Chrome we can get the size of the heap via JavaScript so we could make a coded test to measure the impact of any optimizations.

**Comment by eonarheim** [comment]
Additionally a memory optimization technique we could use to solve this issue, would be to implement a "Sprite Table" to store backing bitmaps until changed (think copy on write semantics) making sure that bitmaps are only loaded into memory when absolutely necessary.

**Comment by eonarheim** [comment]
The new #1425 will assist with this

**Comment by eonarheim** [comment]
Closed by #1730
