### ISSUE TITLE
New "dormant/hibernate" feature for actors

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#388]
### Context
Actor dormancy would be an opt-in feature to improve performance.

### Proposal
``` javascript
var actor = new ex.Actor();
actor.dormant = true
actor.dormant = false;
actor.dormant(true);
// or 
actor.sleep()
actor.wake()
// or
actor.suspend()
actor.activate()

```

This would effectively disable an actors' updates until they became active once again. Actors would still receive events in this state. There are a few reasons why you would want actors to remain dormant.
1. Save CPU Cycles while actor is offscreen (and the actor does not need to update)
2. Actor is inactive in the scene (aggro distance)
3. Potentially they are not yet unlocked

**Comment by kamranayub** [comment]
Just a note, I was trying to figure out if we had this feature yet and I searched for "disable" if that tells you what my brain thought to look for.

**Comment by eonarheim** [comment]
Closing for now
