### ISSUE TITLE
Add sender as a part of the GameEvent

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#389]
### Context 
Many times when events are emitted, we have no idea where they came from. I'm wondering if adding a sender property to the base GameEvent object would be useful, or if it is too risky considering they have a potential to leak memory.

### Proposal
``` javascript
class GameEvent {
   /**
    * Target object for this event.
    * @property target {any}
    */
   public target: any;

   /**
    * Object reference that originated this event
    * @property sender {any}
    */
   public sender: any;   

}
```

**Comment by pathurs** [comment]
Is this slightly implemented in #933 with my addition of `PointerEvent.pointer`?

@eonarheim

**Comment by eonarheim** [comment]
@pathurs I believe so, yes

**Comment by eonarheim** [comment]
Closing for now
