### ISSUE TITLE
Add color blind testing mode to Excalibur debugging

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#390]
### Context
Currently, it is not easy within Excalibur to test if your color scheme will make your assets difficult to see for those with the various forms of colorblindness.

### Proposal
Implement a way to simulate different colorblindness modes to help game developers design better color schemes for their assets.

**Comment by eonarheim** [comment]
I've created a "post processing" pipeline for excalibur, the first post processor to be implemented is the color blindness simulation and correcting processor named `ColorBlindCorrector`. But this also gives us opportunity to implement different post processing effects like glow, blur, sharpen, posterize, etc.

This provides a "quick" fix for games with color issues, however the post processor does eat 10 fps or so --even when optimized to run on the gpu with a glsl shader. We will need to be very clear about this downside in the documentation.

Usage is as follows:
```javascript
var game = new ex.Engine();
// game here

// The corrector can also simulate color blindness

// ex.Engine, simulate?, type of color blindness
var colorBlindCorrector = new ex.ColorBlindCorrector(game, false, ex.ColorBlindness.Protanope);
game.postProcessors.push(colorBlindCorrector);

```
Original sandbox
![image](https://cloud.githubusercontent.com/assets/612071/5604969/00639c92-93a8-11e4-8e19-c5561547af95.png)

Simulated Protanope color blindness in the sandbox
![image](https://cloud.githubusercontent.com/assets/612071/5604971/19564e20-93a8-11e4-9f9d-0be9495f3461.png)

Protanope color corrected version of the sandbox
![image](https://cloud.githubusercontent.com/assets/612071/5604965/d3997d8a-93a7-11e4-9862-196f86d45278.png)

**Comment by eonarheim** [comment]
We just need to add a debug option flag to close this issue

**Comment by eonarheim** [comment]
Proposed api implementation

```typescript
ex.debug.colorBlindMode.protanopeSimulate();
ex.debug.colorBlindMode.protanopeCorrect();

```

**Comment by Xstoudi** [comment]
@eonarheim I can implement the flags.
Considering your implementation, it will create 6 functions (two for each color blindness). Could we consider doing the following:
```js
ex.debug.colorBlindMode.simulate(ColorBlindness.XXX)
ex.debug.colorBlindMode.correct(ColorBlindness.XXX)
```

**Comment by eonarheim** [comment]
@Xstoudi That looks great, proceed :+1:
