### ISSUE TITLE
It is NOT clear that Excalibur is client-side only from the docs

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#391]
There has been some recent confusion about how to install and run node due to the npm package we have. We probably need to make clear in the docs that this package is only meant as another form of distribution (see https://www.npmjs.com/package/jquery). Even so, the presence of a client-side npm package sort of runs against the theory of npm. 

I think there are 2 options here:
* Really clarify the documentation around this
* Remove the npm package in favor of the bower one.

Thoughts anyone?

**Comment by kamranayub** [comment]
I vote removing in favor of bower... it's clear bower is meant for front-end libraries while npm was designed for node packages.

**Comment by eonarheim** [comment]
@kamranayub I'd be willing to remove it, but it does remove a deployment mechanism. On the other had we only need to support 2 from now on... @jedeen @alanag13 your thoughts?

**Comment by jedeen** [comment]
I'd be fine with removing it, especially if it will help prevent this sort
of confusion in the future.

**Comment by alanag13** [comment]
I agree, given that this is js and such I could see how this would be very misleading

**Comment by eonarheim** [comment]
We have deprecated the npm package and removed the npm install directions from our documentation
