### ISSUE TITLE
Enable eslint rule equivalent to ts-lint `completed-docs` rule

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#395]
### Context
We require JSDoc comments on all public members of Excalibur in order to properly generate our API documentation. While we always intend to manually review any new comments, this would prevent anything from slipping through without a comment.

### Proposal

Enable [completed-docs](https://palantir.github.io/tslint/rules/completed-docs/) TSLint rule.

```
"completed-docs": [
  {
    "classes": {"visibilities": ["exported"]},
    "enums": {"visibilities": ["exported"]},
    "enum-members": {"visibilities": ["exported"]},
    "interfaces": {"visibilities": ["exported"]},
    "functions": {"visibilities": ["exported"]},
    "methods": {"privacies": ["public", "protected"]},
    "properties": {"privacies": ["public", "protected"]}
  }
]
```

This should be implemented in this PR as a **warning** not an **error** until we address all outstanding issues it finds (we will open a separate core team PR).

**Comment by kamranayub** [comment]
Check this out, we can enable this right now!

https://palantir.github.io/tslint/rules/completed-docs/

**Comment by kamranayub** [comment]
I think we want:

```js
"completed-docs": [
  {
    "classes": {"visibilities": ["exported"]},
    "enums": {"visibilities": ["exported"]},
    "enum-members": {"visibilities": ["exported"]},
    "interfaces": {"visibilities": ["exported"]},
    "functions": {"visibilities": ["exported"]},
    "methods": {"privacies": ["public", "protected"]},
    "properties": {"privacies": ["public", "protected"]}
  }
]
```

And we should start out with this rule as a warning, not error, while we work to address the documentation.

**Comment by chris-bingham** [comment]
@eonarheim okay to handle this one?

**Comment by eonarheim** [comment]
@chris-bingham Actually we are recently switching to eslint given the eventual deprecation of tslint #1217 (apologies this issue lagged behind), however we would still like a similar feature in eslint if possible. If you base a branch on #1217, we'll merge your PR after #1217. 

If you'd like to figure out an equivalent eslint rule to completed-docs that would be awesome! We'll update the issue to reflect that

**Comment by chris-bingham** [comment]
Oh no I just opened a PR for tslint. But sure I'll have a look for the eslint equivalent

**Comment by eonarheim** [comment]
This branch has our basic eslint changes `feature/1212-tslint-to-eslint`, if you base off of this branch we'll merge your PR next 👍

**Comment by eonarheim** [comment]
Hi @chris-bingham, I've made some updates to the branch `feature/1212-tslint-to-eslint`, there was some more work to be done on this PRhttps://github.com/excaliburjs/Excalibur/pull/1217 apologies if this adds some more challenge.

I did a little more digging, I think this plugin may be what you need to complete this story, it looks like it has all the things that we want 👍 
https://www.npmjs.com/package/eslint-plugin-jsdoc
https://github.com/gajus/eslint-plugin-jsdoc

**Comment by chris-bingham** [comment]
Thanks for this @eonarheim, my research led me to the same plugin :)

**Comment by eonarheim** [comment]
@chris-bingham Are you still working on this? If you need any help let us know.

**Comment by chris-bingham** [comment]
@eonarheim I do still intend to do this, but have been absolulely stacked since i took it on. If anyone else wants the ticket they're welcome to it but if its not been done when I get some time I'll do it :)
