### ISSUE TITLE
Add random timer range as a feature of timers 

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#396]
### Context
There is a use case for creating a timer that has a variable duration. For example, if you wanted to randomly space events during a game.

### Proposal
Add the ability to specify a range (min and max) of time and allow the timer to randomly choose a duration within that range.

**Comment by yammik** [comment]
Hi! I'd like to work on this if it's still up for grabs 🙏

**Comment by eonarheim** [comment]
All yours! 👍

**Comment by DProBoy** [comment]
Is this still up for grabs ?

**Comment by eonarheim** [comment]
@DProBoy All yours, I've added the in-progress label

**Comment by DProBoy** [comment]
@eonarheim Can i (or Should I?) add new sandbox tests for the Random Timer ? I've committed the changes to my fork of Excalibur and i'm about to submit a pull request for #875 and #396 . (hehe ... still haven't gotten used to Git, as I was a Perforce user before ...)

**Comment by kamranayub** [comment]
It may be good to add some visual tests to the sandbox/tests/timers
directory (which doesn't exist yet but feel free to follow an existing
example).

**Comment by c3ho** [comment]
Hi, is this issue still open?

**Comment by eonarheim** [comment]
@c3ho I haven't seen any work on it, all yours!

Excalibur has a built in seeded `ex.Random` implementation that we should use to do the random calculations. 

It may be worth while to rethink the constructor and the Timer interface as well.

Perhaps something along these lines? If possible we should allow the previous constructor to be used as well avoid a breaking change

```typescript
export interface TimerOptions {
    // milliseconds before the timer fires
   interval: number;
   // if number of repeats null, undefined means it fires once
   // if number of repeats <= 0 or Infinity means repeat forever
   repeats?: number;
   // maximum number of milliseconds to randomly add
   randomRange?: number; 
   // timer callback
   fcn?: () => void;
}

type Callback = () => void;

export class Timer {

    // Constructor overload
    constructor(options: TimerOptions);
    constructor(fcn: Callback, interval: number, repeats?: boolean, numberOfRepeats?: number);
    constructor(optionsOrFcn: TimerOptions | Callback, interval?: number, repeats?: boolean, numberOfRepeats?: number) {
       //... todo implement
    }
}
```

// Example new usage
```typescript
// repeat once in 200 ms
const timerOnce = new ex.Timer({
   fcn: () => { console.log('Called Once'); },
   interval: 200
});

// repeat 3 times every 200 ms
const timerThreeTimes = new ex.Timer({
   fcn: () => { console.log('Called Three Times'); },
   interval: 200,
   repeat: 3
});

// repeat forever every 200 ms
const timerForever = new ex.Timer({
   fcn: () => { console.log('Called Forever'); },
   interval: 200,
   repeat: Infinity
});

// repeat with a random range 200 ms + (0ms to 200 ms)
const timerRandomRange = new ex.Timer({
   fcn: () => { console.log('Called every 200ms + random range'); },
   interval: 200,
   repeat: Infinity,
   randomRange: 200
});

```

**Comment by malitherl** [comment]
@eonarheim Hello, is this issue still up?

**Comment by eonarheim** [comment]
@malitherl I haven't seen any traction on the issue yet, it's yours now!
