### ISSUE TITLE
On certain mobile devices audio does not play or is very quiet 

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#397]

**Comment by eonarheim** [comment]
@alanag13 Sent some good links
here is a demo of the workaround: http://foolip.org/2014/02/10/media-playback-restrictions-in-blink/demo.html
more about it a little: http://blog.foolip.org/2014/02/10/media-playback-restrictions-in-blink/

**Comment by eonarheim** [comment]
Originally we theorized this was a difference in browser volume implementations where some browsers might interpret volume [0...1[ and other [0...100]

**Comment by eonarheim** [comment]
We need to confirm this is still bug, remote debugger to android or win phone

**Comment by kamranayub** [comment]
Tested on Galaxy S6--not a problem in Chrome. Will test on my Lumia 1020 next and an iPhone 6S.

**Comment by kamranayub** [comment]
Merging with #262 since this is not really a "quiet" issue--just need to accomodate delay on iOS.
