### ISSUE TITLE
It is implicit that we need to capture pointer when ".on('pointerdown',function()..."

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#398]
When someone uses `.on('pointerdown', function(){...})` I believe they have implicitly "opted-in" to the overhead of pointer events for that actor.

Thoughts?

**Comment by jedeen** [comment]
I agree; trying to use pointer events was slightly confusing at first, until I realized that I had to explicitly set `enableCapturePointer = true`.

**Comment by eonarheim** [comment]
We can do this by overriding the base event dispatcher behavior in `ex.Actor` like this:
```javascript
**
 * Alias for "addEventListener". You can listen for a variety of
 * events off of the engine; see the events section below for a complete list.
 * @method on
 * @param eventName {string} Name of the event to listen for
 * @param handler {event=>void} Event handler for the thrown event
 */
public on(eventName: string, handler: (event?: GameEvent) => void) {
   if (eventName && (eventName.toLowerCase() === 'pointerdown' || eventName.toLowerCase() === 'pointerdown')) {
      this.enableCapturePointer = true;
      if (eventName.toLowerCase() === 'pointermove') {
               
      }
   }
   this.eventDispatcher.subscribe(eventName, handler);
}
```

This feels a little funky to me, but it will definitely get the job done.

Also we need to deprecate `addEventListener` and `removeEventListener` in favor of the much more concise `on` and `off`

**Comment by eonarheim** [comment]
Added a potential implementation to the ld branch

**Comment by kamranayub** [comment]
This makes sense to me. I only wanted to avoid *initial* overhead, when you subscribe it makes sense to enable it for you.
