### ISSUE TITLE
Identify duplicate older methods and deprecate them

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#399]
Prime examples:
- [x] Deprecate `addEventListener` in favor of `on`
- [x] Deprecate `removeEventListener` in favor of `off`
- [x] Deprecate `triggerEvent` in favor of `emit`
- [x] Deprecate `publish` in favor of `emit`
- [x] Deprecate`addChild` in favor of `add`

**Comment by kamranayub** [comment]
Some of I've done already as part of #412.

Just add `@obsolete <reason>` and we can remove it in later versions.

**Comment by eonarheim** [comment]
Per our discussion earlier it is `@deprecated <reason>`
