### ISSUE TITLE
Investigate the Vibration API

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#408]
### Context
Utilizing the vibration API would be really cool, if it's ever formalized:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate
https://developer.mozilla.org/en-US/docs/Web/Guide/API/Vibration

### Proposal
Determine if it would be feasible (and reliable) to implement Vibration API in Excalibur.

**Comment by eonarheim** [comment]
GamePad vibration doesn't seem like it will be a thing, but we could keep this around for mobile vibration

**Comment by eonarheim** [comment]
We are reducing the scope of features we are focusing on to core engine and feature improvements. We are still open to PRs and/or plugins for non-core features.

Spoke with @jedeen offline
