### ISSUE TITLE
Configure option bag constructor overloads for Actor, Scene, Engine, ParticleEmitters, etc

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#410]
### Context
This would make configuration more terse, and easier to pass configuration around.

### Proposal
``` javascript
var game = new ex.Engine({
   width: 800,
   height: 600,
   canvasElementId: "game",
   pointerScope: ex.Input.PointerScope.Document
});

var actor = new ex.Actor({
   x: 50,
   y: 60,
   width: 10,
   height: 10,
   scale: new ex.Point(2,2),
   ay; 10,
   texture: new ex.Texture('myimage.png')   
});
```

**Comment by kamranayub** [comment]
We have a new utility to help, `ex.Util.extend` which you can do like:

    options = Util.extend({}, MyClass._DefaultOptions, options);

Which will merge defaults with provided options to override.

**Comment by eonarheim** [comment]
Additionally, we should have all the flag configurations like `backgroundColor` available in the options back so we don't have to do this
```typescript
var game = new ex.Engine({
    width: 600,
    height: 400,
    backgroundColor: ex.Color.Azure
});
```

instead of this
```typescript
var game = new ex.Engine({
    width: 600,
    height: 400
});

game.backgroundColor = ex.Color.Azure;
```

**Comment by eonarheim** [comment]
A nice way to do this might be to create an interface for each object that contains each public property for a Type, and the ITypeOptions on each object constructor implement that interface.
