### ISSUE TITLE
Scene.onActivate() is called before Scene.onInitialize() 

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#418]
This is especially problematic if you have an event listener defined in onActivate() that performs logic on the scene's child actors in onInitialize(). The first time the scene is visited, those actors haven't been instantiated yet.

**Comment by kamranayub** [comment]
This is a bug, initialize should be called first, I even say it in the new docs.

**Comment by kamranayub** [comment]
I can tackle this today
