### ISSUE TITLE
Replace event classes with interfaces

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#432]
Does it make sense to keep using a `class` for events? Wouldn't it be lighter weight to just define interfaces and then pass JSON objects? Is it the same weight either way?

```
interface UpdateEvent {
  delta: number;
}

this.emit<UpdateEvent>("update", { delta: xxx });
this.on<UpdateEvent>("update", (ev) => { });
```

**Comment by eonarheim** [comment]
Possibly, we still keep the strong typing. I don't think we ever have any implementation details on our event objects.

**Comment by kamranayub** [comment]
Ah that's true... maybe it's better to keep it class-based then.

**Comment by eonarheim** [comment]
Although event objects are probably a good candidate for object pooling, since so many of them are created...

**Comment by kamranayub** [comment]
Yes, I'd agree with that. All the cool kids are using factories nowadays. It's sub-optimal in TS but might be a necessity.

**Comment by eonarheim** [comment]
Issue not needed anymore
