### ISSUE TITLE
Sprite width and height don't take scaling into account

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#437]
If an actor's sprite is scaled up or down in size, the `width` and `height` of the sprite remain unchanged. Perhaps we need additional properties to maintain the current (modified) height and width of a sprite.

**Comment by eonarheim** [comment]
We probably should make 2 new properties to encode the actual width and height of the original image in pixels. The html5 apis seem to favor the terms `naturalWidth` and `naturalHeight`. Then `width` and `height` can the be calculated values taking scale into account.
