### ISSUE TITLE
Actor-specific debug draw

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#463]
The ex.Debugger should allow you to enable debug drawing on specific actors, based on their id.

**Comment by eonarheim** [comment]
All actors have an `.id` property now, it might also be useful to use that to enable actor specific debug draw that way.

Maybe something like this?
```javascript
ex.Debugger.includeActorIds = [1,54, 16];
ex.Debugger.excludeActorIds = [2, 3, 29]
```
or some helpers
```javascript
ex.Debugger.include(actor1);
ex.Debugger.include([actor5, actor6]);
ex.Debugger.exclude(actor3);
```

**Comment by eonarheim** [comment]
Another idea is to enable an interactive mode with the debugger, highlighting actors when you mouse over them. This could allow you to set properties in a pop-up of some kind.

**Comment by eonarheim** [comment]
Implemented as part of the new DebugSystem!
