### ISSUE TITLE
Unit circle drawing for debug mode

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#467]
Ability to toggle a canvas unit circle, as well as a line representing the actor's current rotation.

**Comment by eonarheim** [comment]
![image](https://cloud.githubusercontent.com/assets/612071/9157824/7af8c4bc-3ed1-11e5-9e0c-9440d23bafb2.png)

Currently this is what I have implemented, it currently is a little noisy but if it is fine then we can close this. Once #497 is completed then I think this will be better.
