### ISSUE TITLE
Default fontFamily for Label doesn't work with custom FontSize/FontUnit

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#471]
## Reproduce

```js
var lbl = new Label('x');
lbl.fontSize = 24;
lbl.fontUnit = FontUnit.Px;
```

Observe font size is still 10px, the default size.

## Issue

Because default `fontFamily` is `10px sans-serif`, the formatted string that gets built in `_fontDraw` is:

    "24px 10px sans-serif"

To fix, we just need to set default `fontSize` and remove `10px` from the `fontFamily` property in constructor.

**Comment by kamranayub** [comment]
You can do this currently, but there's a slight bug. Changing issue to reflect.
