### ISSUE TITLE
Excalibur crashes hard if you call .clone() after calling .asSprite() in a constructor

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#474]
Repro

```typescript
var sprite = Resources.MyTexture.asSprite().clone()
```

Work-around is to place this type of thing in the onInitialize()

**Comment by eonarheim** [comment]
I believe this is due to some pixel data not being loaded... we probably need to make .clone() tolerant of situations like this

**Comment by alanag13** [comment]
I was unable to reproduce this given the repro instructions. I tested doing this in Hexshaper (Health.ts)
 ```
     constructor(x: number, y: number) {
      super(x, y, HealthStat.width, HealthStat.height);
      this.anchor.setTo(0, 0); 
      var spriteTest = Resources.Heart.asSprite().clone();
   }
```
and also Bullet (since these get made constantly during the game and not just on game init:
```
   constructor() {
      super(0, 0, 3, 3, ex.Color.Red);
      this.collisionType = ex.CollisionType.Passive;
      this.reset();
      this.rx = Config.bullets.rotation;

      this.on('collision', this._collision);
      this.on('postdraw', this.postdraw); 
      var _spriteTest = Resources.Heart.asSprite().clone();     
   }
```
but everything seemed to behave as expected in both cases.

**Comment by kamranayub** [comment]
So we can close for now until it comes up again (if ever)?
