### ISSUE TITLE
Build a Perlin noise generator for Excalibur

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#491]
Perlin noise is useful for procedural generation.

**Comment by kamranayub** [comment]
http://lencinhaus.github.io/canvas-noise/#seed=noize&color=greyscale&independent=false&gradientStart=ff0000&gradientEnd=00ff00&noiseFunction=perlin_improved&smoothing=quintic&scale=50&size=256&octaves=1&persistence=0.5&lacunarity=2&octaveFunction=none&customOctaveFunction=return+n%3B&sumFunction=none&customSumFunction=return+n%3B&sineFrequencyCoeff=1&modularAmplitude=5
