### ISSUE TITLE
Add basic stuff to improve SEO and/or clickthroughs on social media

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/Excalibur#492]
add open graph meta tags to the website:
http://ogp.me/

add meta description tags for customized search engine description
create google webmaster tools account and add an xml sitemap to help search indexing

see if we can get on these lists?
https://html5gameengine.com/
https://developer.mozilla.org/en-US/docs/Games/Tools/Engines_and_tools

**Comment by kamranayub** [comment]
is this for excaliburjs/excaliburjs.github.io?
