### ISSUE TITLE
Child Actors should participate in collisions

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#496]
### Context
Child actors currently do not participate in collisions with other Actors, which is (often) unexpected behavior.

### Proposal
Add the ability to enable/disable collisions for child actors.

**Comment by eonarheim** [comment]
Agreed, I think this should be fairly simple to implement. Right now only siblings participate.

I think there are 3 things needed to make this work.

* Bounding boxes are returned in world coords always so that is good,
```typescript
 /**
     * Returns the actor's [[BoundingBox]] calculated for this instant.
     */
    public getBounds() {
       var anchor = this._getCalculatedAnchor();
       return new BoundingBox(this.getWorldX() - anchor.x,
          this.getWorldY() - anchor.y,
          this.getWorldX() + this.getWidth() - anchor.x,
          this.getWorldY() + this.getHeight() - anchor.y);
    }
```

* When child actors are added to the parent, then must also be added to the collision resolver on the scene. Something like this, but nicer
```typescript
/**
     * Adds a child actor to this actor. All movement of the child actor will be
     * relative to the parent actor. Meaning if the parent moves the child will
     * move with it.
     * @param actor The child actor to add
     */
    public addChild(actor: Actor) {
       actor.collisionType = CollisionType.PreventCollision;
       if (ex.Util.addItemToArray(actor, this.children)) {
          actor.parent = this;
       }
       if (this.scene) {
           // add the child to the collision resolver, something more elegant than this
           this.scene._collisionResolver.register(actor);
       } else {
           // queue up children to add to the collision resolver when the parent is added
       } 

    }
```
* The scene update logic will need to change to enumerate the entire graph, not just siblings
```typescript
 // Run collision resolution strategy
 if (this._collisionResolver) {
     this._collisionResolver.update(this.children); // this.children is not right, we will need to get the entire graph
     this._collisionResolver.evaluate(this.children);
 }
```

**Comment by eonarheim** [comment]
There is also some stuff that we will need to do when evaluating collision pairs with actors in world and relative space. Shouldn't be too difficult... basically need to calculate the new relative position after collisions

**Comment by kamranayub** [comment]
Because children will probably be within the BB of the parent, maybe provide a way to "ignore" that.

**Comment by jedeen** [comment]
Closed because child actors will be removed in a future release.
