### ISSUE TITLE
it is possible to add an actor to a scene multiple times

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#504]
![image](https://cloud.githubusercontent.com/assets/675840/9346951/bf210dd4-45e8-11e5-89a7-2639dcf655b5.png)

**Comment by kamranayub** [comment]
Maybe use ID to determine whether or not actor was added? or byref

**Comment by eonarheim** [comment]
@kamranayub I think either would work, byref is probably more bullet proof since technically you could update the id on the actor and break this
