### ISSUE TITLE
debug draw bounding boxes are not properly aligned for child actors

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#505]
In the image below, the red square is a child actor of the white square.
![image](https://cloud.githubusercontent.com/assets/675840/9347064/62b8b0a4-45ea-11e5-9d5a-9e4226e63d52.png)

**Comment by eonarheim** [comment]
I don't think it has one, the coordinate test might be good to use for this issue

**Comment by kamranayub** [comment]
Oh sure, yeah I can test it. I have a feeling this is fixed.

**Comment by kamranayub** [comment]
Coordinates test is too small, I've created a new visual debug test which shows the issue clearly:

![image](https://cloud.githubusercontent.com/assets/563819/18226775/b7bfecac-71d6-11e6-9337-6620d8a99b04.png)

**Comment by kamranayub** [comment]
The issue is simply that we fixed child actor world coords, and the debug draw was trying to compensate from previous poor world coordinate calculation.

**Comment by kamranayub** [comment]
Actually, it was worse--`getHeight()` and `getWidth()` did not take into account parent scaling (`getGlobalScale()`). I've fixed it and magically now everything works :+1:
