### ISSUE TITLE
freezeframe is never set to last animation frame

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#506]
![door_animation](https://cloud.githubusercontent.com/assets/675840/9372475/7e657390-46a4-11e5-935d-149201c8bb93.gif)

After the animation plays, the current drawing for that actor disappears. The same behavior occurs for `getAnimationForAll()`,  `getAnimationBetween`, and `getAnimationByIndices()`. In fact, it does not appear that `freezeframe` is ever set other than when it is initialized as '-1'. According to the documentation, the default `freezeframe` for an animation should be the last frame of the animation.

The current workaround is to manually set the `freezeframe` for each animation.

**Comment by eonarheim** [comment]
@jedeen Would you always want animations to default to stop on the last frame and freeze frame? I do agree that this does not match the documentation here: http://excaliburjs.com/docs/api/edge/classes/ex.animation.html#freezeframe, but I'm questioning that behavior.

For instance what if you had animations that were explosions or some other special effect and you wanted them to play once and complete with nothing being drawn. Or would you always expect the freeze frame on the last frame and include and empty frame at the end of effect related animations?

@jedeen On that same note, should animations also loop by default as well?

**Comment by jedeen** [comment]
@eonarheim I don't think that looping by default is expected behavior. In my opinion, the method we currently have described in the documentation is the most straightforward of our options.
