### ISSUE TITLE
utility method to calculate the distance between two points

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#517]
`ex.Util.distance(point1: Point, point2: Point)`

**Comment by eonarheim** [comment]
There is a method off of vectors that calculates the distance between them. `ex.Vector.distance`  http://excaliburjs.com/docs/api/edge/classes/ex.vector.html#distance

Ideally there would be only 1 way to do this... Point is the superclass of Vector, maybe these methods need to move up the hierarchy and not live on vector? Or potentially just kill the point or vector type and reconcile them into one?

@kamranayub @alanag13 What do you guys think?

**Comment by kamranayub** [comment]
What if we made a static `ex.Point.distance(p1, p2)` as a static helper?

**Comment by eonarheim** [comment]
@kamranayub YES

**Comment by Crizzooo** [comment]
I was looking into this, but I'm unable to track down that Point class other than some tests in the sandbox?

Does it still exist? I dont see Vector being an extension of Point.

Other than placing the method on Point as a class method, could this just be a Utility function that accepts two points (or vectors) and returns their distance?

**Comment by kamranayub** [comment]
I think this is implemented as an instance member on Vector (
https://excaliburjs.com/docs/api/edge/classes/_algebra_.vector.html#distance),
we should just make a static method that accepts two Vectors and call it a
day, I don't think it really belongs in Util as originally proposed (but we
can discuss it).

**Comment by kamranayub** [comment]
Oh, and yes, we removed Point in favor of Vectors.
