### ISSUE TITLE
Actors can be present in multiple scenes, but only know about the most recent one

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#526]
### Context
Currently, when an Actor is added to a Scene, `Actor.scene` is set, and the Actor is added to the  `Scene.children` array. If you add that Actor to another scene, it's `scene` property is overwritten, but the first Scene still has it in its array of children.

### Proposal
Only one Scene can be active at a time, so an Actor should probably, by default, only be present in one Scene at a time.

**Comment by eonarheim** [comment]
We've seen recently that it's useful for actors to be potentially be in multiple scenes. Will close for now
