### ISSUE TITLE
UIActors should keep track of all Scenes they are present in

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#527]
### Context
There is a potential case for UIActors to be present in multiple scenes for setup simplicity. 

### Proposal
Add functionality to UIActors so that they are aware of every Scene that they are present in. This will override the default behavior from #526 and allow UIActors to keep track of all the Scenes they are in.

**Comment by eonarheim** [comment]
Closing allowing actors to be in multiple scenes
