### ISSUE TITLE
Return a new Promise in Promise callback

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#532]
### Context
In Q there is the option of returning a promise to influence the promise chain. Excalibur should also support this. 

> If you return a promise in a handler, outputPromise will “become” that promise. Being able to become a new promise is useful for managing delays, combining results, or recovering from errors.

Right now if the first promise in chain is resolved it will fire all of the "then" callbacks in serial order regardless if they return a promise or need to wait.

**Comment by kamranayub** [comment]
Use case:

```js
public load(): Promise<ITiledMap> {
         var p = new Promise<ITiledMap>();

         super.load().then(map => {

            var promises: Promise<HTMLImageElement>[] = [];

            // retrieve images from tilesets and create textures
            this.data.tilesets.forEach(ts => {
               var tx = new ex.Texture(this.imagePathAccessor(ts.image, ts));
               ts.imageTexture = tx;
               promises.push(tx.load());

               ex.Logger.getInstance().debug("[Tiled] Loading associated tileset: " + ts.image);
            });

            ex.Promise.join.apply(this, promises).then(() => {
               p.resolve(map);
            }, (value?: any) => {
               p.reject(value);
            });
         });

         return p;
      }
```

**Comment by eonarheim** [comment]
#936 Should just include the ES6 Promise polyfill as the implementation, and maintain the existing ex api

**Comment by eonarheim** [comment]
Closing in favor of native promise
