### ISSUE TITLE
Add "autoscroll" camera behavior

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#534]
I'm thinking of a camera feature similar to the mario 3 airship levels where the camera inches forward along a path and the edges of the screen are walls

```typescript

export interface PathOptions {
   path: Vector[];
   speed: number;
}

export class StrategyContainer {
...
    followPath(options: PathOptions) {
          // TODO implement strategy
    }
...
}

// usage

const engine = new ex.Engine(...)
const currentCamera = engine.currentScene.camera;

// camera will follow the vector path at a particular speed
currentCamera.strategy.followPath({
   path: [ new ex.Vector(0, 0), new ex.Vector(100, 0), new ex.Vector(100, 100) ],
   speed: 100 // pixels per second
});

```

**Comment by MaanasArora** [comment]
Can I work on this feature?

**Comment by eonarheim** [comment]
@MaanasArora all yours! I've added the community in progress label.

Take a look at the other existing `CameraStrategy` implementations for an example of how to proceed.

**Comment by MaanasArora** [comment]
I'm sorry; could I have a bit of clarification as to what is exactly required? By inching forward on a path, do you mean an arbitrary vector path? What do you mean by the edges of the screen? I tried researching the relevant mario levels but couldn't pinpoint the behavior you mentioned.

**Comment by eonarheim** [comment]
Hi @MaanasArora Apologies the issue is not written very clearly. This issue doesn't have a proposed api either.

The idea behind this issue is to create a new `CameraStrategy` that will allow cameras to follow a pre-set path (using vectors) at some velocity. Similar to some of the games on this list https://tvtropes.org/pmwiki/pmwiki.php/Main/AutoScrollingLevel?from=Main.FixedScrollingLevel

Definitely open to ideas or suggestions, perhaps something like this?

```typescript

export interface PathOptions {
   path: Vector[];
   speed: number;
}

export class StrategyContainer {
...
    followPath(options: PathOptions) {
          // TODO implement strategy
    }
...
}

// usage

const engine = new ex.Engine(...)
const currentCamera = engine.currentScene.camera;

// camera will follow the vector path at a particular speed
currentCamera.strategy.followPath({
   path: [ new ex.Vector(0, 0), new ex.Vector(100, 0), new ex.Vector(100, 100) ],
   speed: 100 // pixels per second
});

```

It may be interesting to come up with a way to allow variable speed between sections of the path.

**Comment by eonarheim** [comment]
It may be nice to know when the camera is done following the path and return a promise that resolves when `followPath` is complete
