### ISSUE TITLE
Add better random utilities for Excalibur

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#538]
It is pretty well documented that V8 and other browser default random utilities are pretty lacking
https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d#.y6mxmug2a

With this in mind, we should improve the existing random utilities in Excalibur. I propose that we make a `ex.Random` module for this purpose.
- [ ] Update random int to use rejection sampling (outlined in the link above) over the current "multiply-and-floor" method
- [x] Update random in range to do the same
- [x] ~~Update random strategies to use a better PRNG generator than `Math.random()` maybe using `window.crypto` that has reasonable browser compatability http://caniuse.com/#feat=cryptography~~ 
- [x] Add random boolean helper (ex.Random.bool()) that will return true or false (coin flip)
- [x] Add Mersenne Twister "seeded" random generation: https://github.com/pigulla/mersennetwister

Related to #396 and #491 we should include these in the `ex.Random` module when completed

**Comment by eonarheim** [comment]
@kamranayub Do you really think we need to use rejection sampling is needed in our implementation?

**Comment by kamranayub** [comment]
If it's easy otherwise don't think it's as important with MT implementation
