### ISSUE TITLE
Sprites and Actors stop drawing at certain negative zoom levels

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#539]
I think this might have something to do with offscreen culling weirdness
![negativezoom gif](https://cloud.githubusercontent.com/assets/612071/11320074/f0626360-9053-11e5-8926-5cb21e51a1c6.gif)

**Comment by eonarheim** [comment]
Does negative zoom even make sense?

**Comment by kamranayub** [comment]
@eonarheim did we end up saying we should disallow negative zoom? or that in some cases it might make sense?
