### ISSUE TITLE
Add way to do "Time" scaling

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#543]
This would be a useful feature if you wanted to control the speed of time in excalibur. With something like this you could lie to the underlying engine pieces and create "slow motion" or "super speed" effects.

Perhaps something like:
```typescript
engine.timeScale = 1.0; // 1 ms real time = 1 ms simulation time
engine.timeScale = 0.5; // 1 ms real time = .5 ms simulation time slowing things down
engine.timeScale = 1.5; // 1 ms real time = 1.5 ms simulation time speeding things up
```

**Comment by eonarheim** [comment]
@agrgic16 I'd leave the > 200 ms part alone, because it solves some stability issues.
![image](https://cloud.githubusercontent.com/assets/612071/16364714/9b13328e-3bb3-11e6-9f1c-1ef95015984d.png)

Also we could extract the Date.now() call and make it injectable as a separate "clock" implementation. See this issue #577 which talks about extracting out the timing implementation into a more general and mockable time keeper.

**Comment by kamranayub** [comment]
Hey @agrgic16 do you want one of us to finish this off this month or do you think you'll have time before end of Sep?
