### ISSUE TITLE
Rename UIActor to something less confusing

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#548]
### Context
The name `UIActor` causes confusion about the purpose and functionality of the class.

### Proposal
Some suggestions have been 
- ScreenElement
- ScreenComponent
- etc

**Comment by alanag13** [comment]
Is there a term that fits nicely into the actor/scene analogy here? Prop? Backdrop?

**Comment by kamranayub** [comment]
- ScreenActor
- FixedActor
- StaticActor

I think since it still inherits from Actor that maybe Actor should still be part of the name, yes?

**Comment by eonarheim** [comment]
I'm partial to the "Screen" aspect of the name. ScreenActor could be a good name.

**Comment by alanag13** [comment]
I'm not sure that's less confusing since virtually all actors appear on the screen. ScreenActor seems equally as confusing as UIActor to me, and I think its because of the "Actor" portion of the name. I also dont like fixed/static etc because that might imply an inability to change anything about it. Of the original proposed list ScreenElement seems thr best to me. It communicates its purpose while making it noticably different from an Actor.

**Comment by eonarheim** [comment]
Yeah, I'll agree with that. The "Actor" portion does confuse the purpose of the "UIActor" and that is to be a fixed thing on the screen for UI purposes. 

ScreenElement is less ambiguous and does make more sense, and it would fit into a possibly UI Elements design metaphor. We could also add DomElement wrappers in that as well...

**Comment by kamranayub** [comment]
:+1:

**Comment by eonarheim** [comment]
@pathurs had a great name suggestion here, I really like the name `ScreenElement` @excaliburjs/core-contributors  thoughts?

> Element - Most base class, can be created, destroyed, has a unique ID
ScreenElement extends Element - The screen element has a location on the screen, and some kind of display (text or image)
ActorElement extends ScreenElement - The actor element is essentially what the actor is, except stripped down to be more basic, having to add "modules" or something to give it physics, sound, etc

**Comment by DProBoy** [comment]
How about Slate or Drawable ? ScreenElement also sounds good...

**Comment by eonarheim** [comment]
@DProBoy I'm leaning towards `ScreenElement` as the desired name

**Comment by jpninanjohn** [comment]
Is this still an issue?

**Comment by eonarheim** [comment]
@jpninanjohn Definitely all yours if you want it!

`ScreenElement` is the new desired name. In addition please locate and update docs to use the new name.

**Comment by jpninanjohn** [comment]
Ill take it up.
