### ISSUE TITLE
Implement Robust Physics System for Excalibur

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#557]
Excalibur needs a good default story for physics games. 

A simple impulse based rigid body system can be implemented with basic primitives
* Edges
* Circles
* Convex Polygons

A few requirements for this issue to be closed
- [x] Some enhancements to ex.Algebra need to be made
- [x] Physics body for hold physical properties need to be implemented #472 
- [x] Collision shape primitives Edges, Circle, Convex Polygons need to be implemented
- [ ] Collision shape primitives need to be tested
- [x] Keep the old "Box" physics system and be able to switch between RigidBody and Box

**Comment by eonarheim** [comment]
@kamranayub @jedeen Should we split this into separate issues? or does having the different check boxes suffice here

**Comment by eonarheim** [comment]
The one thing I'm worried about is the "long lived" branch problem

**Comment by jedeen** [comment]
All of these changes are a direct result of the physics system, so I don't see any benefit that could be gained by splitting this issue into many separate issues, unless some of these check boxes are monumental tasks on their own.

Committing them independently as you go (and as appropriate) is a good way to solve the long-running branch problem. You could even use the same branch, if you like, and merge it back in with each new set of changes.

**Comment by kamranayub** [comment]
Agreed, it's a coupled feature, better to just finish it and merge as you
go to avoid headaches later.
