### ISSUE TITLE
Allow different initial shapes besides rectangle

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#562]
Useful for initial placeholder actors. If I want to draw a planet, it'd be nice to let Excalibur do it for me vs. me writing custom canvas code. Also, you can't add an initial color because then Excalibur will draw the rectangle if you call `super.draw` so you have to start with a null color.

**Bonus:** Changes shape of bounding box too.

**Proposed Actor API**

``` ts
// default
protected defaultDraw(ctx, delta) {
  // draw rect
}

// override
protected defaultDraw(ctx, delta) {
  // custom drawing of shape or default draw
  ex.Drawing.drawCircle(ctx, 5, this.color);
  ex.Drawing.drawEllipse(ctx, 5, 6, this.color);
}
```

**Circle**

Assumes width and height are equal (use width / 2)

``` ts
ctx.beginPath();
ctx.arc(0, 0, this.getWidth() / 2, 0, Math.PI * 2);
ctx.fillStyle = this.color.toString();
ctx.closePath();
ctx.fill();
```

**Ellipse**

Uses width / 2 and height / 2
- Scaling circle: http://stackoverflow.com/a/8372834
- [`ellipse()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse) method

**Comment by eonarheim** [comment]
Per our discussion today, we should add a `defaultDraw` constructor override on actor that when specified will do a custom draw in the normal actor pipeline. We could add some canvas extensions to help `canvas.circle (...)` or `canvas.ellipse(...)`

**Comment by kamranayub** [comment]
We could do `protected` and then allow people to override. Also not sure if it should be `drawDefault` or `defaultDraw` since `drawDefault` might be more discoverable being next to `draw`.

**Comment by PurityLake** [comment]
This task still up for grabs? Wanna get back into open source

**Comment by jedeen** [comment]
Yep! Take a look at our updated [contributing guide](https://github.com/excaliburjs/Excalibur/blob/master/.github/CONTRIBUTING.md), and go ahead! 

I'll assign this issue to myself for tracking. Let us know if you have any questions!

**Comment by kamranayub** [comment]
Yep, it's a good idea to open up a work in progress PR so we can keep up
with what you're working on and discuss any questions or design ideas you
have!

**Comment by mkorevec** [comment]
Hiya,

This issue has been created more than 2 years ago, I am sure the code has changed a lot since then, you can as far as I see create Actors with a default color now.

I might also be missing the point. Would love to explore this task a bit more as I see the person before me Asked and then Abandoned the task :)

Keep me posted will try to get myself a bit more familiar with code and hopefully start tackling this :)

P.S. New to open source so any tips are welcome!

**Comment by eonarheim** [comment]
Hi Marko,

Sorry I missed this comment until now.

Certainly! If you'd like to explore this go for it. I think a circle would
be a useful shape, then maybe any arbitrary polygon?

My open source tip of the day is "over communication" :) feel free to ask
questions or throw out possible ideas!

**Comment by vipulbhj** [comment]
Is this still open, can I try it??

**Comment by eonarheim** [comment]
Go for it!

Open a PR early and we can discuss designs you might have

**Comment by jkasun** [comment]
@vipulbhj are you going to fix this, Can I try?

**Comment by eonarheim** [comment]
@jkasun Certainly! @PurityLake @vipulbhj let us know if you have any insights to share

Please let us know what you have in mind with a PR with your design

**Comment by jkasun** [comment]
@eonarheim I have never done a open source contribution before, I will go thorough the code and update you, if I can do this.

**Comment by eonarheim** [comment]
This is now supported with different collider shapes
