### ISSUE TITLE
Add `fontStyle` to Label

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#563]
Missing font style: bold, italic, etc.

**Comment by eonarheim** [comment]
Label tests should use the new image testing api

**Comment by eonarheim** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-style there isn't a bold font style in CSS. Should we add an additional font style in Excalibur? Or would this be confusing to people coming from a CSS background?

```typescript
   /**
    * Enum representing the different possible font styles
    */
   export enum FontStyle {
      Normal,
      Italic,
      Oblique,
      Bold
   }

```

**Comment by kamranayub** [comment]
Well in CSS it's `font-weight` because a font can be both bold and italic. If we added it to our FontStyle, we would need to treat it as a flag enum. Instead maybe we can just add a property: `bold` boolean.
