### ISSUE TITLE
Extract and swap out the Excalibur clock implementation with window.performance

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#577]
### Context
There is a more precise timer now generally available to javascript that is better than `Date.now()`.
http://caniuse.com/#search=performance

`window.performance()` provides sub-millisecond accuracy and would improve our fps and timing calculations.
### Proposal

Additionally, we really should abstract our clock implementation into a separate type to make the engine more testable. Perhaps something like this?

``` typescript
class Clock implements IClock {
     constructor(){...}
     // calls the mainloop function with a specific delta
     tick(delta){...}
     start(mainloop: function)
     stop()
}
```

**Comment by kamranayub** [comment]
Agreed

**Comment by eonarheim** [comment]
Good article on this https://developers.google.com/web/updates/2012/08/When-milliseconds-are-not-enough-performance-now

**Comment by eonarheim** [comment]
MDN docs https://developer.mozilla.org/en-US/docs/Web/API/Performance/now
