### ISSUE TITLE
Overriding onInitialize, onActivate, onEventType is not safe

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/Excalibur#582]
### Context

Currently we have "eventish" like method overrides like `onInitialize` and `onActivate` that don't have a corresponding `.on('initialize')` or `.on('activate')` event handlers and vice versa, this is not consistent. Additionally it is often not safe to override `onInitialize` implementations without the base implementations.

For example, when overriding OnInitialize, currently you have to manually call super.OnInitialize to get the default UIActor OnInitialize to trigger.

### Proposal

Follow .NET's pattern and create `initialize` implementation that does the base work, and calls the overridable `onInitialize` when complete.

Also for every `onEventType` method, have a corresponding `on('eventtype')` and vice versa.

**Comment by eonarheim** [comment]
Potentially we could also add some generic interfaces to signal to the user which onEventTypes are available on which objects.
