### ISSUE TITLE
Actors added from a timer update do not have their update called that frame

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#584]
To reproduce:
1. Create a timer
2. In the timer callback, add an actor to the game
3. In that actor's draw event, write code that depends on an initialized variable (from OnInitialize)
4. Observe the draw event throws an error because the variable is undefined as OnInitialize hasn't been called

This is because timers are processed last in the update cycle, so any new actors are not updated that frame.

**Comment by eonarheim** [comment]
Maybe timers need to be the first thing to execute in the mainloop?
