### ISSUE TITLE
Excalibur allows duplicates of the same actor to be added more than once

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#587]
This causes hard to track down bugs and bizarre behavior in games. Excalibur should not let you do this it should toss a warning and refuse to re-add it.

**Comment by eonarheim** [comment]
We need a test to confirm this is still a bug

**Comment by kamranayub** [comment]
@jedeen fixed this in https://github.com/excaliburjs/Excalibur/commit/48ad1ef92e518385f815d299b9bf8bdd35bb6daa
