### ISSUE TITLE
Refactor actor to extract reusable behaviors 

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#592]
### Context 
Currently `ex.Actor` is a god class, and it has a lot of different behaviors that could be shared with other components like `ex.Camera`.

### Proposal
Refactor `Actor` to extract reusable behaviors, perhaps using a decorator pattern?

Additionally, extracting these behaviors would make things much easier to test.

**Comment by eonarheim** [comment]
Actors should be build up with things that are needed, like movement, drawing, physics, controller input and other behaviors

**Comment by eonarheim** [comment]
Maybe similar to how Angular2 is organized

**Comment by pathurs** [comment]
In many engines (Software and game), the most basic "thing" is something that only exists, has an ID, and can be destroyed, nothing more.

Perhaps there should be a refactor of the inheritance of Excalibur, beginning with a "Element" (Or whatever you want to name it), and then "Actor" will derive from it.

For example, in Unity you have a [Object](https://docs.unity3d.com/ScriptReference/Object.html) (very simple) and then [GameObject](https://docs.unity3d.com/ScriptReference/GameObject.html) which is still very basic.

Perhaps this could work (names are just ideas):

`Element` - Most base class, can be created, destroyed, has a unique ID
`ScreenElement extends Element` - The screen element has a location on the screen, and some kind of display (text or image)
`ActorElement extends ScreenElement` - The actor element is essentially what the actor is, except stripped down to be more basic, having to add "modules" or something to give it physics, sound, etc

This could be merged with #548 to become a full refactor release?

@eonarheim  @kamranayub  fyi

**Comment by eonarheim** [comment]
Closing in favor of the ECS milestone planning which will make this obsolete
