### ISSUE TITLE
Refactor Resources to be a bit more easily extensible/composable

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#594]
#### Context

When trying to extend Resource, Excalibur has mixed implementations--sounds totally override the base `load` function, textures call the super and do almost the same thing as the base implementation, and the base resource always assumes you want to load data via XHR which is not very testable.

For example, now that you can set data without XHR, it's awkward to see this:

``` ts
var resource = new ex.Resource('path/to/image.png', 'image/png', true);
resource.setData(myblob);
```

The constructor arguments don't even apply, since XHR isn't used to load. Further, since by default Resource create a blob URL, to set binary data you'd have to do:

``` ts
var resource = new ex.Resource('path/to/bin.bin', 'application/octet-binary');
resource.processData = data => data; // pass through
resource.setData(binaryData);
```
#### Proposal
1. Refactor base `Resource` to not depend on XHR or URL blob creation (default `load` immediately resolves with data)
2. Extend base with a `HttpResource` that implements load via XHR and has appropriate hooks for derived classes
3. Refactor Sound, Texture, and FallbackAudio to accommodate change

Now above examples become:

``` ts
var resource = new ex.Resource();
resource.setData(myblob);
```

and

``` ts
var resource = new ex.Resource();
resource.setData(binaryData);
```

Then to do a XHR request:

``` ts
var resource = new ex.HttpResource('path/to/file.png', 'content-type', true);
resource.load() // promise
```

**Comment by kamranayub** [comment]
This is now in a better state to address after cleaning up for excalibur-pack and sound resources.

**Comment by eonarheim** [comment]
This is no longer an issue
