### ISSUE TITLE
Need a better way to keep track of local and global coordinates for actors

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#60]
When actors are rotated, translated, or scaled, it becomes difficult to calculate the local/or global coordinates. The engine should reason about these for us, so that we do not need to apply trigonometry to figure out the coordinates.

**Comment by eonarheim** [comment]
Let's close this when we have written some tests around it

**Comment by kamranayub** [comment]
Almost done, struggling a little with child/grandchild rotation/scaling in world coordinates.
