### ISSUE TITLE
Remove deprecated ActionQueue off of actor in favor of the ActionContext

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#603]
#### Context

We have some code duplication that has caused some issues in actor, and we decided a while ago to decouple `ActionQueue` from actor with the `ActionContext`

However, we still have the `ActionQueue` implementation on `Actor`

```typescript
  /// delete this line and any code that breaks
  public actionQueue: ex.Internal.Actions.ActionQueue; 
  // this is what we want going forward
  public actions: ActionContext = new ActionContext(this);
```
#### Proposal

We should delete this `ActionQueue` code and make sure all of our tests pass, and samples are updated and working with the new `ActionContext`

**Comment by jedeen** [comment]
Closed by this commit: [ef36d32cb3b9922c7a6c3fe1cc6e98c23c8461a6] (https://github.com/excaliburjs/Excalibur/commit/ef36d32cb3b9922c7a6c3fe1cc6e98c23c8461a6)
