### ISSUE TITLE
Extract examples from comment documentation into separate files

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#607]
#### Context

Due to changes in TypeDoc, code examples can now be stored in separate files and pulled in as needed. This will make samples more manageable and let us track changes to them more easily.
#### Proposal

We should pull all of our documentation code examples out into separate files as per the new TypeDoc guidelines.

**Comment by kamranayub** [comment]
This should not be done until #606 is done, otherwise it'll be merge conflict city

**Comment by kamranayub** [comment]
Works.

![image](https://cloud.githubusercontent.com/assets/563819/20613178/fb116418-b286-11e6-9fcd-a4ce5b76524d.png)

![image](https://cloud.githubusercontent.com/assets/563819/20613179/01d3c084-b287-11e6-9a19-9b0b2af4b0b4.png)

You can also link to images via "media://" links and media folder but I think when we migrate to RTD it'll be better anyway.
