### ISSUE TITLE
Allow simple overriding of pipeline in Actors

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#622]
### Context

Currently the Actor constructor puts together a default pipeline. To enhance discoverability and extensibility, I think it would be great to allow people to override a global pipeline builder and individual actor pipelines.
### Proposal

Something like:

``` ts
protected initializePipeline(): void {
  // base?
  super.initializePipeline();

  // customize pipeline
}
```

We could also have a pipeline builder but that may be overkill.

**Comment by eonarheim** [comment]
Closing in favor of the upcoming ECS milestone planning that will make this obsolete
