### ISSUE TITLE
Speed up Excalibur builds

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#623]
### Context

It takes a long time to do a full build of excalibur, with all the tests, samples, dists, coverage, etc. It would be nice if the feedback loop between making a change and validating it were shorter. 
- This would improve our development speed
- Ease development friction
- Speed up our CI builds
### Proposal
- Our build is setup to be synchronous on every step, perhaps things could be parallelized or removed.
- Another build tool like gulp may drastically improve build times
- Investigate how other typescript projects are handling timely builds like [tslint](https://github.com/palantir/tslint) for example
- Time the current build and any proposed improvements to see if there is value

**Comment by kamranayub** [comment]
As a stopgap, we have `grunt compile` to a quick compile step during development. Then you can run `grunt` at the end. In addition, the TSLint for VSCode extension catches issues before compiling.
