### ISSUE TITLE
Remove code marked as obsolete for 0.7 release

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#625]
#### Context
We have lots of old cruft that has been obsoleted, lets delete it. Especially in `Actor`

#### Proposal
Delete it!

**Comment by kamranayub** [comment]
I agree, because we are pre-1.0, the 0.x major version is technically
considered unstable. Deprecating API methods is a courtesy at this point.
After 10, we'll need to have planned deprecations.
