### ISSUE TITLE
actor.rotateTo and actor.repeatForever behave unexpectedly 

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#635]
#### Steps to Reproduce

In the physics visual test (in /sandbox/web/tests/physics/physics.ts) if you run the following code

``` typescript
edge.actions.rotateTo(Math.PI/4, .5, ex.RotationType.ShortestPath).rotateTo(-Math.PI/4, .5, ex.RotationType.ShortestPath).repeatForever();
```

The actor will rotate back and forth slowly as expected once, but then, oscillate back and forth very quickly spinning.
#### Expected Result

It should rotate back and forth slowly forever
#### Actual Result

Behaves strangely and osculates quickly back and forth instead of at the pace of the previous actions.
![rotatebug](https://cloud.githubusercontent.com/assets/612071/17833828/5648c522-66ee-11e6-850e-6741c3c31e65.gif)

**Comment by kamranayub** [comment]
Word of advice: look at the constructor. Might be similar to #512

**Comment by kamranayub** [comment]
This also applies to `moveTo`, `moveBy`, and `easeTo` (the first time it repeats)
