### ISSUE TITLE
Actor updates are being called more than once per frame

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#643]
#### Context

I noticed while doing some audio testing (/tests/audio) that when I clicked the red square, the sound actually ended up playing 5 times all at once.

When I stepped through, it's because when we capture pointer events, each browser pointer event is captured in an array during a frame (the array is cleared at the end of a frame).

So, even a single "click" can generate *n* pointer events during a single frame.

Is this expected? It means people need to have guards in their event handlers to compensate for being called multiple times in a single frame.

Keep in mind: there *could* be a case where if you are using multi-touch you could trigger pointer events in multiple locations on the same frame--this is where it may make sense to keep an array.

```
  var i: number = 0, 
        len: number = this._pointerUp.length;

         for (i; i < len; i++) {
            if (actor.contains(this._pointerUp[i].x, this._pointerUp[i].y, !isUIActor)) {
               actor.eventDispatcher.emit('pointerup', this._pointerUp[i]);
            }
         }

         i = 0;
         len = this._pointerDown.length;

         for (i; i < len; i++) {
            if (actor.contains(this._pointerDown[i].x, this._pointerDown[i].y, !isUIActor)) {
               actor.eventDispatcher.emit('pointerdown', this._pointerDown[i]);
            }
         }
```

#### Proposal

I propose only emitting a single `pointerup`, `pointercancel` and `pointerdown` event **per actor** during a frame (first valid pointer event wins). I would leave `pointermove` to allow multiple per frame.

This means, the logic would go:

- For each pointer event in array:
  - If actor contains pointer coords trigger event **and** break out of loop

**Comment by kamranayub** [comment]
@excaliburjs/core-contributers thoughts? I will mark as a bug if you think it makes sense.

**Comment by eonarheim** [comment]
Seems like a bug, go for it

**Comment by kamranayub** [comment]
Found it:

```
while (iter > 0) {
                // Cycle through actors updating actors
                for (i = 0, len = this.children.length; i < len; i++) {
                    this.children[i].update(engine, collisionDelta);
                    this.children[i].collisionArea.recalc();
                }
                // TODO meh I don't like how this works... maybe find a way to make collisions
                // a trait
                // Run collision resolution strategy
                if (this._broadphase && ex.Physics.enabled) {
                    this._broadphase.update(this.children, collisionDelta);
                    this._broadphase.findCollisionContacts(this.children, collisionDelta);
                }
                iter--;
            }
```

It is running actor update multiple times per frame, thus multiple trait updates.
