### ISSUE TITLE
Drawable is too heavy-handed

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#652]
#### Context

It seems to me that `IDrawable` is too prescriptive as an interface. Essentially all IDrawable should enforce is a `draw` function, right? For example, why does every IDrawable need to be able to be flipped? Shouldn't that be an implementation-specific detail? Same with effects.

Case in point: most methods on `Polygon` are not implemented.
#### Proposal

Split up `IDrawable` into a logical set of interfaces that are responsible for distinct things.

**Comment by eonarheim** [comment]
Fixed by #1730
