### ISSUE TITLE
Add some Line math methods

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#662]
#### Context

The current `ex.Line` is limited in its utility for doing line math. It can provide the basics but I'd like some nice utility methods.

#### Proposal

- [x] `ex.Line.m` - Get the slope `m` component of the line equation
- [x] `ex.Line.b` - Get the y-intercept `b` component of the line equation
- [x] `ex.Line.findPoint({ x?, y? })` - Find a point on a line given a single X or a Y value
- [x] `ex.Line.hasPoint(ex.Vector, threshold? = 0)` - Whether or not a line has the given point (optionally provided a threshold). See [this SO post](http://stackoverflow.com/questions/11907947/how-to-check-if-a-point-lies-on-a-line-between-2-other-points)

```ts
export function getLineSlopeValue(ln: ex.Line) {
        return (ln.end.y - ln.begin.y) / (ln.end.x - ln.begin.x);
    }

    export function getLineIntercept(ln: ex.Line, slope: number) {
         return ln.begin.y - (slope * ln.begin.x);
    }

    export function findPoint(ln: ex.Line, x: number = null, y: number = null): ex.Vector {
        var m = getLineSlopeValue(ln);
        var b = getLineIntercept(ln, m);

        if (x !== null) {
            return new ex.Vector(x, (m * x) + b);
        } else if (y !== null) {
            return new ex.Vector((y - b) / m, y);
        }
    }
```

**Comment by eonarheim** [comment]
@kamranayub you mentioned that you already had this implemented IRL
