### ISSUE TITLE
Add PolyEdge physics body

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#664]
### Context

In my desert golf clone, I create a series of points representing the terrain. I then manually create an Actor for each line segment and use edge collisions. This makes it tough because I need to subscribe to collision events for each edge _and_ remove each edge when I'm done with them.

It would be great to create a single actor but pass in an array of points representing line segments to create a poly edge.
### Proposal
``` ts
this.body.usePolyEdgeCollision(points, center?);
```

**Comment by alanag13** [comment]
It's worth noting that if you do something like this, the order in which the points are connected (and therefore passed in) will matter.

You could use something like this to create actors of arbitrary shapes though, which is cool. We could build on this to do stuff like beyond just straight line segments like arcs and such, though I'm not sure if weirdly shaped actors could potentially introduce any collision or physics issues.

**Comment by eonarheim** [comment]
New `CompositeCollider` will allow you to create interesting geometry on the fly like this
