### ISSUE TITLE
ex.Actor.body.oldPos not being set

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#666]
#### Steps to Reproduce

No matter want position an `ex.Actor.body.pos` takes on over time `ex.actor.body.oldPos` stays at (0, 0)
#### Expected Result

oldPos should take on the value of pos from the previous frame

**Comment by kamranayub** [comment]
Two issues I discovered:

1. `oldVel` was wrong, it was being set to the current frame's value
2. `oldVel` (and now `oldPos`) are being set in the `integrate()` method of Actor but that method can be called multiple times per update, hence oldVel and oldPos are probably not accurate for use within an update loop especially if they are supposed to represent the previous frame values.
