### ISSUE TITLE
Is Excalibur typescript 2.0 compatible?

### ISSUE THREAD

**Issue by hogart** [excaliburjs/Excalibur#675]
Sorry if this is wrong place to ask questions, but forum seems deserted.

My problem is that I want to use Excalibur with TypeScript and webpack. I was able to setup webpack and ts compiler so everything works, including loading 3rd-party libs installed with npm (e.g. lodash). It looks like this: https://github.com/hogart/excalibur-test. But at the moment I add `import {ex} from 'excalibur';` I get an `error TS2306: File '<path-to-project>/node_modules/excalibur/dist/excalibur.d.ts' is not a module.`. 

I looked at how lodash .d.ts is written and manually added following to `dist/excalibur.d.ts`:

```ts
export = ex;
export as namespace ex;
```

This did the trick, `ex.Engine` was properly imported and initialized, but this can't be called a solution.

Since I'm pretty new to TS, I'm bit lost. Am I missing something in my `tsconfig.json`? Can this issue be fixed with some custom .d.ts. which re-exports `ex` namespace? Should I downgrade to TypeScript 1.8, since this version used for developing Excalibur?

**Comment by kamranayub** [comment]
With webpack you can set up "Externals" in the webpack config so that you
just include the Excalibur JS dist file on the page without bundling it in
your application. Then things should work. I can try to write a sample to
show. I would probably advise using something simpler maybe first before
trying something like webpack which is more advanced (even I haven't tried
it yet).

**Comment by hogart** [comment]
I followed your advice and simplified things as much as possible, taking into equation only TypeScript 2 and Excalibur, with the following tsconfig.json:

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "amd",
    "outFile": "dist/game.js",
    "target": "es5",
    "sourceMap": true
  },
  "files": ["./game"]
}
```

Error is still the same.
Funny thing is that using TypeScript 1.8 (with appropriate changes) gives same error again. 

Is there a (native for TS) way to use Excalibur with TS?

**Comment by kamranayub** [comment]
If you are going to use module support for Typescript, it cannot be output
to a single file... You would need to use a module loader or something like
webpack still to bundle it. What you want to do is probably use the
<reference/> comments, and just reference the .d.ts file in your game.ts.

Check out some of our sample repositories listed on the gallery, they are
rough but show how we typically compile Typescript.

You can also use Yeoman, check out the excalibur-generator repository. This
will create a blank game with everything set up bare minimum.

Tonight I might be able to put together a webpack example for you.

If anything, this shows we need a Typescript jumpstart for the docs,
apologies for things being confusing.

**Comment by hogart** [comment]
>  it cannot be output to a single file...

Actually, this is no longer the case since `"outFile": "dist/game.js",` option was introduced (don't remember when it was introduced, sorry).

> our sample repositories listed on the gallery

Module systems and loaders in JS is the best thing since sliced bread, because manually putting a bunch of `<script>`s into document is not scalable and extremely error prone.

**Comment by kamranayub** [comment]
What I mean to say is if you use import syntax with module system in
Typescript, it will not bundle all the dependencies into a single output
file. Because it will think you're using a module loader, so it won't
concatenate your application to a single output.

**Comment by kamranayub** [comment]
The workaround you have is what you'll need to do for now. Excalibur hasn't been developed for use with a module loader (yet). One thing we could look at doing possibly is concat'ing the code you have above when we concat the dist file similar to how we concat the version on.

Otherwise there's another issue #606 open that we plan to address module loading formally (and use it within Excalibur too).

**Comment by hogart** [comment]
Ok, I'll watch that issue for news. Thanks for support and great lib:)

Funny thing that at first I tried Phaser and was disappointed that it requires monkey-patching `.d.ts` in order to work with typescript. Anyway, Excalibur is better because it doesn't require ugly crutches to work with webpack and provided typings obviously superior.

**Comment by kamranayub** [comment]
Appreciate it, we still have some work to do. Maybe tonight I will write up a guide on using Ex with module loaders and add it to the docs. @eonarheim did a similar monkey patch for https://github.com/eonarheim/TypeState/pull/13 to support module loading with TS, we could do it the same way.
