### ISSUE TITLE
Bounding boxes should support rotation

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#68]
Currently bounding boxes will not rotate with their actor leading to sub-optimal collision detection

**Comment by kamranayub** [comment]
@eonarheim will this be fixed with AABB?

**Comment by eonarheim** [comment]
@kamranayub Sort of, the AABB Tree makes detecting collisions faster but in order to support rotation we need to implement a new collision primitive that uses the SAT test (Separating Axis Theorem).

I have a working example here http://erikonarheim.com/labs/collision/

**Comment by eonarheim** [comment]
#624 closes this
