### ISSUE TITLE
Ensure Excalibur Promises match A+ spec

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#683]
### Context

Excalibur Promises are similar but different to the A+ spec. We should implement it fully compliant with all tests passing.

### Proposal

Match https://promisesaplus.com/ and ensure all tests listed pass.

**Comment by eonarheim** [comment]
@kamranayub Did we finish this a while ago?

**Comment by eonarheim** [comment]
Closing in favor of #994
