### ISSUE TITLE
Allow setting a global anchor default for Actors

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#705]
### Context

Awhile back we decided it might be a good default to center Actors. I think this is still 50/50 that it is a good default--sometimes I overwrite it to be top left.

I think it might be beneficial to allow us to just decide globally how we want the default anchor to act--i.e. I can choose for my game to anchor all actors (0, 0) or (0.5, 0.5) by default.

### Proposal

A workaround of course is to create a new base actor for your game and set it that way. I propose also allowing a Engine option.

```ts
ex.Engine.defaults.actors.anchor.setTo(0, 0);
```

This could be extended for *x* number of properties and might be useful to set globals.

**Comment by raghavraman** [comment]
Can I contribute to this?

**Comment by eonarheim** [comment]
@raghavraman Go for it! I'll assign myself to make sure no one else grabs it
