### ISSUE TITLE
On bootup, log enabled/detected features

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#707]
#### Context

To aid in browser/device testing, it might be good to have a formal mechanism to register detected/enabled browser features and log them at bootup time so a developer can see what Excalibur sees as enabled or available.

#### Proposal

- [ ] WebGL support
- [ ] Web Audio vs. HTML5 Audio support
- [ ] Gamepad API

**Comment by guahanweb** [comment]
I'll look into this one. Shouldn't be too difficult.

**Comment by guahanweb** [comment]
Playing with some IIFE's in the Detector to have a constant with a feature support matrix available, then outputting some debugging in the Engine setup:
![image](https://cloud.githubusercontent.com/assets/155616/20956029/50f01478-bbfc-11e6-903d-7549a787d400.png)

**Comment by kamranayub** [comment]
That's awesome!

**Comment by eonarheim** [comment]
Very cool!
