### ISSUE TITLE
Remove webkitImageSmoothingEnabled 

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#711]
#### Context

We don't need to set `webKitImageSmoothingEnabled` anymore--it'd be best to have a condition around each of those properties:

```
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated and will be removed in M55, around November 2016. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead. See https://www.chromestatus.com/features/5639849247768576 for more details.
```

```ts
(<any>this.ctx).imageSmoothingEnabled = isSmooth;
(<any>this.ctx).webkitImageSmoothingEnabled = isSmooth;
(<any>this.ctx).mozImageSmoothingEnabled = isSmooth;
(<any>this.ctx).msImageSmoothingEnabled = isSmooth;
```

This is generating a warning in Chrome currently.

#### Proposal

Can be:

```ts
var ctx: any = this.ctx;
ctx.imageSmoothingEnabled = isSmooth;
("webkitImageSmoothingEnabled" in ctx) && ctx.webkitImageSmoothingEnabled = isSmooth;
("mozImageSmoothingEnabled" in ctx) && ctx.mozImageSmoothingEnabled = isSmooth;
("msImageSmoothingEnabled" in ctx) && ctx.msImageSmoothingEnabled = isSmooth;
```

**Comment by kamranayub** [comment]
Hey @guahanweb! Thanks for taking this!

The tests seem to pass in the CI server, can you see which one is failing for you locally?

**Comment by guahanweb** [comment]
Looks like the one failure is a floating point calculation difference:
```
 Vectors
   ✓ should exists
   ✓ can be instantiated
   ✓ can have values set
   ✓ has a Zero constant
   ✓ can test against equality within tolerance
   ✓ can be created from an angle
   X can be transformed to an angle
     Expected 0.7853981633974482 to be 0.7853981633974483. (1)
```
It may be that the difference in that level of precision is due to the platform? I'm running on Mac-64. I'll look at the test and see if there's a way to make it more robust.

**Comment by kamranayub** [comment]
Ah good catch, you can use `expect(value).toBeCloseTo(target, precision)` to fix this 👍

**Comment by guahanweb** [comment]
@kamranayub, good call. I'll fix that right up! To what precision do you care to match? I suspect 10 is sufficient here?

**Comment by kamranayub** [comment]
Yeah, I think a threshold of `0.001` is fine haha, anything small like that.

**Comment by guahanweb** [comment]
Perfect. I erred on the side of accuracy with a precision of 4, but I updated my PR to have that test change in there. I verified that it successfully builds and passes all test on my platform now as well.
