### ISSUE TITLE
Actors sometimes fall through edges that they collide with when stacked high

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#712]
### Steps to Reproduce
1. Open the fastphysics visual test
2. Shoot rockets rapidly in a direction
3. Additionally, let rockets pile up in the box

### Expected Result
Actors should not pass through the edges they collide with.

### Actual Result
When enough Actors pile up, some of them fall through the box.
![fastmovingphysics_1](https://cloud.githubusercontent.com/assets/5409649/20867880/d9082f16-ba13-11e6-8631-178554b2e798.gif)

### Environment

- browser: Google Chrome
- browser version: 54.0.2840.99 m
- operating system: Microsoft Windows 10

**Comment by alanag13** [comment]
Perhaps related but perhaps not: under ideal circumstances in the above test, the box would keep filling up with rockets and none would fall out or leave the borders. What, then, would happen if the box was filled to capacity and the engine attempted spawn another rocket?

**Comment by FerociousQuasar** [comment]
So, after looking into it.
Are physics not calculated in a fixed-step manner?

If physics aren't calculated in a fixed step manner you get non-deterministic behavior the more actors you draw in each scene.
