### ISSUE TITLE
Enable some stricter compiler flags

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#724]
#### Context

We have been bitten before by some of the default TS compiler behavior (such as allowing implicit `any` assumptions), so I'm thinking it might be a force for good to enable some flags that are off by default.

I imagine there might be build errors, so would need to address those.

#### Proposal

Update `tsconfig.json` and set the following `compilerOptions`:

- `noImplicitAny: true`
- `noFallthroughCasesInSwitch: true`
- `noImplicitReturns: true`
- `noImplicitThis: true`
- `noUnusedLocals: true`
- `noUnusedParameters: true`

**Comment by asi7296** [comment]
I have created a pull request.
