### ISSUE TITLE
Investigate greenkeeper.io

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#727]
### Context

Anything that helps dependency management is a plus, would something like Greenkeeper help at all? Not sure.

https://greenkeeper.io/

We are already using shrinkpack which hardens our dependency graph, but something like GK could maybe help us auto-update packages without worrying.

### Proposal

Investigate what GK could do for us and whether or not it's worth using.

**Comment by eonarheim** [comment]
Not needed anymore
