### ISSUE TITLE
Add Engine.getWorldBounds() helper method

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#729]
#### Context

Right now in a scrolling game it can be annoying to constantly calculate the world bounds. To do so, you have to do:

```ts
// left
var wl = game.screenToWorldCoordinates(ex.Vector.Zero).x;
// top
var wt = game.screenToWorldCoordinates(ex.Vector.Zero).y;
// right
var wr = wl + game.getWidth();
// bottom
var wb = wt + game.getHeight();
```

It would be nice to wrap this up into a helper that returns a `BoundingBox`.

#### Proposal

Add a method to Engine called `getWorldBounds()` that returns a `BoundingBox` using the logic above and add unit tests.

```ts
getWorldBounds() {
    // left
    var l = this.screenToWorldCoordinates(ex.Vector.Zero).x;
    // top
    var t = this.screenToWorldCoordinates(ex.Vector.Zero).y;
    // right
    var r = l + this.getWidth();
    // bottom
    var b = t + this.getHeight();

    return new ex.BoundingBox(l, t, r, b);
  }
```

**Comment by PurityLake** [comment]
Is this still open to be implemented, if so I'll write it up

**Comment by eonarheim** [comment]
@PurityLake Awesome, it's all yours!

**Comment by eonarheim** [comment]
I'll assign myself so no one takes it

**Comment by PurityLake** [comment]
@eonarheim will we stick with returning a BoundingBox or should we create a separate class to represent the dimensions?

**Comment by eonarheim** [comment]
@PurityLake I think it makes sense to return the existing `BoundingBox` type, it will allow us to take advantage of its existing methods and features. 

We should also take into account the coordinates in world space as the left, top, bottom, right aspects like the example above which converts the screen coordinates.
