### ISSUE TITLE
Add Angular2/WebPack/SystemJS getting started helper

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#733]
#### Context
There are more and more people trying to use Angular/WebPack/SystemJS with the new ES6 style module syntax and there are a few pitfalls that folks are running into since it requires modifying the Excalibur dist for it to work correctly.

#### Proposal
We should add this documentation to our README and/or have a quickstart for such users in our docs site.

See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/excaliburjs/z_8HThXxkaY

**Comment by kamranayub** [comment]
Done in #734
