### ISSUE TITLE
Engine missing `predraw` and `postdraw` event signatures

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#744]
### Context

Engine is missing signatures for `on('predraw')` and `on('postdraw')` events.

**Comment by PurityLake** [comment]
I'll implement this

**Comment by PurityLake** [comment]
@kamranayub should a spec test be added?

**Comment by kamranayub** [comment]
If possible yes. There should be examples of using the engine to test
drawing, so the tests can just verify those events are triggered.
