### ISSUE TITLE
Add an ex.Button class for easier player interaction

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#749]
### Context
It would be helpful to have a built-in Button class that allowed functionality to happen when a user clicks/taps it.

### Proposal
Something similar to this would be a nice start:
```typescript
class Button extends ex.UIActor {
    // resize and attach the buttonText, and call the function passed in when a user clicks/taps the button
    constructor(x: number, y: number, width: number, height: number, color: ex.Color, buttonText: string, func: () => void) { 
... 
}
```

(see also https://gist.github.com/jedeen/a1c7ec5a4ebac29fce0d9a251475b67e)

**Comment by kamranayub** [comment]
I'll let Josh chime in but I'd say for initial implementation that probably
isn't needed (i.e. what if the arrow keys are already bound during the
gameplay? Requires some more thought on the API/behavior)

**Comment by PurityLake** [comment]
Was just making suggestions, just seeing what sticks

**Comment by kamranayub** [comment]
It's a good idea, maybe we'll pull it into a separate issue once this is implemented.

**Comment by jedeen** [comment]
Addressing keyboard input is a good idea. However, I think an initial implementation that takes care of mouse/touch input should work for now, since that form of input is the minimum necessary for a platform to use Excalibur (e.g. mobile devices).

I agree with @kamranayub. We can open an enhancement issue to add keyboard support to buttons.

**Comment by PurityLake** [comment]
Excellent, just so I'm putting it out there, I think it might be best to make UI generic. Currently I have two new files `UIElement.ts` and `Button.ts`. UIElement implements basically a Blank UI element that reacts to `pointermove`, `pointerdown` and `pointerup` wrapped in an EventHandler class. Button then is a specialisation of UIElement, adding text, font, font size and font color. It will rely on UIElement to draw the base structure, the Button adds the text itself. When I have the code neater and working I'll post it to my fork so you can see it for yourselves

**Comment by PurityLake** [comment]
Sorry, was reading Actor wrong, might be able to rely on that for the drawing of the base element

**Comment by PurityLake** [comment]
[Look at this](https://github.com/PurityLake/Excalibur/commit/76773d580dd761ad2177e4ca5fbb87bc8be5488d)

This is the latest commit for the button addition. `UIElement` is the thing being drawn in the visual test as `Button` isn't finished yet. `Button` is a specialisation of `UIElement` which is itself a specialisation of `UIActor`

**Comment by kamranayub** [comment]
One point of feedback is that UIActor should already be propagating pointer events (except move, which is opt-in) and you can subscribe using `button.on('pointerup', handler)`.

**Comment by PurityLake** [comment]
@kamranayub @jedeen Check [this](https://github.com/PurityLake/Excalibur/tree/add-button) branch out, using the ui visual test I am drawing a button that I've implemented taking into account #410 so let me know what needs changing, it's not finished yet, need to add some data manipulation for the `Button` class and the `UIElement`  class.

**Comment by eonarheim** [comment]
@kamranayub @jedeen Any thoughts?

**Comment by kamranayub** [comment]
Haven't had time to look but I will when I get a chance

**Comment by jedeen** [comment]
@PurityLake Please go ahead and issue a pull request for these changes. It will make it easier to track the differences and provide feedback. It's perfectly all right if a PR is a work in progress. Thanks for working on this feature!

**Comment by PurityLake** [comment]
Have to apologise for the absence, health issues but I'm back again. Gimme a day to reaquaint myself with the code I wrote and I'll make a pull request.

**Comment by LePhil** [comment]
Any news on this issue? Implemented my own version but not happy at all with my own mess...

**Comment by eonarheim** [comment]
@jedeen Any updates?

**Comment by jedeen** [comment]
It appears that there hasn't been any activity on this for a few months now. We'll prioritize this issue for the 0.14.0 Release.

Until then, if you're using TypeScript, you should be able to drop in the [gist](https://gist.github.com/jedeen/a1c7ec5a4ebac29fce0d9a251475b67e) listed in the issue description above.

**Comment by PurityLake** [comment]
I'll get back to this after I finish both reacquainting myself with the code and finish that "good first issue"

**Comment by eonarheim** [comment]
Closing for now, we are moving towards an html first strategy for UI. More to come in the v0.30.0 release on first party HTML UI management in Excalibur
