### ISSUE TITLE
Add utility method to determine if Engine is paused or not

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#750]
### Context
Currently, you can stop/start (i.e. pause/resume) a game with `Engine.start()` and `Engine.stop()`. However, in order to implement pause logic, you need to manage your own boolean:

```typescript
var paused = false;
game.on('p', () => {
   if (!paused) {
      game.stop();
   } else {
      game.start();
   }
   paused != paused;
});
```

### Proposal
The `Engine` already has a private `_hasStarted` variable that appears to be maintaining, but not exposing, this status.

It would be helpful to have an `isStopped()` or `isPaused()` method to return the current state of the game, so the above code could be simplified to:

```typescript
game.on('p', () => {
   if (!game.isPaused()) {
      game.stop();
   } else {
      game.start();
   }
});
```

**Comment by kamranayub** [comment]
If you implement your game UI as all HTML this also works really well, since if the game is stopped no updates/processing will happen but HTML will work fine.

**Comment by SurajGoel** [comment]
Can I take this ?

**Comment by eonarheim** [comment]
@SurajGoel For sure! Please do, let us know if you need any assisstance :)

**Comment by SurajGoel** [comment]
@eonarheim Sorry, didn't see your post. On it now, will update you soon.

**Comment by SurajGoel** [comment]
@eonarheim How should I write a unit test for this ? A simple idea :- Maybe run the engine first, check the status, stop the engine, check the status again. Any ideas ?

**Comment by jedeen** [comment]
@SurajGoel Sounds like a good way to do it! You'll probably want to test that it can be un-paused as well.

This is `Engine` functionality, so I'd recommend putting the test in `EngineSpec.ts`

Now that I'm thinking about it, this is more of a test of the `Engine.start()` and `Engine.stop()` methods. @kamranayub, what do you think?
