### ISSUE TITLE
Use native `Object.assign` for shallow merges in Util.extend

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#763]
### Context

We have a utility, `extend` that supports deep merging. For shallow merges, however, it should use the [new `Object.assign` native functionality](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign) (for perf/compatibility). Currently only IE11 is lacking it.

### Proposal

Update `Util.extend` method to use `Object.assign` where available on shallow merges.

**Comment by PurityLake** [comment]
I'd be up for helping out with this if that's ok

**Comment by eonarheim** [comment]
@PurityLake All yours!

**Comment by eonarheim** [comment]
Assigning myself so no one takes it, let us know if you have questions.

**Comment by PurityLake** [comment]
Typescript doesn't seem to support it, sometimes requires polyfill.

[Typescript issue](https://github.com/Microsoft/TypeScript/issues/3429)

**Comment by kamranayub** [comment]
Just need to test for existence. If it exists then we use it, if not it
does the current code path.

**Comment by PurityLake** [comment]
@kamranayub the problem is that `Object.assign` is an ES2015 feature so `Object.assign` will stop the program from compiling when it is even mentioned.

**Comment by kamranayub** [comment]
I can try checking but all it needs is a type definition or can just be
casted to the any type.

(Object as any).assign

**Comment by PurityLake** [comment]
@kamranayub ah yes, sorry, that slipped my mind
