### ISSUE TITLE
Actors when scaled don't appear to rotate as expected

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#770]
### Steps to Reproduce
When using sprites inside of actors while setting actor scale, the actor's current image does not appear to rotate as expected.

See full repro code below:
```typescript
var game = new ex.Engine({
    width: 800,
    height: 600
});


// create an asset loader
var loader = new ex.Loader();
var resources = {
    txPlayer: new ex.Texture("assets/logo.png")
};

// queue resources for loading
for (var r in resources) {
    loader.addResource(resources[r]);
}

var target = new ex.Actor(500, 500, 20, 20, ex.Color.Red);
game.add(target);

var aim = new ex.Actor(200, 200, 100, 100, ex.Color.Black);
aim.addDrawing(resources.txPlayer);
aim.setHeight(10);
aim.scale.setTo(1, .5);
game.add(aim);

// uncomment loader after adding resources
game.start(loader).then(() => {

    game.input.pointers.primary.on('move', (ev: ex.Input.PointerEvent) => {
        target.pos.setTo(ev.x, ev.y);

        var aimVec = target.pos.sub(aim.pos);
        aim.rotation =  aimVec.toAngle();
    });

});
```

The current work around is to scale the sprite separately instead of the actor.

`actor.currentDrawing.scale.setTo(1, .5)`

### Expected Result
The excalibur logo while scaled to .5 height should point at the cursor

![works](https://cloud.githubusercontent.com/assets/612071/24533729/2e1f0fde-158f-11e7-8337-ef477361e85f.gif)

### Actual Result
The excalibur logo kind of points at the cursor, but is scaled oddly as it rotates around

![notworks](https://cloud.githubusercontent.com/assets/612071/24533715/1821a6f6-158f-11e7-8dc6-e0a6708989c6.gif)

### Proposal

Fix rotation with scaled actors to behave as expected.

**Comment by kamranayub** [comment]
Well, if you want a sweet "top down projection" rotation effect, that'll do it 💃

**Comment by eonarheim** [comment]
@kamranayub It does have a orthographic projection look to it... might be something to keep in mind for the future

**Comment by HSAR** [comment]
Question - is there a projected release date for this fix? Wondering if I should apply the work-around, or just forge on and wait for a patch.

**Comment by eonarheim** [comment]
@HSAR We are planning on cutting the 0.10.0 release next week sometime, if this is merged soon it will make it into the next release.
