### ISSUE TITLE
Refactor drawing transformations to use setTransform()

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#771]
### Context
Currently we are using a non optimal way to manipulate the canvas for drawing transformations. According to JSPerf https://jsperf.com/transform-vs-settransform/4 we could be getting more draw performance out of this. Since this is in the heart of the core draw loop we could seriously boost perf.

### Proposal
Replace all calls to `ctx.translate`,`ctx.rotate`, and `ctx.scale` with the appropriate matrix transformation in `ctx.setTransform`

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform

**Comment by Cictani** [comment]
I ran the benchmark and setTransform wasn't the fastest .... but setting translate, rotate and scale individually was.

**Comment by eonarheim** [comment]
Interesting I'm seeing that too on mobile brave, what browser are you using?

Theoretically their browserscope still shows it being better. More investigation required for sure

**Comment by Cictani** [comment]
I use Chrome 68.0.3440 on Windows 10. Edge is faster with setTransform.  If I use the latest revision of the benchmark which only tests translate it is also faster on Edge.

Their browserscope shows a lot of older versions of web browsers.

**Comment by eonarheim** [comment]
I wonder if there is a hardware acceleration difference between the platforms... it also seems that multiple runs produce different results on my hardware accelerated laptop...

**Comment by eonarheim** [comment]
The jury is out on any meaningful performance gains here, closing for now
