### ISSUE TITLE
How to draw game in center of screen.

### ISSUE THREAD

**Issue by Majirefy** [excaliburjs/Excalibur#780]
Excalibur draws game content on the left top of the screen.
Is it possible to change that? Draw the canvas in the center of the screen?

**Comment by kamranayub** [comment]
If you're looking to change the canvas position, typically we just use CSS
to center or put the canvas wherever we need.

The following styles will center the canvas:

    canvas { margin: 0 auto }

Older browsers sometimes need `text-align: center` applied on the parent
element (body) but auto margin usually centers elements. Our samples
typically center the canvas on screen.

**Comment by kamranayub** [comment]
It wouldn't be a bad idea to have a canvas position parameter in engine
options that adds these styles for you. Typically I want more control so I
use CSS myself but not everyone knows CSS necessarily

**Comment by Majirefy** [comment]
Thanks! @kamranayub 
Is it possible to use webGL?

**Comment by kamranayub** [comment]
Not at this time, all the draw logic in Excalibur is based on the 2D
context. A core drawing rewrite may lead to webgl support, but not sure yet
what implications that'll have.

**Comment by Majirefy** [comment]
Thanks!

There are few game engine in TypeScript, and Excalibur is a good one.
Happy to see more improvements in the future!

**Comment by kamranayub** [comment]
Closing in favor of enhancement #781
