### ISSUE TITLE
Add engine option to allow positioning the canvas

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#781]
### Context

Right now you can position the game canvas using CSS, however not everyone may know how to do this effectively, especially if they want to vertically center the canvas.

### Proposal

Add an engine option `canvasPosition` that will add some styles to position the canvas:
- top / bottom / middle
- left / right / center
- absolute value (CSS object, `{ top: '4px', left: '50%', right: 6, bottom: '4em' }`)

Can use an enumeration for the positional values. The CSS object should treat strings as raw values to apply to the styles. Numbers should be interpreted in pixels.

Flexbox can be used to position the canvas according to the layout needed, while `position: absolute` can be used for the absolute positioning. Flexbox may require a parent wrapper element to be generated OR we can just apply the styles to whatever the parent element is for the game canvas.

This is entirely **optional** and advanced users will be expected to use their own CSS to customize the game canvas.

**Comment by andrewmbyrd** [comment]
I've started to take a look at this issue, and I'm making a few observations as I dive in and try to figure out the code base.

1. It seems we should be able to adjust canvas position only when `ex.DisplayMode` is `Fixed` or 'Container' (not `FullScreen`)
2. Users should be able to select  (top/bottom/middle , left/right/center) OR (absolute value). So they could want a canvas position of for example `top`, or `top and left`, or _only_ an `absolute value`.  
Should there then be an enumeration for each of CanvasHorizontalPosition, and CanvasVerticalPosition, and Canvas AbsolutePosition?

**Comment by kamranayub** [comment]
This might be an opportunity to consolidate the display modes.

- ex.DisplayMode.Fullscreen
- ex.DisplayMode.Fixed
- ex.DisplayMode.Container
- ex.DisplayMode.Position

We can then add an `IEngineOptions` property for `position` that accepts a string OR absolute position object. If the user provides `ex.DisplayMode.Position` and they do *not* provide a position property we should throw an error.

```
position: string  | AbsolutePosition;
```

The relative CSS positioning format is the same as `[background-position](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position)` following the same rules (exception only the keywords are allowed so e.g. `top` or `top right`).

We can use Flexbox to position the canvas, either by creating a wrapper element automatically or adding `display: flex` to the parent element.

The absolute position object is just:

```
interface AbsolutePosition {
  top: number | string;
  left: number | string;
  right: number | string;
  bottom: number | string;
}
```

That will get translated directly into CSS styles for `position: absolute` and the values directly passed into the corresponding TLRB value.
