### ISSUE TITLE
Semicolon key command doesn't work in Firefox

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#789]
Note: this is not an issue in Google Chrome. There may be other keys that also cause this issue.

### Steps to Reproduce
```typescript
game.input.keyboard.on('down', (keyDown?: ex.Input.KeyEvent) => {
    switch(keyDown.key) {
        case ex.Input.Keys.Semicolon :
            ex.Logger.getInstance().info('semicolon pressed');
            break;
        default :
            ex.Logger.getInstance().warn('unsupported key command');
    }
});
```

### Expected Result
"semicolon pressed"

### Actual Result
"unsupported key command"

### Environment

- browsers and versions: Firefox 53.0 (32-bit)
- operating system: Windows 7
- Excalibur versions: Excalibur 0.10.0

**Comment by jedeen** [comment]
Additional context: http://stackoverflow.com/questions/3883543/javascript-different-keycodes-on-different-browsers

**Comment by kamranayub** [comment]
Browsers are the worst
