### ISSUE TITLE
Implement a consistent coding style

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#79]
We need a consistent coding style within the codebase. It will help us as contributors and people new to TypeScript. It also looks more professional when it's consistent. For example, I prefer no space before a type declaration (`myVar: string`) but you do (`myVar : string`); I prefer spaces between lambdas (`() => {`) but there are instances where that isn't the case.

We should either try to use a tool on build to reformat or find a ST plugin to invoke when we want to format a selection/file.

We also need to outline the coding style in the CONTRIBUTING guidelines.

**Comment by eonarheim** [comment]
This is tied in with the linting storing in #394 closing this issue
