### ISSUE TITLE
Incorrect Instructions on Documentation Site

### ISSUE THREAD

**Issue by andrewmbyrd** [excaliburjs/Excalibur#790]
### Context
On your [documentation website](http://docs.excaliburjs.com/en/latest/quickstart.html), the instructions for walking through the introductory Block Breaker game reference a `game.getHeight()` method. You mention in the [release page](https://github.com/excaliburjs/Excalibur/releases/tag/v0.10.0) that for version 0.10.0 `Engine.getHeight()` no longer works and has been replaced by `Engine.getDrawHeight()`

### Proposal

I propose simply updating the documentation site with the new `getDrawHeight()` method call.

Also, Hello! New OSS contributor here, hoping I can be of service on this project! I'm happy to make this small change if I can get access to the html file in question for the documentation site.

**Comment by kamranayub** [comment]
Documentation is just in the docs folder of the repository. Feel free to
submit a PR!
