### ISSUE TITLE
Upgrade to TS 2.5 or 2.6.1 if possible

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#794]
### Context
TypeScript 2.5 has been released:
https://blogs.msdn.microsoft.com/typescript/2017/08/31/announcing-typescript-2-5/

### Proposal
- [x] Update Typedoc
- [x] Update core

**Comment by eonarheim** [comment]
TypeScript 2.6.1 just dropped we should see if it's possible to jump here, theoretically TypeDoc may still work with a newer version of ts 
https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/

**Comment by kamranayub** [comment]
Typedoc can do 2.4 now

**Comment by kamranayub** [comment]
There's a regression it appears that causes issues with the new option bag (#753), so I think we have to rollback to TS < 2.3.3.

https://github.com/Microsoft/TypeScript/issues/21871
