### ISSUE TITLE
Rename ex.Scene.children to ex.Scene.actors

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#796]
### Context
Currently, it is conceptually confusing when trying to get at actors in a scene. It doesn't make sense that the collection in a scene is called children. It should be named for what it is :) 

This will be a breaking change, so we could potentially add backwards compatibility getter/setter to call through to the new `ex.Scene.actors`. Something like the below code perhaps with a deprecation warning decorator? (unfortunately decorators in TS can't be added to a getter AND it's setter 😢 )

![image](https://cloud.githubusercontent.com/assets/612071/25557100/ceffed0e-2ccf-11e7-82f6-9a9913a5cf8d.png)

```typescript
/**
  * The actors in the current scene
  */
 public actors: Actor[] = [];

 @obsolete({ alternateMethod: 'ex.Scene.actors' })
 public set children (actors: Actor[]) {
    this.actors = actors;
 }

 public get children (): Actor[] {
    return this.actors;
 }
```

### Proposal

* Refactor `ex.Scene.children` to be renamed to `ex.Scene.actors`
* Update specs to reflect change
* Update visual tests in /sandbox/tests

**Comment by alanag13** [comment]
In line with what happened when we changed getHeight and getWidth, we should also check for documentation that mentions the use of .children

**Comment by kamranayub** [comment]
Yes I think a deprecation is okay, we can remove it for 1.0

**Comment by Crizzooo** [comment]
Is this still open? I can attempt it.

As far as what @eonarheim was saying with backwards compatability - could we write one children method to match both the get and set? If an argument is present, it sets children based on the argument. Else, it functions as a get and returns the children.

Forgive me if Im misunderstanding how TS works in this case.

**Comment by kamranayub** [comment]
@Crizzooo You can go for it.

Unfortunately we can't use a method, because existing calls to `.children` will fail (since it was a property before, not a method). A getter/setter like above should work fine.
