### ISSUE TITLE
When setting Vector type setters/getters, we should implicitly clone to avoid bugs

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#797]
### Context
This recently bit me during Ludum Dare 38. I assigned an `ex.Actor.pos` to a point that was part of another type which consisted of a grid of `ex.Vector`'s 

The problem can be easily demonstrated thus
```typescript
var actor1 = new ex.Actor();

var actor2 = new ex.Actor();

var point = new ex.Vector(10, 10);

actor1.pos = point;
actor2.pos = point;

actor1.moveTo(20, 100);
// BOTH ACTOR1 and ACTOR2 move!!!
// they share the pos reference
```
The reason this happens, is because Vector (even though I want to treat it like a value type) is actually a reference type, and the reference in this case is shared causing problems and tricky bugs to find since you'd expect mathematically for points to be just a value.

### Proposal

I think we should implicitly call the `.clone()` on vector when setters and getters take or emit `ex.Vector` anywhere in excalibur, I think this will eliminate a class of hard to track down bugs when working with actors. 

You do sacrifice the ability to retrieve the reference of the Vector and treat it as one and do tricky things with it and squeeze perfomance out of it. However, I'd argue that people should be doing things like that with things that are conceptually value types, it would be like retrieving a reference to the number 5 and changing it's value for people using it to 8 or something.

```typescript
/**
 * Gets the position vector of the actor in pixels
 */
public get pos(): Vector {
   return this.body.pos.clone();
}

/**
 * Sets the position vector of the actor in pixels
 */
public set pos(thePos: Vector) {
   this.body.pos = thePos.clone();
}
```

**Comment by alanag13** [comment]
Are there any valid use cases for keeping this behavior? Can we think of a scenario where a developer would want multiple actors to share a reference with the same Vector?

**Comment by eonarheim** [comment]
@alanag13 I'd argue that even if you could come up with one, the potential to blow your own foot off is too great. And conceptually it's weird to share a value, it's like they share the number 5 but somehow its value was changed under you.

**Comment by alanag13** [comment]
I agree, just playing devils advocate. Changing the behavior of a getter/setter always feels a little weird to me

**Comment by kamranayub** [comment]
I think this makes sense, we want to treat it as much like a value type as we can
