### ISSUE TITLE
Fix odd method name ex.Util.removeItemToArray to ex.Util.removeItemFromArray

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#798]
### Context
This is an oddly worded confusing method ex.Util.removeItem**To**Array, it just needs to be renamed. 

### Proposal
Rename it to ex.Util.removeItem**From**Array

**Comment by Crizzooo** [comment]
Can I take this as a first PR? does seem very easy though hahaha

**Comment by eonarheim** [comment]
Go for it! :)

**Comment by Crizzooo** [comment]
Changed the method and added test specs. I think I followed most rules I found in the Contributing guidelines as far as writing tests, referencing changes/issues, making the PR - how'd I do?

I didn't do much, but that was fun. Got any other beginner issues to get my feet wet with?

**Comment by kamranayub** [comment]
Anything tagged jump-in is up for grabs! Plenty of work to be done!

**Comment by Crizzooo** [comment]
@kamranayub Cool, I'm currently eyeing #612 and getting familiar with TypeScript now. This one seems pretty easy, just making this.pos = new Vector(x, y), but I'm waiting for some feedback before going forward.

**Comment by Crizzooo** [comment]
@kamranayub or @eonarheim  - this issue can be closed and was handled in #812

**Comment by kamranayub** [comment]
@Crizzooo Actually that PR was closed because the commits were lost. I'd make a new branch and re-submit.

**Comment by htalat** [comment]
can i submit a pr for this if its still open

**Comment by jedeen** [comment]
Closed in 0.11.0
