### ISSUE TITLE
Actors that are killed are still colliding

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#799]
### Steps to Reproduce
After an actor is killed the on.collision method is still happening sometimes, `collision!` will be logged multiple times.

```typescript
this.on('collision', (e?: ex.CollisionEvent) => {
    console.log('collision!')
    e.other.kill();
    // In order to work around this you need to set the actor to PreventCollision
    // e.other.collisionType = ex.CollisionType.PreventCollision;
});
```
This problem can be demonstrated in the ludum-38 repo https://github.com/excaliburjs/ludum-38/blob/fa840bb2022e0c1d552f4e3a93a11e0dd5580000/game/Player.ts#L75

### Expected Result
I would have expected actors not to participate in collisions after they've been killed. The example above should only log `collision!` once.

### Actual Result
Actors seem capable of colliding multiple times after they've been killed.

**Comment by alanag13** [comment]
It seems kinda hacky, but could a potential solve for this just be to simply set the collision type to PreventCollision in the kill method itself?

**Comment by jedeen** [comment]
@alanag13 That would solve the immediate issue. It would not solve other potential problems, such as extra non-collision events being fired because the Actor is still around after it's supposed to be gone.

**Comment by kamranayub** [comment]
I'll look into this

**Comment by eonarheim** [comment]
I believe we put a work-around for this into the latest ludum branch, could be useful place to start
