### ISSUE TITLE
Add ex.Sound per-play volume setting

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#801]
### Context
It is slightly clumsy to play sounds at different volumes dynamically. It would be nice to have a new way to play a sound on demand at a specific volume. Currently you need to set the `ex.Sound.volume` property then call `.play()` then set the `.volume` property for every play that you want at a different volume. We should also be able to dynamically change volume while playing.

### Proposal

Add a `ex.Sound.play(volume)` or a `ex.Sound.playAt(volume)` method for per play volume settings and should return a promise that resolves with the sound play is done..

```typescript
var sound = new ex.Sound();
sound.playAt(.5); // play once at a specific maximum volume
```

**Comment by andrewmbyrd** [comment]
I could take a look at this. Seems like updating the existing `Sound.play` method to take a volume parameter should work: `Sound.play(volume?: number)`.

With setting a profile, would you envision that after setting with `sound.withProfile(profile)`, that any future calls to `sound.play()` would make use of that profile information?

I'm only slightly familiar with interpolation curves. In CSS, there's basically linear and cubic-bezier. (ease, ease-in, ease-out, etc. all vary up the parameters of the cubic bezier function). Should the options for `interpolator` be just `linear` and 'cubic'? And if the user chooses `cubic` then they'll provide parameters with the `volume` option?

**Comment by kamranayub** [comment]
@eonarheim Let's separate this into two issues, since per-play volume is a lot easier to jump in and fix.

**Comment by eonarheim** [comment]
@andrewmbyrd @kamranayub I've split these into two separate issues, since the per-play is much simpler to implement. And sound profiles are more nebulous 
https://github.com/excaliburjs/Excalibur/issues/804
