### ISSUE TITLE
Replace mock.engine with real engine

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#805]
### Context

I think new and core contributors alike are getting a bit confused with what approach to test the engine. We don't need to use `mock.engine` anymore, that is deprecated. This was used back before engine's dependencies were made testable.

The only key thing to remember is to stop the engine after each test so it gets cleaned up, otherwise there will be multiple engines running which causes all sorts of issues.

### Proposal

Delete `mock.engine` and replace with `TestUtil.engine`. See ScaleSpec for recommended approach. I *think* the loop mock can also be deprecated, but it could also be retooled to work with the real engine.

**Comment by UmangThapliyal** [comment]
Hello, I want to contribute to the project can I work on it if it is still open

**Comment by eonarheim** [comment]
@UmangThapliyal All yours, there is a test utility to return a real Engine configured for testing `TestUtils.engine();` UIActorSpec.ts is a good example.
