### ISSUE TITLE
game/game.ts(47,24): error TS2339: Property 'x' does not exist on type 'GameEvent<any>'.

### ISSUE THREAD

**Issue by prubini87** [excaliburjs/Excalibur#828]
Hello, I've encountered a problem while trying to follow one of the starting tutorials. "npm start" is returning the error in the title. The tutorial I'm following is this: [Hello Excalibur: Building Breakout!](http://docs.excaliburjs.com/en/latest/quickstart.html).

game.ts(47,24) is 
`game.input.pointers.primary.on('click', function (evt) {
    paddle.pos.x = evt.x;
    paddle.pos.y = evt.y;
});`

Apparently "evt" is a GameEvent object and that object has only one property, named target, as I inspected in Excalibur source code:

excalibur.amd.d.ts(6107)
`export class GameEvent<T> {
        /**
         * Target object for this event.
         */
        target: T;
    }`

So, I tried editing the javascript file directly (game.js) and it works with evt.x, evt.y, etc, but npm start won't compile the typescript file and will return the error mentioned...

Does anyone know anything about that?

**Comment by kamranayub** [comment]
It should be typed as PointerEvent, not GameEvent. It could be a bug with
our overload signature. You can explicitly type it by doing evt:
PointerEvent in the callback method.
