### ISSUE TITLE
Implement more robust image diff matching tests

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#833]
### Context
Image diff tests are non-deterministic across platforms and often times on the same platform (for example font rendering changed slightly between versions of windows 10). We need to come up with a more robust way of doing image tests that allows for some slack and not a "pixel perfect" test approach which is brittle.

### Proposal
Craft a new Jasmine 2.x matcher with a new image diff implementation that can be tolerant of some image deviation.

**Comment by eonarheim** [comment]
As part of this issue we should uncomment the tests for #800 `CameraSpec.ts` to validate

**Comment by eonarheim** [comment]
Also related to #820

**Comment by alanag13** [comment]
This seems to be happening on more tests over time, most recently headless chrome seems to have some rendering difference on windows vs linux. One idea I had was to generate a different comparison image for each OS we're testing against and have the test determine which one to use. Thoughts?

**Comment by kamranayub** [comment]
I think the only real difference is font rendering and in that case, having
a slightly more tolerant diff will fix the issue while still catching
actual abnormalities.
