### ISSUE TITLE
Add a ex.Timer.on/off method to easily add multiple callbacks

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#839]
### Context
Add `ex.Timer.on` and `ex.Timer.off` methods to timer, right now it is hard to add callbacks to timer since it is a constructor argument. Also I want to make the constructor argument optional if we add these methods.

### Proposal
Something like this
```typescript
// forever 200 ms timer
var timer = new ex.Timer(200, true);
timer.on(() => {
   spawnNewEnemy();
})
```

```typescript
var timer = new ex.Timer(200, true);
var spawnHandler = spawnNewEnemy;
timer.on(spawnHandler);
timer.off(); // remove all handlers
timer.off(spawnHandler); // remove specific handler
```

**Comment by htalat** [comment]
was going through the code to see if I can do this,
doesn't the timer have a single handler?

**Comment by eonarheim** [comment]
@htalat Correct, right now time only supports a single handler. This would allow timers to support multiple handlers, and possibly change the constructor signature to remove the old handler definition (or maybe make it optional?)
