### ISSUE TITLE
Breakout Demo link is broken

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#843]
### Steps to Reproduce
1. Navigate to https://excaliburjs.com/samples/ 
2. Click on the Breakout sample Demo link (https://erikonarheim.com/labs/breakout)

### Expected Result
Load the Breakout Demo

### Actual Result
404 File not found

**Comment by kamranayub** [comment]
Shouldn't it link to the fiddle we have?

**Comment by jedeen** [comment]
@kamranayub That's what we should probably update it to, yes.
