### ISSUE TITLE
Create Sample games

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#845]
### Context
We should have more example games of best practices Excalibur development.

### Proposal
Create several small sample games to do so.

Potential list:

- [ ] shoot 'em up (base exists)
- [ ] Excalibird (base exists)
- [ ] breakout (base exists)
- [ ] basic platformer
- [ ] pong
- [ ] basic turn-based game (checkers or something similar)
- [ ] a few physics demos
- [ ] etc. etc.

Ideally, these games could also serve as automated tests for Excalibur.

**Comment by eonarheim** [comment]
@kberg Thanks for spotting this, we'll get sorted soon

**Comment by eonarheim** [comment]
Closing we have samples up to date with CI and tests
