### ISSUE TITLE
Add `backgroundColor` to IEngineOptions

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#846]
### Context

You can set the `backgroundColor` property on an instance of engine but cannot pass it in via the constructor options.

```
var game = new ex.Engine({
    width: 1280,
    height: 720    
});
game.backgroundColor = ex.Color.White;
```

### Proposal

Add `backgroundColor` to `IEngineOptions` and allow setting it that way. It should be as easy as adding a new property and then setting it in the Engine constructor.

```
var game = new ex.Engine({
    width: 1280,
    height: 720,
    backgroundColor: ex.Color.White
});
```

**Comment by htalat** [comment]
Hi, 
I'd like to work on this.

**Comment by kamranayub** [comment]
Thanks @htalat! Make sure to review the contributing guidelines for what we expect and we look forward to seeing your PR!
