### ISSUE TITLE
Add `Color.toHex()`, `toRGBA()`, and `toHSLA()` methods

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#852]
### Context

Color supports converting *from* Hex/HSL representation but not back to them (only RGBA).

### Proposal

Modify Color class:

1. Add a new instance method `toHex()`.
2. Add a new instance method `toRGBA()`
3. Add a new instance method `toHSLA()`
3. Add an optional param `type` to `toString()` that accepts a string, either `rgb`, `hsl` or `hex` parameter (default: "rgb" to maintain backwards compat). Depending on value, it should call either of the three new instance methods.

**Comment by htalat** [comment]
hey! can i work on this?

**Comment by kamranayub** [comment]
@htalat Absolutely, your PR inspired this one when I noticed these were missing 👍

**Comment by htalat** [comment]
haha great!

**Comment by htalat** [comment]
what to return in case an invalid format is provided?

```
   public toString(format = 'rgb') {
      if (format === 'rgb')
         return this.toRGBA();
      
      if(format === 'hsl')
         return this.toHSLA();
      
      if(format === 'hex')
         return this.toHex();

      return 'invalid format';  // what would be the correct way to handle this flow?
   }
```

**Comment by kamranayub** [comment]
I would throw an error (throw new Error("foo"))
