### ISSUE TITLE
Add support for cell spacing in TileMap

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#860]
### Context

Tiled lets you add cell spacing to the grid. TileMap should support that. See https://github.com/excaliburjs/excalibur-tiled/issues/11

### Proposal

Add new `cellSpacing` property to TileMap and draw accordingly.

**Comment by eonarheim** [comment]
Fixed in https://github.com/excaliburjs/Excalibur/issues/1058
