### ISSUE TITLE
High DPI Support for Excalibur

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#861]
### Steps to Reproduce
On high DPI screens, assets in Excalibur do not scale correctly as expected for the screen. In order to reproduce this run https://sarasflare.com/play/#/login 

An explanation of the issue is located here in the excalibur google group https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/excaliburjs/GgOyA8dQd8E 

We should look at investing in a high DPI screen or any emulation tools that can repro this locally.

### Expected Result
Assets should be scaled to the appropriate size on high DPI screens
![image](https://user-images.githubusercontent.com/612071/29089885-71f50572-7c43-11e7-9714-436bf29a06e7.png)

### Actual Result
Assets are scaled incorrectly 

![image](https://user-images.githubusercontent.com/612071/29089915-89173202-7c43-11e7-84ae-d608ad58e678.png)

**Comment by kamranayub** [comment]
Resource: https://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by eonarheim** [comment]
This is super awesome https://material.io/devices/
