### ISSUE TITLE
CollisionGroups do not work at all

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#862]
### Steps to Reproduce
The `.onCollidesWith` handler does not fire when active collision types collide with groups added with `.addCollisionGroup` that match the filter in the handler.

Here is a codepen reproducing the issue https://codepen.io/eonarheim/pen/LjjeEm 
Left click to move the read block right, right click to move the blue block left. 

We also have a second "Group" type that is confusing on which should be used.

### Expected Result
What should happen is that a message should be written if the blocks collide since there is a collision group handler on actor1.

### Actual Result
As far as I can tell this does not happen, possibly a regression during the collision system over-haul.

**Comment by eonarheim** [comment]
In fact upon further review they seem to be half implemented... perhaps this was a leftover from a hopeful implemenation or from the `Groups` implementation?

**Comment by eonarheim** [comment]
This is an interesting read and may be pertinent to this issue http://www.aurelienribon.com/blog/2011/07/box2d-tutorial-collision-filtering/

**Comment by moonblade** [comment]
Is there any updates on this issue?

**Comment by eonarheim** [comment]
@moonblade None yet, we intend to redesign the way collision groups work. We are definitely open to suggestions/ideas on what you'd like to see in a feature like this.
