### ISSUE TITLE
Loading text resources fails

### ISSUE THREAD

**Issue by jordanroher** [excaliburjs/Excalibur#872]
### Steps to Reproduce

1. Have a resource that references a text file, e.g. `MainData: new ex.Resource("/play/res/fonts/main.txt", "text")`
2. Add this resource to the loader
3. Load the resource

### Expected Result

- The **public load(): Promise<T>** function inside **Resource.ts** sets `this.data` to the contents of the text file

### Actual Result

- Receive this error from **public processData(data: T): any** inside **Resource.ts**
    `TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.`
- The signature (data) is the content of the text file. **URL.createObjectURL** doesn't like arbitrary strings.

### Environment
- browsers and versions: Google Chrome 60.0.3112.90 (Official Build) (64-bit)
- operating system: Windows 10 Pro 64-bit v1703 Build 15063.540
- Excalibur versions: 0.11

### Workaround discovered

**Resource.ts** lines 83-90

      switch(this.responseType) {
         case "text":
            this.data = request.response;
            break;
         default:
            this.data = this.processData(request.response);
            break;
      }

**Comment by kamranayub** [comment]
Is the response time a valid MIME type? Unrelated to the issue, I think,
just wondering if it should be `text/plain`

**Comment by kamranayub** [comment]
The proper way to address this I think is to inspect whether the return response is a byte stream or plaintext and act accordingly, that way it'll work for other plain text MIME types.

**Comment by jordanroher** [comment]
I tried `text/plain` but it didn't like that. URL.createObjectURL throws the fairly unhelpful `TypeError: Type error`

**Comment by kamranayub** [comment]
Well, I think you'd still need your workaround, I was just commenting on using the standard MIME type.

Also, as a workaround, I think you can extend `Resource` and override the `processData` method to do what you like.

(pseudo)

```ts
class PlainResource extends Resource<string>
  processData(data) {
    this.data = data;
  }
}
```

**Comment by jordanroher** [comment]
That... almost worked. I tried setting `this.data` in `processData()` manually, but in `getData()` it insists that `this.data` is null.

But this worked, so I'm good.

	class TextResource extends ex.Resource<string> {
		textData: string;

		processData(data: string): void {
			this.textData = data;
		}

		public getData(): string {
			return this.textData;
		}
	}
