### ISSUE TITLE
Actor should not have its own opacity property

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#874]
### Context
`Actor` should not have its own opacity property. Currently, it's used to facilitate the `Fade` Action, and to override the opacity of the Actor's `color` property (if it has one). This has the potential to cause confusion, over which property is actually used (see #837).

### Proposal
`Actor.opacity` should be deprecated in favor of using the opacity of `Actor.color.a` or `Actor.currentDrawing.opacity` (if the `IDrawable` has an opacity property, such as if it is a `Sprite`)

**Comment by kamranayub** [comment]
Yeah I think this makes sense

**Comment by eonarheim** [comment]
The fade action is going to need to be retooled to take this into account, but I think this is a good idea.

**Comment by djcsdy** [comment]
Just wasted a bunch of time on this. It could not possibly be more confusing. Everything about Actor.opacity is inconsistent and broken.

 * Constructing an Actor with a color causes the opacity of the Actor to be set the the alpha value of the color, but subsequently updating the alpha value of the color has no effect.
 * Setting the color of an existing Actor (with opacity > 0) to `Color.Transparent` causes the Actor to turn black and retain its previous opacity.
 * Drawables attached to an actor use the opacity set by the Actor but ignore the color.
 * Actor sets `this.color.a = this.opacity` in its `update` function (**WHY?!**) so classes that extend Actor and define their own `draw` function inherit the weird relationship between `color` and `opacity`. For example, `Label`. They could override `update` but then they lose the existing implementation of a bunch of other useful stuff.
 * It's just awful and I don't much care for it at all.

**Comment by kamranayub** [comment]
> It's just awful and I don't much care for it at all.

That is a good summation 😄 Yes, this should be tackled soon along with the rest of the  drawing infrastructure rewrite.
