### ISSUE TITLE
If the opacity of an Actor's drawing/color is 0, don't draw the actor

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#875]
### Context
If an Actor's `currentDrawing` or `color` has it's opacity set to 0, the Actor will still draw transparent pixels to the canvas.

### Proposal
Set `Actor.visible` to false if the Actor's drawing or color is 100% transparent, to prevent transparent pixels from being drawn.

**Comment by tskull01** [comment]
I would like to handle this.

**Comment by eonarheim** [comment]
@tskull01 Go for it, I recommend refactoring visible to a getter/setter pair and implementing the logic in the setter.

**Comment by eonarheim** [comment]
@tskull01 let me know if you would like any assistance

**Comment by DProBoy** [comment]
@eonarheim Can i handle this issue ?

**Comment by SirKitboard** [comment]
Is this issue still open?
I see that there were commits related to it but the issue is marked as openn

**Comment by eonarheim** [comment]
@SirKitboard It is! All yours! 

There are a couple approaches, hooking into the internal [_postupdate](https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Actor.ts#L1544) and checking the Actor's color opacity then setting visible or not may make the most sense.
