### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#884]
### Context

[Prettier](https://github.com/prettier/prettier) auto-formats code before commit (or on save) to code standards set for the project. This should make code style a non-issue for new contributors and for the team.

### Proposal

Implement Prettier with our current TSLint rules.

1. Add the git hook using husky, as outlined in their README
2. Recommend using Prettier VSCode plug-in (optional) in our README
3. Remove lint step from grunt

**Comment by htalat** [comment]
can i have a go at this one?

**Comment by eonarheim** [comment]
@htalat For sure! I've assigned myself to prevent anyone else from grabbing this

**Comment by htalat** [comment]
so i have set up prettier but tslint wont run.
is it just me getting this error on running tslint?

```
Warning:
            Could not find implementations for the following rules specified in the configuration:
            array-bracket-spacing
block-spacing
brace-style
conditional-expression-parens
import-destructuring-spacing
import-spacing
jsx-alignment
jsx-attribute-spacing
jsx-curly-spacing
jsx-equals-spacing
jsx-expression-spacing
jsx-no-closing-bracket-newline
jsx-no-multiline-js
jsx-wrap-multiline
literal-spacing
no-empty-line-after-opening-brace
no-irregular-whitespace
no-multi-spaces
no-semicolon-interface
no-unnecessary-parens-for-arrow-function-arguments
no-unnecessary-semicolons
object-curly-spacing
react-tsx-curly-spacing
space-before-function-paren
space-in-parens
space-within-parens
ter-arrow-parens
ter-arrow-spacing
ter-func-call-spacing
ter-indent
ter-max-len
ter-no-irregular-whitespace
            Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
            If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
         Use --force to continue.
```

**Comment by kamranayub** [comment]
Tslint runs normally, otherwise we'd notice builds failing.

**Comment by eonarheim** [comment]
Hi @htalat, have you run an npm install after cloning/forking? 

I double checked a fresh clone of master that tslint is running

```
git clone https://github.com/excaliburjs/Excalibur.git test-clone
cd test-clone
npm install
npm run all
```

The tslint portion runs for me and outputs 
```
Local build, using version "local"
Running "tslint:src" (tslint) task
>> 130 files lint free.
```

**Comment by htalat** [comment]
so, was getting this error after making changes so I updated tslint then I was getting linting errors. (which means lint is running)
Do you want me to update to the latest tslint or the next version that works?
currently: `"^3.13.0"`
latest: `5.7.0'

**Comment by kamranayub** [comment]
Yeah we should update! Good opportunity to do so.
