### ISSUE TITLE
Investigate rollup for distribution

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#895]
### Context

The current way we create dists is kind of complex with grunt and TS using AMD with Almond.js embedded and a UMD wrapper.

### Proposal

Try looking at [Rollup](https://rollupjs.org/) to create `excalibur.es.js` and `excalibur.js` dists that accomplish the same as what we have now.

**Comment by eonarheim** [comment]
We are going to stick with webpack for time being, we'll re-open if a good reason presents itself to look into another bundler
