### ISSUE TITLE
Excalibur dist automation improperly tags releases

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#900]
### Context
The excalibur-dist travis automation improperly tags our main releases
https://github.com/excaliburjs/excalibur-dist/blob/030f936461bac790cb7ccca5182b657d0ec0b012/.travis.yml#L18

We need to update the automation so that only alpha builds are tagged in the 'next' channel

### Steps to Reproduce
Publish a Excalibur Release
example: https://travis-ci.org/excaliburjs/excalibur-dist#L445

### Expected Result
main release is tagged in 'latest' channel in NPM

### Actual Result
main release is tagged in the 'next' channel instead of 'latest'

**Comment by eonarheim** [comment]
Closed https://github.com/excaliburjs/excalibur-dist/commit/ac5c5599f1b077526c36d8abc7ab93ab11c33347
