### ISSUE TITLE
Add ability to repeat a timer a finite number of times

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#905]
### Context
Currently, timers can either fire once, or fire repeatedly on their specified interval (until `timer.pause()` or `timer.cancel()` is explicitly called). I recently had the need to use a timer to fire a specific number of times, and then stop firing.

### Proposal
Build-in the ability for a timer repeat a finite number of times.

*Proposed API for Timer*:
```typescript
constructor(fcn: () => void, interval: number, repeats?: boolean, repeatAmount?: number)
```
The timer will stop firing after it has repeated the number of times specified by `repeatAmount`.

*Current workaround*:

```typescript
var timerInterval = 1000; //ms
var timerRepeatCount = 0;
var timerRepeatMax = 3;
var timer = new ex.Timer(() => {
   ex.Logger.getInstance().info('timer fired');
   timerRepeatCount++;
   if (timerRepeatCount >= timerRepeatMax) {
      timer.cancel();
   }
}, timerInterval, true);
game.add(timer);
```

**Comment by Dreaded-Gnu** [comment]
It seems that the milestone has been forgotten here, it's still `vNext`. Shouldn't it be `0.17.0`? Same also with the pull request which has been merged two days ago.
