### ISSUE TITLE
Different/Custom EmitterTypes for Particles

### ISSUE THREAD

**Issue by LePhil** [excaliburjs/Excalibur#906]
### Context
Particle Emitters and their types

### Proposal
Use custom shapes or even images as an EmitterType so we could have effects like coins, hearts, bubbles, stars etc.

**Comment by eonarheim** [comment]
@LePhil I 100% agree, this would be awesome

**Comment by kamranayub** [comment]
Can we already set a sprite right now? I don't have the docs in front of me.

**Comment by jedeen** [comment]
Sprites currently [supported](https://excaliburjs.com/docs/api/edge/classes/_particles_.particleemitter.html#particlesprite), although they are performance intensive.

**Comment by LePhil** [comment]
Ah my apologies, did not see that at all. Will work on my effects and my reading skills.

**Comment by LePhil** [comment]
...but maybe an example could be included in the Particle Tester (https://excaliburjs.com/particle-tester/)?

**Comment by eonarheim** [comment]
@LePhil I totally forgot you could add sprites (and I wrote it!) Let me know if you need any assistance

The documentation here is definitely lacking

**Comment by LePhil** [comment]
All good, got my hearts effect :revolving_hearts:  ![image](https://user-images.githubusercontent.com/1488366/32862425-5d30da40-ca58-11e7-9c1d-96ebceef4107.png)

Took a minute to figure out why setting the sprite's scale didn't work until I saw that it's determined by the particle's max/min size: https://github.com/excaliburjs/Excalibur/blob/4ac682a/src/engine/Particles.ts#L137
