### ISSUE TITLE
Stop Pointer-Event from propagating

### ISSUE THREAD

**Issue by LePhil** [excaliburjs/Excalibur#912]
### Context
If there are 2 actors overlapping and both listen to pointer events and the overlapping area is clicked, both receive the click event. This is not always desirable.

Demo: https://codepen.io/piko_/pen/ooPNaB

### Proposal
It would be good to be able to stop the propagation of input events.

**Comment by kamranayub** [comment]
Stop propogation would definitely be a nice feature, and should match the
typical standard used in other libs, e.stopPropagation()

**Comment by eonarheim** [comment]
Agreed, it shouldn't be too difficult to include this behavior in our event handling scheme

**Comment by LePhil** [comment]
Implementation and Unittests can be found in https://github.com/excaliburjs/Excalibur/compare/master...LePhil:master, by the way. I'll add more unit tests later.

**Comment by pathurs** [comment]
I'd like to try this one next, if that's okay.

What will I do?
`Event.stopPropagation()` should work the same way as https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

**Comment by kamranayub** [comment]
Yeah if we can follow the spec that will follow our goal of least surprise.
Thanks @Pathurs!

**Comment by pathurs** [comment]
I will probably do #389 as well as add support for `Event.preventDefault()` to my changes for this. Most likely plus some extra improvements, because who doesn't like free stuff?
