### ISSUE TITLE
Add feature to pull Animations out of a packed SpriteSheet

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#918]
### Context

Currently Excalibur sprite sheets only optimize for neatly arranged in rows and columns when extracting animations. Many assets now are arranged into tightly packed sprite sheets to save on space and download size. 

### Proposal
Excalibur `ex.SpriteSheet` should support a way to specify a list of bespoke sprite coordinates to generate an `ex.Animation`. 

Phil on the forums posted this motivation which makes a lot of sense

> Most of the image resources I have are not aligned in rows and columns but are tightly packed, e.g. lots of resources from kenney.nl. This means I can't use them to create an ex.Spritesheet. Is there any way to create an animation from the single sprites from a texture? E.g. pass an array of {x,y,w,h} objects instead of indices on getAnimationByIndices?

A possible api might look like this

```typescript

export interface ISpriteCoordinates {
   x: number;
   y: number;
   width: number;
   height: number;
}

// create sprite sheet with 5 columns, 1 row, 80x80 frames
let playerIdleSheet = new ex.SpriteSheet(txAnimPlayerIdle);

  // create animation (125ms frame speed)
let playerIdleAnimation = playerIdleSheet.getAnimationByCoords({x: 10, y: 10, width: 100, height: 100},{x: 120, y: 10, width: 100, height: 100},{x: 120, y: 10, width: 100, height: 100},);

```

**Comment by LePhil** [comment]
I'm wondering how one could align the individual sprites. I *assume* most should be aligned at the bottom, but I can imagine some sprites to be aligned by the center...

**Comment by eonarheim** [comment]
I think right now things are oriented from the top left position when defining sprites, and sprites have a top left (0, 0) defined anchor by default. https://excaliburjs.com/docs/api/edge/classes/_drawing_sprite_.sprite.html#anchor

We could allow an optional anchor on a per sprite basis, what do you think of this?

```typescript
export interface ISpriteCoordinates {
   x: number;
   y: number;
   width: number;
   height: number;
   anchor?: ex.Vector
}
```

**Comment by LePhil** [comment]
Yeah that should work. Also, the dimensions of the animation would need to be gathered from the largest sprite, I think.

**Comment by eonarheim** [comment]
I think that would make sense 👍

**Comment by alanag13** [comment]
I actually sneaked something into #753 that might offer a good start to this: the ability to pass an arbitrary `Sprite` array to the `SpriteSheet` constructor rather than have to pull from an image and use rows/columns. More work probably needs to be done (e.g. as mentioned setting the size of the animation based on the largest sprite), but it was an abstraction that made sense to me.
