### ISSUE TITLE
Allow repeat-x/y for Sprites

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/Excalibur#922]
### Context
Particularly for UI actors and for in-game walls/scenery (think a dialog box with a "rope" border around it or a row of trees marking the border of a scene), it is sometimes necessary to repeat the same drawing multiple times in succession along a x or y axis. We've done this with Tiled, but there isn't a good way to do it in the "stock" engine aside from calculating a length and duplicating the Sprite as needed.

### Proposal
Add optional css-like repeatX and repeatY properties to sprites. These would default to false, but when enabled would continuously add additional renderings of the Sprite along the appropriate axis until the entire height and/or width of the actor was consumed.

**Comment by eonarheim** [comment]
This has been accidentally implemented, see #2744
