### ISSUE TITLE
Standardize manual visual tests

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#946]
### Context
The current state of the manual visual tests makes them easy to overlook, and sometimes difficult to determine if they're actually passing.

### Proposal
1. Write precise acceptance criteria for all manual visual tests, documented within the test
2. Convert as many of the manual visual tests into automated tests as possible
3. Streamline the remaining manual visual tests (if any) to make them easy to use

**Comment by eonarheim** [comment]
Closing for now
