### ISSUE TITLE
Update Excalibur descriptions

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#959]
In the spirit of ensuring we are describing Excalibur in a succinct and modern way, I'm proposing reviewing the descriptions we use.

- **Tagline**:  A simple HTML5 Canvas game engine written in TypeScript 

- **Description**: Excalibur is a simple, free game engine written in TypeScript for making 2D games in HTML5 canvas. Our goal is to make it incredibly simple to create 2D HTML/JS games, for folks new to game development as well as experienced game developers. We take care of all of the boilerplate engine code, cross-platform targeting, and more so you don't have to. Use as much or as little as you need!

- **GitHub organization tagline**: HTML5 Game Engine

**Comment by jedeen** [comment]
Proposal:

- **Tagline**:  A simple Canvas game engine written in TypeScript 

- **Description**: Excalibur is a simple, free 2D engine for making games in TypeScript/JavaScript. We're here to help, whether you're new to game development or an experienced game developer. We take care of the boilerplate engine code, cross-platform targeting, and more so you don't have to. Use as much or as little as you need!

- **GitHub organization tagline**: TypeScript/JavaScript Game Engine

**Comment by kamranayub** [comment]
@jedeen Do you think the average user looking for engines keys off of "Canvas" to know it's web-based? I think IRL I mentioned maybe wording like...

> A simple web-based game engine written in TypeScript

The other thing I wonder about is the notion of "simple". I want people to know we strive for a simple API but a powerful engine. I'm worried that may imply Excalibur itself is "simple" (and yes, I know we don't have allll the features of bigger engines but we're getting there!).

**Comment by eonarheim** [comment]
I think I agree on both points, I like `web-based` and maybe to convey that we want the API to be simple, maybe something like `A web-based game engine with a simple API written in TypeScript`?

**Comment by jedeen** [comment]
Good points and changes, but I'd recommend avoiding additional prepositional phrases (for the tagline, at least)
Perhaps this:
>An intuitive web-based game engine written in TypeScript

**Comment by alanag13** [comment]
I like "intuitive" over "simple" because the latter has connotation of meaning stripped down/not feature heavy. How do you feel about "for the web" instead of "web-based??

> An intuitive game engine for the web written in TypeScript

**Comment by kamranayub** [comment]
Now I'm worried "for the web" precludes the fact you can actually *deploy*
games to other non-web platforms like mobile/desktop/etc. Saying
"web-based" leaves it open for cross platform deployments?

**Comment by alanag13** [comment]
That's fair. I don't really like `web-based` because (at least in my head) the engine is not based on the web itself, but I also can't think of a better term to use right now.

**Comment by kamranayub** [comment]
What about...

> An intuitive TypeScript-based game engine for web-based platforms

> An intuitive TypeScript-based game engine for web platforms

> An intuitive cross-platform TypeScript game engine to make awesome web-based games

> An intuitive TypeScript game engine to make awesome JavaScript games

**Comment by jedeen** [comment]
I like the second one the most, of those four.

**Comment by eonarheim** [comment]
@excaliburjs/core-contributors Have we reached consensus?

**Comment by kamranayub** [comment]
OK more now, let's take care of this!

> An open source TypeScript game engine for making 2D web games

> An open source 2D game engine for the web, written in TypeScript

> An open source 2D game engine for the web, with first-class support for TypeScript

> An open source 2D game engine for the web, made with TypeScript

**Comment by eonarheim** [comment]
I believe this has been done
