### ISSUE TITLE
Dragging a window to another screen with Excalibur running causes odd behavior

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#976]
### Steps to Reproduce
Drag a running excalibur window to another screen

### Expected Result
Excalibur should handle this case and display the game as expected

### Actual Result
Placement of game elements is off, forcing a browser refresh to correct.

### Current Workaround
None

**Comment by kamranayub** [comment]
Is this due to changing DPI?

**Comment by eonarheim** [comment]
@kamranayub Possibly due to that, if so the fix will probably require us to recalculate canvas scaling on window resize...

**Comment by eonarheim** [comment]
Closed by #1733
