### ISSUE TITLE
Sprites don't work when created in onInitialize

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#980]
### Steps to Reproduce
I believe this is due to an issue with the backing canvas for sprites when created, the draw method (at least in firefox) does not allow for width/height drawings. I believe this is the fix https://github.com/excaliburjs/Excalibur/commit/bf4d8852925b3ecb5878baefe71e97dc6cf6b91b

https://codepen.io/eonarheim/pen/qYNeYM?editors=0011

```typescript
let game = new ex.Engine({
  width: 600,
  height: 400
});

let tex = new ex.Texture('https://cdn.rawgit.com/excaliburjs/Excalibur/7dd48128/assets/sword.png');

let loader = new ex.Loader([tex]);

let actor = new ex.Actor(100, 100, 50, 50, ex.Color.Red);
actor.onInitialize = () => {
  let sprite = new ex.Sprite({
    image: tex,
    x: 0,
    y: 0,
    width: 100,
    height: 100
  });
  actor.add(sprite);
}
game.add(actor);
game.start(loader);
```

### Expected Result
Textures have been loaded by initialize time, this style of sprite creation should work

### Actual Result
A DOM exception results

### Environment
excalibur@0.16.0

### Current Workaround
None

**Comment by eonarheim** [comment]
@AimedNuu We will do our best to release this in 0.18.0, unfortunately we could not fit this into 0.17.0. We make bugs our top priority.

**Comment by AimedNuu** [comment]
@eonarheim That's great, thanks.

**Comment by alanag13** [comment]
@eonarheim FYI I think there's a mistake in your codepen (`actor.add` should be `actor.addDrawing`). I was going to see if I could get this one taken care of, just thought you'd want to know.

**Comment by eonarheim** [comment]
@alanag13 good catch, I'll fix that soon
