### ISSUE TITLE
Sometimes actor keeps accelerating while on the ground

### ISSUE THREAD

**Issue by rmvermeulen** [excaliburjs/Excalibur#986]
### Steps to Reproduce
On the left side of the floor, _only_ while going right, the vertical speed will keep increasing to some maximum before resetting. The same happens on the rights sice, _only_ when going left.
The maximum seems to relate to the horizontal component, the faster you go the fast you fall.

https://jsfiddle.net/0rt3unh1/
in jsfiddle the inputs do not work, so I used timeouts to show the motion vector changing.

shortened code sample:
```js
const engine = new ex.Engine()
engine.isDebug = true
Physics.acc.setTo(0, 200)
Physics.showMotionVectors = true
const floor = new ex.Actor({ collisionType: ex.CollisionType.Fixed })
const player = new ex.Actor({ collisionType: ex.CollisionType.Active })
player.update = (e, ms) => {
  if (keyboard.isHeld(Space)) player.vel.x = 0
  if (keyboard.isHeld(Left)) player.vel.x -= 10
  if (keyboard.isHeld(Right)) player.vel.x += 10
  ex.Actor.prototype.update.call(player, e, ms)
}
engine.add(floor)
engine.add(player)
engine.start()

```

### Expected Result
The actor does not accelerate 'in the background' while colliding with objects that block it's path.
In this simple case, when the player collides with the floor it's vertical speed should always be (near) zero.

### Actual Result
The actor continues to accelerate after collision, when the described conditions are met.
When an actor crosses the edge it already has an sorta random downward velocity and falls immediately.

### Environment
- browsers and versions: 
  - Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- operating system: macOS 10.13.4
- Excalibur versions: 0.15 - latest

### Workaround
Explicitly set velocity to zero on post-collision event.

**Comment by eonarheim** [comment]
We've tried to model the physics off the real world were possible. So I'd always expect vertical acceleraction to be active when sitting on a platform or the ground, but the velocity vertical component should theoretically be zero. 

Since this is a simulation I'd expect at least at or near zero on post-collision which doesn't seem to be the case.

**Comment by rmvermeulen** [comment]
Exactly, I meant that the actual speed is increasing while sitting on the platform. I'll update the OP with that and the workaround.
