### ISSUE TITLE
Support older JS with modern JS features (i.e const, let, arrow functions, etc.). 

### ISSUE THREAD

**Issue by LoserAntbear** [excaliburjs/Excalibur#989]
### Context
@eonarheim proposed creating this issue. So changes to older version of js code could be stashed and tracked in one place.

Currently Excalibur uses some more outdated JS, it would be nice to update to newer es2016, es2017 features like const, let, and arrow functions where appropriate

### Proposal
Update Excalibur file by file with newer features.

Let's do this one file at a time per commit if possible so we can discuss changes incrementally.

**Comment by eonarheim** [comment]
Closing in favor of #1102
